CREATE TABLE "OptionDataYahooHistoryDaily" (
	snapshot_date DATE NOT NULL,
	symbol TEXT NOT NULL,
	expiration_date DATETIME, 
	"option-type" TEXT, 
	"contractSymbol" TEXT, 
	strike FLOAT, 
	currency TEXT, 
	"lastPrice" FLOAT, 
	change FLOAT, 
	"percentChange" FLOAT, 
	option_open_interest BIGINT, 
	bid FLOAT, 
	ask FLOAT, 
	"contractSize" TEXT, 
	"lastTradeDate" DATETIME, 
	"impliedVolatility" FLOAT, 
	"inTheMoney" BOOLEAN, 
	option_volume FLOAT,
	UNIQUE(snapshot_date, "contractSymbol")
);
DROP TABLE IF EXISTS "OptionDataYahoo";
CREATE TABLE "OptionDataYahoo" (
	symbol TEXT, 
	expiration_date DATETIME, 
	"option-type" TEXT, 
	"contractSymbol" TEXT, 
	strike FLOAT, 
	currency TEXT, 
	"lastPrice" FLOAT, 
	change FLOAT, 
	"percentChange" FLOAT, 
	option_open_interest BIGINT, 
	bid FLOAT, 
	ask FLOAT, 
	"contractSize" TEXT, 
	"lastTradeDate" DATETIME, 
	"impliedVolatility" FLOAT, 
	"inTheMoney" BOOLEAN, 
	option_volume FLOAT,
	UNIQUE("contractSymbol")
);
DROP TABLE IF EXISTS "OptionDataTradingView";
CREATE TABLE "OptionDataTradingView" (
	ask FLOAT, 
	bid FLOAT, 
	delta FLOAT, 
	gamma FLOAT, 
	iv FLOAT, 
	"option-type" TEXT, 
	rho FLOAT, 
	strike FLOAT, 
	"theoPrice" FLOAT, 
	theta FLOAT, 
	vega FLOAT, 
	option TEXT, 
	time TEXT, 
	symbol TEXT, 
	exchange TEXT, 
	expiration_date BIGINT, 
	option_osi TEXT,
	UNIQUE(option_osi)
);
CREATE TABLE "OptionDataTradingViewHistoryDaily" (
	snapshot_date DATE NOT NULL,
	ask FLOAT, 
	bid FLOAT, 
	delta FLOAT, 
	gamma FLOAT, 
	iv FLOAT, 
	"option-type" TEXT, 
	rho FLOAT, 
	strike FLOAT, 
	"theoPrice" FLOAT, 
	theta FLOAT, 
	vega FLOAT, 
	option TEXT, 
	time TEXT, 
	symbol TEXT, 
	exchange TEXT, 
	expiration_date BIGINT, 
	option_osi TEXT,
	UNIQUE(snapshot_date, option_osi)
);
