CREATE TABLE "DataAgingFieldClassification" (
    table_name TEXT NOT NULL,
    field_name TEXT NOT NULL,
    tier TEXT DEFAULT 'Daily', -- 'Daily', 'Weekly', 'Monthly', 'Master'
    last_value TEXT,
    last_change_date DATE,
    tier_entry_date DATE,
    PRIMARY KEY (table_name, field_name)
);
ALTER TABLE "OptionDataTradingViewHistoryDaily" RENAME TO "OldOptionDataTradingViewHistoryDaily";
CREATE TABLE "OptionDataTradingViewHistoryDaily" (
	snapshot_date DATE,
	option_osi TEXT,
	symbol TEXT, 
	"option-type" TEXT,
	expiration_date BIGINT,
	strike FLOAT, 
	ask FLOAT, 
	bid FLOAT, 
	delta FLOAT, 
	gamma FLOAT, 
	iv FLOAT, 
	rho FLOAT, 
	"theoPrice" FLOAT, 
	theta FLOAT, 
	vega FLOAT, 
	option TEXT, 
	time TEXT, 
	exchange TEXT,
	PRIMARY KEY(snapshot_date, option_osi)
);
INSERT INTO "OptionDataTradingViewHistoryDaily" (
    snapshot_date,
	option_osi,
	symbol, 
	"option-type",
	expiration_date,
	strike, 
	ask, 
	bid, 
	delta, 
	gamma, 
	iv, 
	rho, 
	"theoPrice", 
	theta, 
	vega, 
	option, 
	time, 
	exchange
)
SELECT
    snapshot_date,
	option_osi,
	symbol, 
	"option-type",
	expiration_date,
	strike, 
	ask, 
	bid, 
	delta, 
	gamma, 
	iv, 
	rho, 
	"theoPrice", 
	theta, 
	vega, 
	option, 
	time, 
	exchange
FROM
    "OldOptionDataTradingViewHistoryDaily";
DROP TABLE "OldOptionDataTradingViewHistoryDaily";
CREATE TABLE "OptionDataTradingViewHistoryMonthly" (
	year INT,
	month INT,
	option_osi TEXT,
	symbol TEXT, 
	"option-type" TEXT,
	expiration_date BIGINT,
	strike FLOAT, 
	ask FLOAT, 
	bid FLOAT, 
	delta FLOAT, 
	gamma FLOAT, 
	iv FLOAT, 
	rho FLOAT, 
	"theoPrice" FLOAT, 
	theta FLOAT, 
	vega FLOAT, 
	option TEXT, 
	time TEXT, 
	exchange TEXT,
	PRIMARY KEY(year, month, option_osi)
);
CREATE TABLE "OptionDataTradingViewHistoryWeekly" (
	year INT,
	week INT,
	option_osi TEXT,
	symbol TEXT, 
	"option-type" TEXT,
	expiration_date BIGINT,
	strike FLOAT, 
	ask FLOAT, 
	bid FLOAT, 
	delta FLOAT, 
	gamma FLOAT, 
	iv FLOAT, 
	rho FLOAT, 
	"theoPrice" FLOAT, 
	theta FLOAT, 
	vega FLOAT, 
	option TEXT, 
	time TEXT, 
	exchange TEXT,
	PRIMARY KEY(year, week, option_osi)
);
CREATE TABLE "OptionDataTradingViewMasterData" (
	option_osi TEXT PRIMARY KEY,
	symbol TEXT, 
	"option-type" TEXT,
	expiration_date BIGINT,
	strike FLOAT, 
	ask FLOAT, 
	bid FLOAT, 
	delta FLOAT, 
	gamma FLOAT, 
	iv FLOAT, 
	rho FLOAT, 
	"theoPrice" FLOAT, 
	theta FLOAT, 
	vega FLOAT, 
	option TEXT, 
	time TEXT, 
	exchange TEXT
);
ALTER TABLE "OptionDataYahooHistoryDaily" RENAME TO "OldOptionDataYahooHistoryDaily";
CREATE TABLE "OptionDataYahooHistoryDaily" (
	snapshot_date DATE NOT NULL,
	"contractSymbol" TEXT,
	symbol TEXT,
	"option-type" TEXT, 
	expiration_date DATETIME, 
	strike FLOAT, 
	currency TEXT, 
	"lastPrice" FLOAT, 
	change FLOAT, 
	"percentChange" FLOAT, 
	option_open_interest BIGINT, 
	bid FLOAT, 
	ask FLOAT, 
	"contractSize" TEXT, 
	"lastTradeDate" DATETIME, 
	"impliedVolatility" FLOAT, 
	"inTheMoney" BOOLEAN, 
	option_volume FLOAT,
	PRIMARY KEY(snapshot_date, "contractSymbol")
);
INSERT INTO "OptionDataYahooHistoryDaily" (
    snapshot_date,
	"contractSymbol",
	symbol,
	"option-type", 
	expiration_date, 
	strike, 
	currency, 
	"lastPrice", 
	change, 
	"percentChange", 
	option_open_interest, 
	bid, 
	ask, 
	"contractSize", 
	"lastTradeDate", 
	"impliedVolatility", 
	"inTheMoney", 
	option_volume
)
SELECT
    snapshot_date,
	"contractSymbol",
	symbol,
	"option-type", 
	expiration_date, 
	strike, 
	currency, 
	"lastPrice", 
	change, 
	"percentChange", 
	option_open_interest, 
	bid, 
	ask, 
	"contractSize", 
	"lastTradeDate", 
	"impliedVolatility", 
	"inTheMoney", 
	option_volume
FROM
    "OldOptionDataYahooHistoryDaily";
DROP TABLE "OldOptionDataYahooHistoryDaily";
CREATE TABLE "OptionDataYahooHistoryMonthly" (
	year INT,
	month INT,
	"contractSymbol" TEXT,
	symbol TEXT,
	"option-type" TEXT, 
	expiration_date DATETIME, 
	strike FLOAT, 
	currency TEXT, 
	"lastPrice" FLOAT, 
	change FLOAT, 
	"percentChange" FLOAT, 
	option_open_interest BIGINT, 
	bid FLOAT, 
	ask FLOAT, 
	"contractSize" TEXT, 
	"lastTradeDate" DATETIME, 
	"impliedVolatility" FLOAT, 
	"inTheMoney" BOOLEAN, 
	option_volume FLOAT,
	PRIMARY KEY(year, month, "contractSymbol")
);
CREATE TABLE "OptionDataYahooHistoryWeekly" (
	year INT,
	week INT,
	"contractSymbol" TEXT,
	symbol TEXT,
	"option-type" TEXT, 
	expiration_date DATETIME, 
	strike FLOAT, 
	currency TEXT, 
	"lastPrice" FLOAT, 
	change FLOAT, 
	"percentChange" FLOAT, 
	option_open_interest BIGINT, 
	bid FLOAT, 
	ask FLOAT, 
	"contractSize" TEXT, 
	"lastTradeDate" DATETIME, 
	"impliedVolatility" FLOAT, 
	"inTheMoney" BOOLEAN, 
	option_volume FLOAT,
	PRIMARY KEY(year, week, "contractSymbol")
);
CREATE TABLE "OptionDataYahooMasterData" (
	"contractSymbol" TEXT PRIMARY KEY,
	symbol TEXT,
	"option-type" TEXT, 
	expiration_date DATETIME, 
	strike FLOAT, 
	currency TEXT, 
	"lastPrice" FLOAT, 
	change FLOAT, 
	"percentChange" FLOAT, 
	option_open_interest BIGINT, 
	bid FLOAT, 
	ask FLOAT, 
	"contractSize" TEXT, 
	"lastTradeDate" DATETIME, 
	"impliedVolatility" FLOAT, 
	"inTheMoney" BOOLEAN, 
	option_volume FLOAT
);
DROP TABLE IF EXISTS "EarningDates";
CREATE TABLE "EarningDates" (
	symbol TEXT PRIMARY KEY, 
	earnings_date TEXT
);
DROP TABLE IF EXISTS "FundamentalDataDividendRadar";
CREATE TABLE "FundamentalDataDividendRadar" (
	"Symbol" TEXT PRIMARY KEY, 
	"Company" TEXT, 
	"FV" FLOAT, 
	"Sector" TEXT, 
	"No-Years" BIGINT, 
	"Price" FLOAT, 
	"Div-Yield" FLOAT, 
	"5Y-Avg-Yield" FLOAT, 
	"Current-Div" FLOAT, 
	"Payouts/-Year" BIGINT, 
	"Annualized" FLOAT, 
	"Previous-Div" FLOAT, 
	"Ex-Date" DATETIME, 
	"Pay-Date" DATETIME, 
	"Low" FLOAT, 
	"High" FLOAT, 
	"DGR-1Y" FLOAT, 
	"DGR-3Y" FLOAT, 
	"DGR-5Y" FLOAT, 
	"DGR-10Y" FLOAT, 
	"TTR-1Y" FLOAT, 
	"TTR-3Y" FLOAT, 
	"Fair-Value" TEXT, 
	"FV-%" FLOAT, 
	"Streak-Basis" TEXT, 
	"Chowder-Number" FLOAT, 
	"EPS-1Y" FLOAT, 
	"Revenue-1Y" FLOAT, 
	"NPM" FLOAT, 
	"CF/Share" FLOAT, 
	"ROE" FLOAT, 
	"Current-R" FLOAT, 
	"Debt/Capital" FLOAT, 
	"ROTC" FLOAT, 
	"P/E" FLOAT, 
	"P/BV" FLOAT, 
	"PEG" FLOAT, 
	"New-Member" FLOAT, 
	"Industry" TEXT, 
	"Classification" TEXT
);
DROP TABLE IF EXISTS "FundamentalDataYahoo";
CREATE TABLE "FundamentalDataYahoo" (
	symbol TEXT PRIMARY KEY, 
	"asOfDate" DATETIME, 
	"periodType" TEXT, 
	"currencyCode" TEXT, 
	"AccountsPayable" FLOAT, 
	"AccountsReceivable" FLOAT, 
	"AccruedInterestReceivable" FLOAT, 
	"AccumulatedDepreciation" FLOAT, 
	"AdditionalPaidInCapital" FLOAT, 
	"AllowanceForDoubtfulAccountsReceivable" FLOAT, 
	"Amortization" FLOAT, 
	"AmortizationCashFlow" FLOAT, 
	"AmortizationOfIntangibles" FLOAT, 
	"AmortizationOfIntangiblesIncomeStatement" FLOAT, 
	"AmortizationOfSecurities" FLOAT, 
	"AssetImpairmentCharge" FLOAT, 
	"AssetsHeldForSaleCurrent" FLOAT, 
	"AvailableForSaleSecurities" FLOAT, 
	"AverageDilutionEarnings" FLOAT, 
	"BasicAverageShares" FLOAT, 
	"BasicEPS" FLOAT, 
	"BeginningCashPosition" FLOAT, 
	"BuildingsAndImprovements" FLOAT, 
	"CapitalExpenditure" FLOAT, 
	"CapitalExpenditureReported" FLOAT, 
	"CapitalLeaseObligations" FLOAT, 
	"CapitalStock" FLOAT, 
	"CashAndCashEquivalents" FLOAT, 
	"CashCashEquivalentsAndShortTermInvestments" FLOAT, 
	"CashDividendsPaid" FLOAT, 
	"CashEquivalents" FLOAT, 
	"CashFinancial" FLOAT, 
	"CashFlowFromContinuingFinancingActivities" FLOAT, 
	"CashFlowFromContinuingInvestingActivities" FLOAT, 
	"CashFlowFromContinuingOperatingActivities" FLOAT, 
	"CashFlowFromDiscontinuedOperation" FLOAT, 
	"CashFlowsfromusedinOperatingActivitiesDirect" FLOAT, 
	"CashFromDiscontinuedFinancingActivities" FLOAT, 
	"CashFromDiscontinuedInvestingActivities" FLOAT, 
	"CashFromDiscontinuedOperatingActivities" FLOAT, 
	"ChangeInAccountPayable" FLOAT, 
	"ChangeInAccruedExpense" FLOAT, 
	"ChangeInCashSupplementalAsReported" FLOAT, 
	"ChangeInDividendPayable" FLOAT, 
	"ChangeInIncomeTaxPayable" FLOAT, 
	"ChangeInInterestPayable" FLOAT, 
	"ChangeInInventory" FLOAT, 
	"ChangeInOtherCurrentAssets" FLOAT, 
	"ChangeInOtherCurrentLiabilities" FLOAT, 
	"ChangeInOtherWorkingCapital" FLOAT, 
	"ChangeInPayable" FLOAT, 
	"ChangeInPayablesAndAccruedExpense" FLOAT, 
	"ChangeInPrepaidAssets" FLOAT, 
	"ChangeInReceivables" FLOAT, 
	"ChangeInTaxPayable" FLOAT, 
	"ChangeInWorkingCapital" FLOAT, 
	"ChangesInAccountReceivables" FLOAT, 
	"ChangesInCash" FLOAT, 
	"ClassesofCashPayments" FLOAT, 
	"ClassesofCashReceiptsfromOperatingActivities" FLOAT, 
	"CommercialPaper" FLOAT, 
	"CommonStock" FLOAT, 
	"CommonStockDividendPaid" FLOAT, 
	"CommonStockEquity" FLOAT, 
	"CommonStockIssuance" FLOAT, 
	"CommonStockPayments" FLOAT, 
	"ConstructionInProgress" FLOAT, 
	"CostOfRevenue" FLOAT, 
	"CurrentAccruedExpenses" FLOAT, 
	"CurrentAssets" FLOAT, 
	"CurrentCapitalLeaseObligation" FLOAT, 
	"CurrentDebt" FLOAT, 
	"CurrentDebtAndCapitalLeaseObligation" FLOAT, 
	"CurrentDeferredAssets" FLOAT, 
	"CurrentDeferredLiabilities" FLOAT, 
	"CurrentDeferredRevenue" FLOAT, 
	"CurrentDeferredTaxesAssets" FLOAT, 
	"CurrentDeferredTaxesLiabilities" FLOAT, 
	"CurrentLiabilities" FLOAT, 
	"CurrentNotesPayable" FLOAT, 
	"CurrentProvisions" FLOAT, 
	"DeferredIncomeTax" FLOAT, 
	"DeferredTax" FLOAT, 
	"DefinedPensionBenefit" FLOAT, 
	"Depletion" FLOAT, 
	"DepletionIncomeStatement" FLOAT, 
	"Depreciation" FLOAT, 
	"DepreciationAmortizationDepletion" FLOAT, 
	"DepreciationAmortizationDepletionIncomeStatement" FLOAT, 
	"DepreciationAndAmortization" FLOAT, 
	"DepreciationAndAmortizationInIncomeStatement" FLOAT, 
	"DepreciationIncomeStatement" FLOAT, 
	"DerivativeProductLiabilities" FLOAT, 
	"DilutedAverageShares" FLOAT, 
	"DilutedEPS" FLOAT, 
	"DilutedNIAvailtoComStockholders" FLOAT, 
	"DividendPaidCFO" FLOAT, 
	"DividendReceivedCFO" FLOAT, 
	"DividendsPayable" FLOAT, 
	"DividendsReceivedCFI" FLOAT, 
	"DuefromRelatedPartiesCurrent" FLOAT, 
	"DuefromRelatedPartiesNonCurrent" FLOAT, 
	"DuetoRelatedPartiesCurrent" FLOAT, 
	"DuetoRelatedPartiesNonCurrent" FLOAT, 
	"EBIT" FLOAT, 
	"EBITDA" FLOAT, 
	"EarningsFromEquityInterest" FLOAT, 
	"EarningsFromEquityInterestNetOfTax" FLOAT, 
	"EarningsLossesFromEquityInvestments" FLOAT, 
	"EffectOfExchangeRateChanges" FLOAT, 
	"EmployeeBenefits" FLOAT, 
	"EndCashPosition" FLOAT, 
	"EnterpriseValue" FLOAT, 
	"EnterprisesValueEBITDARatio" FLOAT, 
	"EnterprisesValueRevenueRatio" FLOAT, 
	"ExcessTaxBenefitFromStockBasedCompensation" FLOAT, 
	"ExciseTaxes" FLOAT, 
	"FinancialAssets" FLOAT, 
	"FinancialAssetsDesignatedasFairValueThroughProfitorLossTotal" FLOAT, 
	"FinancingCashFlow" FLOAT, 
	"FinishedGoods" FLOAT, 
	"FixedAssetsRevaluationReserve" FLOAT, 
	"ForeignCurrencyTranslationAdjustments" FLOAT, 
	"FreeCashFlow" FLOAT, 
	"GainLossOnInvestmentSecurities" FLOAT, 
	"GainLossOnSaleOfBusiness" FLOAT, 
	"GainLossOnSaleOfPPE" FLOAT, 
	"GainOnSaleOfBusiness" FLOAT, 
	"GainOnSaleOfPPE" FLOAT, 
	"GainOnSaleOfSecurity" FLOAT, 
	"GainsLossesNotAffectingRetainedEarnings" FLOAT, 
	"GeneralAndAdministrativeExpense" FLOAT, 
	"GeneralPartnershipCapital" FLOAT, 
	"Goodwill" FLOAT, 
	"GoodwillAndOtherIntangibleAssets" FLOAT, 
	"GrossAccountsReceivable" FLOAT, 
	"GrossPPE" FLOAT, 
	"GrossProfit" FLOAT, 
	"HedgingAssetsCurrent" FLOAT, 
	"HeldToMaturitySecurities" FLOAT, 
	"ImpairmentOfCapitalAssets" FLOAT, 
	"IncomeTaxPaidSupplementalData" FLOAT, 
	"IncomeTaxPayable" FLOAT, 
	"InsuranceAndClaims" FLOAT, 
	"InterestExpense" FLOAT, 
	"InterestExpenseNonOperating" FLOAT, 
	"InterestIncome" FLOAT, 
	"InterestIncomeNonOperating" FLOAT, 
	"InterestPaidCFF" FLOAT, 
	"InterestPaidCFO" FLOAT, 
	"InterestPaidSupplementalData" FLOAT, 
	"InterestPayable" FLOAT, 
	"InterestReceivedCFI" FLOAT, 
	"InterestReceivedCFO" FLOAT, 
	"InventoriesAdjustmentsAllowances" FLOAT, 
	"Inventory" FLOAT, 
	"InvestedCapital" FLOAT, 
	"InvestingCashFlow" FLOAT, 
	"InvestmentProperties" FLOAT, 
	"InvestmentinFinancialAssets" FLOAT, 
	"InvestmentsAndAdvances" FLOAT, 
	"InvestmentsInOtherVenturesUnderEquityMethod" FLOAT, 
	"InvestmentsinAssociatesatCost" FLOAT, 
	"InvestmentsinJointVenturesatCost" FLOAT, 
	"InvestmentsinSubsidiariesatCost" FLOAT, 
	"IssuanceOfCapitalStock" FLOAT, 
	"IssuanceOfDebt" FLOAT, 
	"LandAndImprovements" FLOAT, 
	"Leases" FLOAT, 
	"LiabilitiesHeldforSaleNonCurrent" FLOAT, 
	"LimitedPartnershipCapital" FLOAT, 
	"LineOfCredit" FLOAT, 
	"LoansReceivable" FLOAT, 
	"LongTermCapitalLeaseObligation" FLOAT, 
	"LongTermDebt" FLOAT, 
	"LongTermDebtAndCapitalLeaseObligation" FLOAT, 
	"LongTermDebtIssuance" FLOAT, 
	"LongTermDebtPayments" FLOAT, 
	"LongTermEquityInvestment" FLOAT, 
	"LongTermProvisions" FLOAT, 
	"MachineryFurnitureEquipment" FLOAT, 
	"MarketCap" FLOAT, 
	"MinimumPensionLiabilities" FLOAT, 
	"MinorityInterest" FLOAT, 
	"MinorityInterests" FLOAT, 
	"NetBusinessPurchaseAndSale" FLOAT, 
	"NetCommonStockIssuance" FLOAT, 
	"NetDebt" FLOAT, 
	"NetForeignCurrencyExchangeGainLoss" FLOAT, 
	"NetIncome" FLOAT, 
	"NetIncomeCommonStockholders" FLOAT, 
	"NetIncomeContinuousOperations" FLOAT, 
	"NetIncomeDiscontinuousOperations" FLOAT, 
	"NetIncomeExtraordinary" FLOAT, 
	"NetIncomeFromContinuingAndDiscontinuedOperation" FLOAT, 
	"NetIncomeFromContinuingOperationNetMinorityInterest" FLOAT, 
	"NetIncomeFromContinuingOperations" FLOAT, 
	"NetIncomeFromTaxLossCarryforward" FLOAT, 
	"NetIncomeIncludingNoncontrollingInterests" FLOAT, 
	"NetIntangiblesPurchaseAndSale" FLOAT, 
	"NetInterestIncome" FLOAT, 
	"NetInvestmentPropertiesPurchaseAndSale" FLOAT, 
	"NetInvestmentPurchaseAndSale" FLOAT, 
	"NetIssuancePaymentsOfDebt" FLOAT, 
	"NetLongTermDebtIssuance" FLOAT, 
	"NetNonOperatingInterestIncomeExpense" FLOAT, 
	"NetOtherFinancingCharges" FLOAT, 
	"NetOtherInvestingChanges" FLOAT, 
	"NetPPE" FLOAT, 
	"NetPPEPurchaseAndSale" FLOAT, 
	"NetPreferredStockIssuance" FLOAT, 
	"NetShortTermDebtIssuance" FLOAT, 
	"NetTangibleAssets" FLOAT, 
	"NonCurrentAccountsReceivable" FLOAT, 
	"NonCurrentAccruedExpenses" FLOAT, 
	"NonCurrentDeferredAssets" FLOAT, 
	"NonCurrentDeferredLiabilities" FLOAT, 
	"NonCurrentDeferredRevenue" FLOAT, 
	"NonCurrentDeferredTaxesAssets" FLOAT, 
	"NonCurrentDeferredTaxesLiabilities" FLOAT, 
	"NonCurrentNoteReceivables" FLOAT, 
	"NonCurrentPensionAndOtherPostretirementBenefitPlans" FLOAT, 
	"NonCurrentPrepaidAssets" FLOAT, 
	"NormalizedEBITDA" FLOAT, 
	"NormalizedIncome" FLOAT, 
	"NotesReceivable" FLOAT, 
	"OperatingCashFlow" FLOAT, 
	"OperatingExpense" FLOAT, 
	"OperatingGainsLosses" FLOAT, 
	"OperatingIncome" FLOAT, 
	"OperatingRevenue" FLOAT, 
	"OrdinarySharesNumber" FLOAT, 
	"OtherCashAdjustmentInsideChangeinCash" FLOAT, 
	"OtherCashAdjustmentOutsideChangeinCash" FLOAT, 
	"OtherCashPaymentsfromOperatingActivities" FLOAT, 
	"OtherCashReceiptsfromOperatingActivities" FLOAT, 
	"OtherCurrentAssets" FLOAT, 
	"OtherCurrentBorrowings" FLOAT, 
	"OtherCurrentLiabilities" FLOAT, 
	"OtherEquityAdjustments" FLOAT, 
	"OtherEquityInterest" FLOAT, 
	"OtherGandA" FLOAT, 
	"OtherIncomeExpense" FLOAT, 
	"OtherIntangibleAssets" FLOAT, 
	"OtherInventories" FLOAT, 
	"OtherInvestments" FLOAT, 
	"OtherNonCashItems" FLOAT, 
	"OtherNonCurrentAssets" FLOAT, 
	"OtherNonCurrentLiabilities" FLOAT, 
	"OtherNonOperatingIncomeExpenses" FLOAT, 
	"OtherOperatingExpenses" FLOAT, 
	"OtherPayable" FLOAT, 
	"OtherProperties" FLOAT, 
	"OtherReceivables" FLOAT, 
	"OtherShortTermInvestments" FLOAT, 
	"OtherSpecialCharges" FLOAT, 
	"OtherTaxes" FLOAT, 
	"OtherunderPreferredStockDividend" FLOAT, 
	"Payables" FLOAT, 
	"PayablesAndAccruedExpenses" FLOAT, 
	"PaymentsonBehalfofEmployees" FLOAT, 
	"PensionAndEmployeeBenefitExpense" FLOAT, 
	"PensionandOtherPostRetirementBenefitPlansCurrent" FLOAT, 
	"PreferredSecuritiesOutsideStockEquity" FLOAT, 
	"PreferredSharesNumber" FLOAT, 
	"PreferredStock" FLOAT, 
	"PreferredStockDividendPaid" FLOAT, 
	"PreferredStockDividends" FLOAT, 
	"PreferredStockEquity" FLOAT, 
	"PreferredStockIssuance" FLOAT, 
	"PreferredStockPayments" FLOAT, 
	"PrepaidAssets" FLOAT, 
	"PretaxIncome" FLOAT, 
	"ProceedsFromStockOptionExercised" FLOAT, 
	"Properties" FLOAT, 
	"ProvisionForDoubtfulAccounts" FLOAT, 
	"ProvisionandWriteOffofAssets" FLOAT, 
	"PurchaseOfBusiness" FLOAT, 
	"PurchaseOfIntangibles" FLOAT, 
	"PurchaseOfInvestment" FLOAT, 
	"PurchaseOfInvestmentProperties" FLOAT, 
	"PurchaseOfPPE" FLOAT, 
	"RawMaterials" FLOAT, 
	"Receivables" FLOAT, 
	"ReceivablesAdjustmentsAllowances" FLOAT, 
	"ReconciledCostOfRevenue" FLOAT, 
	"ReconciledDepreciation" FLOAT, 
	"RentAndLandingFees" FLOAT, 
	"RentExpenseSupplemental" FLOAT, 
	"RepaymentOfDebt" FLOAT, 
	"RepurchaseOfCapitalStock" FLOAT, 
	"ResearchAndDevelopment" FLOAT, 
	"RestrictedCash" FLOAT, 
	"RestructuringAndMergernAcquisition" FLOAT, 
	"RetainedEarnings" FLOAT, 
	"SalariesAndWages" FLOAT, 
	"SaleOfBusiness" FLOAT, 
	"SaleOfIntangibles" FLOAT, 
	"SaleOfInvestment" FLOAT, 
	"SaleOfInvestmentProperties" FLOAT, 
	"SaleOfPPE" FLOAT, 
	"SecuritiesAmortization" FLOAT, 
	"SellingAndMarketingExpense" FLOAT, 
	"SellingGeneralAndAdministration" FLOAT, 
	"ShareIssued" FLOAT, 
	"ShortTermDebtIssuance" FLOAT, 
	"ShortTermDebtPayments" FLOAT, 
	"SpecialIncomeCharges" FLOAT, 
	"StockBasedCompensation" FLOAT, 
	"StockholdersEquity" FLOAT, 
	"TangibleBookValue" FLOAT, 
	"TaxEffectOfUnusualItems" FLOAT, 
	"TaxProvision" FLOAT, 
	"TaxRateForCalcs" FLOAT, 
	"TaxesReceivable" FLOAT, 
	"TaxesRefundPaid" FLOAT, 
	"TotalAssets" FLOAT, 
	"TotalCapitalization" FLOAT, 
	"TotalDebt" FLOAT, 
	"TotalEquityGrossMinorityInterest" FLOAT, 
	"TotalExpenses" FLOAT, 
	"TotalLiabilitiesNetMinorityInterest" FLOAT, 
	"TotalNonCurrentAssets" FLOAT, 
	"TotalNonCurrentLiabilitiesNetMinorityInterest" FLOAT, 
	"TotalOperatingIncomeAsReported" FLOAT, 
	"TotalOtherFinanceCost" FLOAT, 
	"TotalPartnershipCapital" FLOAT, 
	"TotalRevenue" FLOAT, 
	"TotalTaxPayable" FLOAT, 
	"TotalUnusualItems" FLOAT, 
	"TotalUnusualItemsExcludingGoodwill" FLOAT, 
	"TradeandOtherPayablesNonCurrent" FLOAT, 
	"TradingSecurities" FLOAT, 
	"TreasurySharesNumber" FLOAT, 
	"TreasuryStock" FLOAT, 
	"UnrealizedGainLoss" FLOAT, 
	"UnrealizedGainLossOnInvestmentSecurities" FLOAT, 
	"WorkInProcess" FLOAT, 
	"WorkingCapital" FLOAT, 
	"WriteOff" FLOAT, 
	"InterestPaidDirect" FLOAT, 
	"InterestReceivedDirect" FLOAT, 
	"PaymentstoSuppliersforGoodsandServices" FLOAT, 
	"ReceiptsfromCustomers" FLOAT, 
	"RestrictedCommonStock" FLOAT, 
	"TaxesRefundPaidDirect" FLOAT, 
	"KeyStats_maxAge" FLOAT, 
	"KeyStats_priceHint" FLOAT, 
	"KeyStats_enterpriseValue" FLOAT, 
	"KeyStats_forwardPE" FLOAT, 
	"KeyStats_profitMargins" FLOAT, 
	"KeyStats_floatShares" FLOAT, 
	"KeyStats_sharesOutstanding" FLOAT, 
	"KeyStats_sharesShort" FLOAT, 
	"KeyStats_sharesShortPriorMonth" FLOAT, 
	"KeyStats_sharesShortPreviousMonthDate" TEXT, 
	"KeyStats_dateShortInterest" TEXT, 
	"KeyStats_sharesPercentSharesOut" FLOAT, 
	"KeyStats_heldPercentInsiders" FLOAT, 
	"KeyStats_heldPercentInstitutions" FLOAT, 
	"KeyStats_shortRatio" FLOAT, 
	"KeyStats_shortPercentOfFloat" FLOAT, 
	"KeyStats_beta" FLOAT, 
	"KeyStats_impliedSharesOutstanding" FLOAT, 
	"KeyStats_category" TEXT, 
	"KeyStats_bookValue" FLOAT, 
	"KeyStats_priceToBook" FLOAT, 
	"KeyStats_fundFamily" TEXT, 
	"KeyStats_legalType" TEXT, 
	"KeyStats_lastFiscalYearEnd" TEXT, 
	"KeyStats_nextFiscalYearEnd" TEXT, 
	"KeyStats_mostRecentQuarter" TEXT, 
	"KeyStats_earningsQuarterlyGrowth" FLOAT, 
	"KeyStats_netIncomeToCommon" FLOAT, 
	"KeyStats_trailingEps" FLOAT, 
	"KeyStats_forwardEps" FLOAT, 
	"KeyStats_lastSplitFactor" TEXT, 
	"KeyStats_lastSplitDate" TEXT, 
	"KeyStats_enterpriseToRevenue" FLOAT, 
	"KeyStats_enterpriseToEbitda" FLOAT, 
	"KeyStats_52WeekChange" FLOAT, 
	"KeyStats_SandP52WeekChange" FLOAT, 
	"KeyStats_lastDividendValue" FLOAT, 
	"KeyStats_lastDividendDate" FLOAT, 
	"KeyStats_latestShareClass" FLOAT, 
	"KeyStats_leadInvestor" FLOAT, 
	"Forward_EPS_Growth_Percent" FLOAT, 
	"Summary_maxAge" FLOAT, 
	"Summary_priceHint" FLOAT, 
	"Summary_previousClose" FLOAT, 
	"Summary_open" FLOAT, 
	"Summary_dayLow" FLOAT, 
	"Summary_dayHigh" FLOAT, 
	"Summary_regularMarketPreviousClose" FLOAT, 
	"Summary_regularMarketOpen" FLOAT, 
	"Summary_regularMarketDayLow" FLOAT, 
	"Summary_regularMarketDayHigh" FLOAT, 
	"Summary_dividendRate" FLOAT, 
	"Summary_dividendYield" FLOAT, 
	"Summary_exDividendDate" TEXT, 
	"Summary_payoutRatio" FLOAT, 
	"Summary_fiveYearAvgDividendYield" FLOAT, 
	"Summary_beta" FLOAT, 
	"Summary_trailingPE" FLOAT, 
	"Summary_forwardPE" FLOAT, 
	"Summary_volume" FLOAT, 
	"Summary_regularMarketVolume" FLOAT, 
	"Summary_averageVolume" FLOAT, 
	"Summary_averageVolume10days" FLOAT, 
	"Summary_averageDailyVolume10Day" FLOAT, 
	"Summary_bid" FLOAT, 
	"Summary_ask" FLOAT, 
	"Summary_bidSize" FLOAT, 
	"Summary_askSize" FLOAT, 
	"Summary_marketCap" FLOAT, 
	"Summary_fiftyTwoWeekLow" FLOAT, 
	"Summary_fiftyTwoWeekHigh" FLOAT, 
	"Summary_allTimeHigh" FLOAT, 
	"Summary_allTimeLow" FLOAT, 
	"Summary_priceToSalesTrailing12Months" FLOAT, 
	"Summary_fiftyDayAverage" FLOAT, 
	"Summary_twoHundredDayAverage" FLOAT, 
	"Summary_trailingAnnualDividendRate" FLOAT, 
	"Summary_trailingAnnualDividendYield" FLOAT, 
	"Summary_currency" TEXT, 
	"Summary_fromCurrency" FLOAT, 
	"Summary_toCurrency" FLOAT, 
	"Summary_lastMarket" FLOAT, 
	"Summary_coinMarketCapLink" FLOAT, 
	"Summary_algorithm" FLOAT, 
	"Summary_tradeable" TEXT, 
	"FinData_maxAge" FLOAT, 
	"FinData_currentPrice" FLOAT, 
	"FinData_targetHighPrice" FLOAT, 
	"FinData_targetLowPrice" FLOAT, 
	"FinData_targetMeanPrice" FLOAT, 
	"FinData_targetMedianPrice" FLOAT, 
	"FinData_recommendationMean" FLOAT, 
	"FinData_recommendationKey" TEXT, 
	"FinData_numberOfAnalystOpinions" FLOAT, 
	"FinData_totalCash" FLOAT, 
	"FinData_totalCashPerShare" FLOAT, 
	"FinData_ebitda" FLOAT, 
	"FinData_totalDebt" FLOAT, 
	"FinData_quickRatio" FLOAT, 
	"FinData_currentRatio" FLOAT, 
	"FinData_totalRevenue" FLOAT, 
	"FinData_debtToEquity" FLOAT, 
	"FinData_revenuePerShare" FLOAT, 
	"FinData_returnOnAssets" FLOAT, 
	"FinData_returnOnEquity" FLOAT, 
	"FinData_grossProfits" FLOAT, 
	"FinData_freeCashflow" FLOAT, 
	"FinData_operatingCashflow" FLOAT, 
	"FinData_earningsGrowth" FLOAT, 
	"FinData_revenueGrowth" FLOAT, 
	"FinData_grossMargins" FLOAT, 
	"FinData_ebitdaMargins" FLOAT, 
	"FinData_operatingMargins" FLOAT, 
	"FinData_profitMargins" FLOAT, 
	"FinData_financialCurrency" TEXT, 
	"KeyStats_ytdReturn" FLOAT, 
	"KeyStats_beta3Year" FLOAT, 
	"KeyStats_totalAssets" FLOAT, 
	"KeyStats_yield" FLOAT, 
	"KeyStats_fundInceptionDate" TEXT, 
	"KeyStats_threeYearAverageReturn" FLOAT, 
	"KeyStats_fiveYearAverageReturn" FLOAT, 
	"Summary_yield" FLOAT, 
	"Summary_totalAssets" FLOAT, 
	"Summary_navPrice" FLOAT
);
DROP TABLE IF EXISTS "OptionDataTradingView";
CREATE TABLE "OptionDataTradingView" (
	option_osi TEXT,
	symbol TEXT, 
	"option-type" TEXT,
	expiration_date BIGINT,
	strike FLOAT, 
	ask FLOAT, 
	bid FLOAT, 
	delta FLOAT, 
	gamma FLOAT, 
	iv FLOAT, 
	rho FLOAT, 
	"theoPrice" FLOAT, 
	theta FLOAT, 
	vega FLOAT, 
	option TEXT, 
	time TEXT, 
	exchange TEXT,
	PRIMARY KEY(option_osi)
);
DROP TABLE IF EXISTS "OptionDataYahoo";
CREATE TABLE "OptionDataYahoo" (
	"contractSymbol" TEXT,
	symbol TEXT,
	"option-type" TEXT, 
	expiration_date DATETIME, 
	strike FLOAT, 
	currency TEXT, 
	"lastPrice" FLOAT, 
	change FLOAT, 
	"percentChange" FLOAT, 
	option_open_interest BIGINT, 
	bid FLOAT, 
	ask FLOAT, 
	"contractSize" TEXT, 
	"lastTradeDate" DATETIME, 
	"impliedVolatility" FLOAT, 
	"inTheMoney" BOOLEAN, 
	option_volume FLOAT,
	PRIMARY KEY("contractSymbol")
);
DROP TABLE IF EXISTS "StockDataBarchart";
CREATE TABLE "StockDataBarchart" (
	symbol TEXT PRIMARY KEY,
	implied_volatility FLOAT, 
	historical_volatility FLOAT, 
	iv_percentile FLOAT, 
	iv_rank FLOAT, 
	iv_high FLOAT, 
	iv_low FLOAT, 
	put_call_vol_ratio FLOAT, 
	put_call_oi_ratio FLOAT, 
	todays_volume BIGINT, 
	volume_avg_30d BIGINT, 
	todays_open_interest BIGINT, 
	open_int_30d BIGINT
);
DROP TABLE IF EXISTS "StockPrice";
CREATE TABLE "StockPrice" (
	symbol TEXT PRIMARY KEY, 
	live_stock_price FLOAT, 
	price_source TEXT, 
	live_price_timestamp DATETIME
);
DROP TABLE IF EXISTS "TechnicalIndicators";
CREATE TABLE "TechnicalIndicators" (
	symbol TEXT PRIMARY KEY,
	"Recommend.Other" FLOAT, 
	"Recommend.All" FLOAT, 
	"Recommend.MA" FLOAT, 
	"RSI" FLOAT, 
	"RSI[1]" FLOAT, 
	"Stoch.K" FLOAT, 
	"Stoch.D" FLOAT, 
	"Stoch.K[1]" FLOAT, 
	"Stoch.D[1]" FLOAT, 
	"CCI20" FLOAT, 
	"CCI20[1]" FLOAT, 
	"ADX" FLOAT, 
	"ADX+DI" FLOAT, 
	"ADX-DI" FLOAT, 
	"ADX+DI[1]" FLOAT, 
	"ADX-DI[1]" FLOAT, 
	"AO" FLOAT, 
	"AO[1]" FLOAT, 
	"Mom" FLOAT, 
	"Mom[1]" FLOAT, 
	"MACD.macd" FLOAT, 
	"MACD.signal" FLOAT, 
	"Rec.Stoch.RSI" BIGINT, 
	"Stoch.RSI.K" FLOAT, 
	"Rec.WR" BIGINT, 
	"W.R" FLOAT, 
	"Rec.BBPower" BIGINT, 
	"BBPower" FLOAT, 
	"Rec.UO" BIGINT, 
	"UO" FLOAT, 
	close FLOAT, 
	"EMA5" FLOAT, 
	"SMA5" FLOAT, 
	"EMA10" FLOAT, 
	"SMA10" FLOAT, 
	"EMA20" FLOAT, 
	"SMA20" FLOAT, 
	"EMA30" FLOAT, 
	"SMA30" FLOAT, 
	"EMA50" FLOAT, 
	"SMA50" FLOAT, 
	"EMA100" FLOAT, 
	"SMA100" FLOAT, 
	"EMA200" FLOAT, 
	"SMA200" FLOAT, 
	"Rec.Ichimoku" BIGINT, 
	"Ichimoku.BLine" FLOAT, 
	"Rec.VWMA" BIGINT, 
	"VWMA" FLOAT, 
	"Rec.HullMA9" BIGINT, 
	"HullMA9" FLOAT, 
	"Pivot.M.Classic.S3" FLOAT, 
	"Pivot.M.Classic.S2" FLOAT, 
	"Pivot.M.Classic.S1" FLOAT, 
	"Pivot.M.Classic.Middle" FLOAT, 
	"Pivot.M.Classic.R1" FLOAT, 
	"Pivot.M.Classic.R2" FLOAT, 
	"Pivot.M.Classic.R3" FLOAT, 
	"Pivot.M.Fibonacci.S3" FLOAT, 
	"Pivot.M.Fibonacci.S2" FLOAT, 
	"Pivot.M.Fibonacci.S1" FLOAT, 
	"Pivot.M.Fibonacci.Middle" FLOAT, 
	"Pivot.M.Fibonacci.R1" FLOAT, 
	"Pivot.M.Fibonacci.R2" FLOAT, 
	"Pivot.M.Fibonacci.R3" FLOAT, 
	"Pivot.M.Camarilla.S3" FLOAT, 
	"Pivot.M.Camarilla.S2" FLOAT, 
	"Pivot.M.Camarilla.S1" FLOAT, 
	"Pivot.M.Camarilla.Middle" FLOAT, 
	"Pivot.M.Camarilla.R1" FLOAT, 
	"Pivot.M.Camarilla.R2" FLOAT, 
	"Pivot.M.Camarilla.R3" FLOAT, 
	"Pivot.M.Woodie.S3" FLOAT, 
	"Pivot.M.Woodie.S2" FLOAT, 
	"Pivot.M.Woodie.S1" FLOAT, 
	"Pivot.M.Woodie.Middle" FLOAT, 
	"Pivot.M.Woodie.R1" FLOAT, 
	"Pivot.M.Woodie.R2" FLOAT, 
	"Pivot.M.Woodie.R3" FLOAT, 
	"Pivot.M.Demark.S1" FLOAT, 
	"Pivot.M.Demark.Middle" FLOAT, 
	"Pivot.M.Demark.R1" FLOAT, 
	open FLOAT, 
	"P.SAR" FLOAT, 
	"BB.lower" FLOAT, 
	"BB.upper" FLOAT, 
	"AO[2]" FLOAT, 
	volume BIGINT, 
	change FLOAT, 
	low FLOAT, 
	high FLOAT, 
	recommendation TEXT, 
	recommendation_buy_amount BIGINT, 
	recommendation_neutral_amount BIGINT, 
	recommendation_sell_amount BIGINT
);
DROP TABLE IF EXISTS "AnalystPriceTargets";
CREATE TABLE "AnalystPriceTargets" (
	symbol TEXT PRIMARY KEY, 
	analyst_mean_target FLOAT
);
INSERT INTO "DataAgingFieldClassification"
(table_name, field_name, tier, tier_entry_date) 
VALUES
('OptionDataTradingView', 'strike', 'Master', DATE('now')),
('OptionDataTradingView', 'expiration_date', 'Master', DATE('now')),
('OptionDataTradingView', 'option-type', 'Master',, DATE('now')),
('OptionDataTradingView', 'exchange', 'Master', DATE('now')),
('OptionDataTradingView', 'symbol', 'Master', DATE('now'))
ON CONFLICT(table_name, field_name) DO UPDATE SET
    tier = excluded.tier,
    tier_entry_date = excluded.tier_entry_date;

INSERT INTO "DataAgingFieldClassification"
(table_name, field_name, tier, tier_entry_date) 
VALUES
-- Kategorie: Master (Ändern sich nie)
('OptionDataTradingView', 'option_osi', 'Master', DATE('now')),
('OptionDataTradingView', 'symbol', 'Master', DATE('now')),
('OptionDataTradingView', 'option-type', 'Master', DATE('now')),
('OptionDataTradingView', 'expiration_date', 'Master', DATE('now')),
('OptionDataTradingView', 'strike', 'Master', DATE('now')),
('OptionDataTradingView', 'option', 'Master', DATE('now')),
('OptionDataTradingView', 'exchange', 'Master', DATE('now')),

-- Kategorie: Market (Ändern sich daily/realtime)
('OptionDataTradingView', 'ask', 'Daily', DATE('now')),
('OptionDataTradingView', 'bid', 'Daily', DATE('now')),
('OptionDataTradingView', 'iv', 'Daily', DATE('now')),
('OptionDataTradingView', 'theoPrice', 'Daily', DATE('now')),
('OptionDataTradingView', 'time', 'Daily', DATE('now')),

-- Kategorie: Greeks (Ändern sich daily/realtime)
('OptionDataTradingView', 'delta', 'Daily', DATE('now')),
('OptionDataTradingView', 'gamma', 'Daily', DATE('now')),
('OptionDataTradingView', 'rho', 'Daily', DATE('now')),
('OptionDataTradingView', 'theta', 'Daily', DATE('now')),
('OptionDataTradingView', 'vega', 'Daily', DATE('now'))

ON CONFLICT(table_name, field_name) DO UPDATE SET
    tier = excluded.tier,
    tier_entry_date = excluded.tier_entry_date;

INSERT INTO "DataAgingFieldClassification"
(table_name, field_name, tier, tier_entry_date) 
VALUES
-- Kategorie: Master (Statische Kontraktinformationen)
('OptionDataYahoo', 'contractSymbol', 'Master', DATE('now')),
('OptionDataYahoo', 'symbol', 'Master', DATE('now')),
('OptionDataYahoo', 'option-type', 'Master', DATE('now')),
('OptionDataYahoo', 'expiration_date', 'Master', DATE('now')),
('OptionDataYahoo', 'strike', 'Master', DATE('now')),
('OptionDataYahoo', 'currency', 'Master', DATE('now')),
('OptionDataYahoo', 'contractSize', 'Master', DATE('now')),

-- Kategorie: Market (Preisrelevante Daten)
('OptionDataYahoo', 'lastPrice', 'Daily', DATE('now')),
('OptionDataYahoo', 'bid', 'Daily', DATE('now')),
('OptionDataYahoo', 'ask', 'Daily', DATE('now')),
('OptionDataYahoo', 'change', 'Daily', DATE('now')),
('OptionDataYahoo', 'percentChange', 'Daily', DATE('now')),
('OptionDataYahoo', 'impliedVolatility', 'Daily', DATE('now')),
('OptionDataYahoo', 'lastTradeDate', 'Daily', DATE('now')),
('OptionDataYahoo', 'inTheMoney', 'Daily', DATE('now')),

-- Kategorie: Volume (Handelsaktivität)
('OptionDataYahoo', 'option_open_interest', 'Daily', DATE('now')),
('OptionDataYahoo', 'option_volume', 'Daily', DATE('now'))

ON CONFLICT(table_name, field_name) DO UPDATE SET
    tier = excluded.tier,
    tier_entry_date = excluded.tier_entry_date;