-- create views
-- db/SQL/views/create_view/*
DROP VIEW IF EXISTS FundamentalData;
CREATE VIEW FundamentalData AS
SELECT 
	a."Symbol", 
	a."Company", 
	a."FV", 
	a."Sector", 
	a."No-Years", 
	a."Price", 
	a."Div-Yield", 
	a."5Y-Avg-Yield", 
	a."Current-Div", 
	a."Payouts/-Year", 
	a."Annualized", 
	a."Previous-Div", 
	a."Ex-Date", 
	a."Pay-Date", 
	a."Low", 
	a."High", 
	a."DGR-1Y", 
	a."DGR-3Y", 
	a."DGR-5Y", 
	a."DGR-10Y", 
	a."TTR-1Y", 
	a."TTR-3Y", 
	a."Fair-Value", 
	a."FV-%", 
	a."Streak-Basis", 
	a."Chowder-Number", 
	a."EPS-1Y", 
	a."Revenue-1Y", 
	a."NPM", 
	a."CF/Share", 
	a."ROE", 
	a."Current-R", 
	a."Debt/Capital", 
	a."ROTC", 
	a."P/E", 
	a."P/BV", 
	a."PEG", 
	a."New-Member", 
	a."Industry", 
	a."Classification",

    b."EnterpriseValue", 
	b."ForwardPE", 
	b."TrailingEps", 
	b."PriceToBook", 
	b."TotalRevenue", 
	b."EBITDA", 
	b."FreeCashFlow", 
	b."TotalDebt", 
	b."NetIncome", 
	b."ROE", 
	b."ROA", 
	b."CurrentPrice", 
	b."MarketCap", 
	b."Volume", 
	b."AverageVolume", 
	b."Yahoo_DividendYield", 
	b."DividendRate", 
	b."TrailingAnnualDividendRate", 
	b."PayoutRatio", 
	b."ExDividendDate", 
	b."PE_Ratio_Calc", 
	b."PS_Ratio", 
	b."DebtToMarketCap", 
	b."EV_EBITDA_Approx"
FROM 
    FundamentalDataDividendRadar AS a
JOIN 
    FundamentalDataYahooProcessed as b
ON a."Symbol" = b.symbol;


DROP VIEW IF EXISTS OptionData;
CREATE VIEW OptionData AS
SELECT 
	a.symbol, 
	a."option-type", 
	a.strike, 
	a.expiration_date, 
    a.ask, 
	a.bid, 
	a.delta, 
	a.gamma, 
	a.iv, 
	a.rho, 
    a."theoPrice", 
	a.theta, 
	a.vega, 
	a.option, 
	a.time, 
	a.exchange, 
	a.option_osi,
    b."contractSymbol",  
	b.currency, 
	b."lastPrice", 
	b.change, 
	b."percentChange", 
	b.option_open_interest, 
	b."contractSize", 
	b."lastTradeDate", 
	b."impliedVolatility", 
	b."inTheMoney", 
	b.option_volume
FROM 
    OptionDataTradingView AS a
JOIN 
    OptionDataYahoo as b
ON a.option_osi = b.contractSymbol;

DROP VIEW IF EXISTS StockData;

CREATE VIEW StockData AS
SELECT 
 a.symbol,
 a.analyst_mean_target,
 b.earnings_date
FROM 
 AnalystPriceTargets AS a
JOIN 
 EarningDates AS b
ON 
 a.symbol = b.symbol;


DROP VIEW IF EXISTS OptionDataMerged;
CREATE VIEW OptionDataMerged AS
SELECT 
	-- Option Data
    a.symbol, 
	a."option-type", 
	a.strike, 
	a.expiration_date, 
    a.ask, 
	a.bid, 
	a.delta, 
	a.gamma, 
	a.iv, 
	a.rho, 
    a."theoPrice", 
	a.theta, 
	a.vega, 
	a.option, 
	a.time, 
	a.exchange, 
	a.option_osi,
    a."contractSymbol",  
	a.currency, 
	a."lastPrice", 
	a.change, 
	a."percentChange", 
	a.option_open_interest, 
	a."contractSize", 
	a."lastTradeDate", 
	a."impliedVolatility", 
	a."inTheMoney", 
	a.option_volume,

    -- Fundamental Data
    b."Symbol", 
	b."Company", 
	b."FV", 
	b."Sector", 
	b."No-Years", 
	b."Price", 
	b."Div-Yield", 
	b."5Y-Avg-Yield", 
	b."Current-Div", 
	b."Payouts/-Year", 
	b."Annualized", 
	b."Previous-Div", 
	b."Ex-Date", 
	b."Pay-Date", 
	b."Low", 
	b."High", 
	b."DGR-1Y", 
	b."DGR-3Y", 
	b."DGR-5Y", 
	b."DGR-10Y", 
	b."TTR-1Y", 
	b."TTR-3Y", 
	b."Fair-Value", 
	b."FV-%", 
	b."Streak-Basis", 
	b."Chowder-Number", 
	b."EPS-1Y", 
	b."Revenue-1Y", 
	b."NPM", 
	b."CF/Share", 
	b."ROE", 
	b."Current-R", 
	b."Debt/Capital", 
	b."ROTC", 
	b."P/E", 
	b."P/BV", 
	b."PEG", 
	b."New-Member", 
	b."Industry", 
	b."Classification",
    b."EnterpriseValue", 
	b."ForwardPE", 
	b."TrailingEps", 
	b."PriceToBook", 
	b."TotalRevenue", 
	b."EBITDA", 
	b."FreeCashFlow", 
	b."TotalDebt", 
	b."NetIncome", 
	b."ROE", 
	b."ROA", 
	b."CurrentPrice", 
	b."MarketCap", 
	b."Volume", 
	b."AverageVolume", 
	b."Yahoo_DividendYield", 
	b."DividendRate", 
	b."TrailingAnnualDividendRate", 
	b."PayoutRatio", 
	b."ExDividendDate", 
	b."PE_Ratio_Calc", 
	b."PS_Ratio", 
	b."DebtToMarketCap", 
	b."EV_EBITDA_Approx",

    -- Stock Data
    c.analyst_mean_target,
    c.earnings_date,

    -- Technical Indicators
    d."Recommend.Other", 
	d."Recommend.All", 
	d."Recommend.MA", 
	d."RSI", 
	d."RSI[1]", 
	d."Stoch.K", 
	d."Stoch.D", 
	d."Stoch.K[1]", 
	d."Stoch.D[1]", 
	d."CCI20", 
	d."CCI20[1]", 
	d."ADX", 
	d."ADX+DI", 
	d."ADX-DI", 
	d."ADX+DI[1]", 
	d."ADX-DI[1]", 
	d."AO", 
	d."AO[1]", 
	d."Mom", 
	d."Mom[1]", 
	d."MACD.macd", 
	d."MACD.signal", 
	d."Rec.Stoch.RSI", 
	d."Stoch.RSI.K", 
	d."Rec.WR", 
	d."W.R", 
	d."Rec.BBPower", 
	d."BBPower", 
	d."Rec.UO", 
	d."UO", 
	d.close, 
	d."EMA5", 
	d."SMA5", 
	d."EMA10", 
	d."SMA10", 
	d."EMA20", 
	d."SMA20", 
	d."EMA30", 
	d."SMA30", 
	d."EMA50", 
	d."SMA50", 
	d."EMA100", 
	d."SMA100", 
	d."EMA200", 
	d."SMA200", 
	d."Rec.Ichimoku", 
	d."Ichimoku.BLine", 
	d."Rec.VWMA", 
	d."VWMA", 
	d."Rec.HullMA9", 
	d."HullMA9", 
	d."Pivot.M.Classic.S3", 
	d."Pivot.M.Classic.S2", 
	d."Pivot.M.Classic.S1", 
	d."Pivot.M.Classic.Middle", 
	d."Pivot.M.Classic.R1", 
	d."Pivot.M.Classic.R2", 
	d."Pivot.M.Classic.R3", 
	d."Pivot.M.Fibonacci.S3", 
	d."Pivot.M.Fibonacci.S2", 
	d."Pivot.M.Fibonacci.S1", 
	d."Pivot.M.Fibonacci.Middle", 
	d."Pivot.M.Fibonacci.R1", 
	d."Pivot.M.Fibonacci.R2", 
	d."Pivot.M.Fibonacci.R3", 
	d."Pivot.M.Camarilla.S3", 
	d."Pivot.M.Camarilla.S2", 
	d."Pivot.M.Camarilla.S1", 
	d."Pivot.M.Camarilla.Middle", 
	d."Pivot.M.Camarilla.R1", 
	d."Pivot.M.Camarilla.R2", 
	d."Pivot.M.Camarilla.R3", 
	d."Pivot.M.Woodie.S3", 
	d."Pivot.M.Woodie.S2", 
	d."Pivot.M.Woodie.S1", 
	d."Pivot.M.Woodie.Middle", 
	d."Pivot.M.Woodie.R1", 
	d."Pivot.M.Woodie.R2", 
	d."Pivot.M.Woodie.R3", 
	d."Pivot.M.Demark.S1", 
	d."Pivot.M.Demark.Middle", 
	d."Pivot.M.Demark.R1", 
	d.open, 
	d."P.SAR", 
	d."BB.lower", 
	d."BB.upper", 
	d."AO[2]", 
	d.volume, 
	d.change, 
	d.low, 
	d.high, 
	d.recommendation, 
	d.recommendation_buy_amount, 
	d.recommendation_neutral_amount, 
	d.recommendation_sell_amount
FROM 
    OptionData AS a
JOIN 
    FundamentalData as b
ON a.symbol = a.symbol
JOIN 
    StockData as c
ON a.symbol = c.symbol
JOIN 
    TechnicalIndicators as d
ON a.symbol = d.symbol;

