CREATE TABLE IF NOT EXISTS "StockDayPricesYahoo" (
	SYMBOL TEXT,
	OPEN DOUBLE PRECISION,
	HIGH DOUBLE PRECISION,
	LOW DOUBLE PRECISION,
	CLOSE DOUBLE PRECISION,
	VOLUME BIGINT,
	ADJCLOSE DOUBLE PRECISION,
	DIVIDENDS REAL,
	SPLITS DOUBLE PRECISION,
	PRIMARY KEY (SYMBOL)
);
CREATE TABLE IF NOT EXISTS "StockDayPricesYahooHistoryDaily" (
	SNAPSHOT_DATE DATE,
	SYMBOL TEXT,
	OPEN DOUBLE PRECISION,
	HIGH DOUBLE PRECISION,
	LOW DOUBLE PRECISION,
	CLOSE DOUBLE PRECISION,
	VOLUME BIGINT,
	ADJCLOSE DOUBLE PRECISION,
	DIVIDENDS REAL,
	SPLITS DOUBLE PRECISION,
	PRIMARY KEY (SNAPSHOT_DATE, SYMBOL)
);