DROP TABLE IF EXISTS "StockDayPricesYahooHistoryDaily" ;
DROP TABLE IF EXISTS "StockDayPricesYahooHistoryDaily";
CREATE TABLE IF NOT EXISTS "StockPricesYahooHistoryDaily" (
	SNAPSHOT_DATE DATE,
    SYMBOL TEXT,
	OPEN DOUBLE PRECISION,
	HIGH DOUBLE PRECISION,
	LOW DOUBLE PRECISION,
	CLOSE DOUBLE PRECISION,
	VOLUME BIGINT,
	ADJCLOSE DOUBLE PRECISION,
	DIVIDENDS REAL,
	SPLITS DOUBLE PRECISION,
	PRIMARY KEY (SNAPSHOT_DATE,SYMBOL)
);
CREATE TABLE IF NOT EXISTS "StockPricesYahoo" (
    SYMBOL TEXT,
	OPEN DOUBLE PRECISION,
	HIGH DOUBLE PRECISION,
	LOW DOUBLE PRECISION,
	CLOSE DOUBLE PRECISION,
	VOLUME BIGINT,
	ADJCLOSE DOUBLE PRECISION,
	DIVIDENDS REAL,
	SPLITS DOUBLE PRECISION,
	PRIMARY KEY (SYMBOL)
);