DROP TABLE IF EXISTS "TechnicalIndicators";
DROP TABLE IF EXISTS "TechnicalIndicatorsCalculated";
CREATE TABLE "TechnicalIndicatorsCalculated" (
	symbol TEXT PRIMARY KEY,
    "EMA_5" REAL,
    "EMA_10" REAL,
    "EMA_20" REAL,
    "EMA_30" REAL,
    "EMA_50" REAL,
    "EMA_100" REAL,
    "EMA_200" REAL,
    "SMA_5" REAL,
    "SMA_10" REAL,
    "SMA_20" REAL,
    "SMA_30" REAL,
    "SMA_50" REAL,
    "SMA_100" REAL,
    "SMA_200" REAL,
    "MACD_12_26_9" REAL,
    "MACDh_12_26_9" REAL,
    "MACDs_12_26_9" REAL,
    "BBL_20_2.0_2.0" REAL,
    "BBM_20_2.0_2.0" REAL,
    "BBU_20_2.0_2.0" REAL,
    "BBB_20_2.0_2.0" REAL,
    "BBP_20_2.0_2.0" REAL,
    "ATRr_14" REAL,
    "ADX_10" REAL,
    "ADXR_10_2" REAL,
    "DMP_10" REAL,
    "DMN_10" REAL,
    "STOCHk_14_3_1" REAL,
    "STOCHd_14_3_1" REAL,
    "STOCHh_14_3_1" REAL,
    "RSI_14" REAL,
    "RSL" REAL
);
CREATE TABLE "TechnicalIndicatorsCalculatedHistoryDaily" (
	snapshot_date Date,
    symbol TEXT,
    "EMA_5" REAL,
    "EMA_10" REAL,
    "EMA_20" REAL,
    "EMA_30" REAL,
    "EMA_50" REAL,
    "EMA_100" REAL,
    "EMA_200" REAL,
    "SMA_5" REAL,
    "SMA_10" REAL,
    "SMA_20" REAL,
    "SMA_30" REAL,
    "SMA_50" REAL,
    "SMA_100" REAL,
    "SMA_200" REAL,
    "MACD_12_26_9" REAL,
    "MACDh_12_26_9" REAL,
    "MACDs_12_26_9" REAL,
    "BBL_20_2.0_2.0" REAL,
    "BBM_20_2.0_2.0" REAL,
    "BBU_20_2.0_2.0" REAL,
    "BBB_20_2.0_2.0" REAL,
    "BBP_20_2.0_2.0" REAL,
    "ATRr_14" REAL,
    "ADX_10" REAL,
    "ADXR_10_2" REAL,
    "DMP_10" REAL,
    "DMN_10" REAL,
    "STOCHk_14_3_1" REAL,
    "STOCHd_14_3_1" REAL,
    "STOCHh_14_3_1" REAL,
    "RSI_14" REAL,
    "RSL" REAL,
    PRIMARY KEY (snapshot_date, symbol)
);
INSERT INTO "DataAgingFieldClassification"
(table_name, field_name, tier, tier_entry_date) 
VALUES
-- Kategorie: Master (Statische Kontraktinformationen)
('TechnicalIndicatorsCalculated', 'EMA_5', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'EMA_10', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'EMA_20', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'EMA_30', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'EMA_50', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'EMA_100', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'EMA_200', 'Daily', DATE('now')),

('TechnicalIndicatorsCalculated', 'SMA_5', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'SMA_10', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'SMA_20', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'SMA_30', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'SMA_50', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'SMA_100', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'SMA_200', 'Daily', DATE('now')),

('TechnicalIndicatorsCalculated', 'MACD_12_26_9', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'MACDh_12_26_9', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'MACDs_12_26_9', 'Daily', DATE('now')),

('TechnicalIndicatorsCalculated', 'BBL_20_2.0_2.0', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'BM_20_2.0_2.0', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'BBU_20_2.0_2.0', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'BBB_20_2.0_2.0', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'BBP_20_2.0_2.0', 'Daily', DATE('now')),

('TechnicalIndicatorsCalculated', 'ATRr_14', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'ADX_10', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'ADXR_10_2', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'DMP_10', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'DMN_10', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'STOCHk_14_3_1', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'STOCHd_14_3_1', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'STOCHh_14_3_1', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'RSI_14', 'Daily', DATE('now')),
('TechnicalIndicatorsCalculated', 'RSL', 'Daily', DATE('now'))
ON CONFLICT(table_name, field_name) DO UPDATE SET
    tier = excluded.tier,
    tier_entry_date = excluded.tier_entry_date;