DROP TABLE IF EXISTS "FundamentalDataYahoo";
CREATE TABLE "FundamentalDataYahoo" (
	symbol TEXT, 
	"asOfDate" DATETIME, 
	"periodType" TEXT, 
	"currencyCode" TEXT, 
	"AccountsPayable" FLOAT, 
	"AccountsReceivable" FLOAT, 
	"AccumulatedDepreciation" FLOAT, 
	"AvailableForSaleSecurities" FLOAT, 
	"BasicAverageShares" FLOAT, 
	"BasicEPS" FLOAT, 
	"BeginningCashPosition" FLOAT, 
	"CapitalExpenditure" FLOAT, 
	"CapitalLeaseObligations" FLOAT, 
	"CapitalStock" FLOAT, 
	"CashAndCashEquivalents" FLOAT, 
	"CashCashEquivalentsAndShortTermInvestments" FLOAT, 
	"CashDividendsPaid" FLOAT, 
	"CashEquivalents" FLOAT, 
	"CashFinancial" FLOAT, 
	"CashFlowFromContinuingFinancingActivities" FLOAT, 
	"CashFlowFromContinuingInvestingActivities" FLOAT, 
	"CashFlowFromContinuingOperatingActivities" FLOAT, 
	"ChangeInAccountPayable" FLOAT, 
	"ChangeInCashSupplementalAsReported" FLOAT, 
	"ChangeInInventory" FLOAT, 
	"ChangeInOtherCurrentAssets" FLOAT, 
	"ChangeInOtherCurrentLiabilities" FLOAT, 
	"ChangeInOtherWorkingCapital" FLOAT, 
	"ChangeInPayable" FLOAT, 
	"ChangeInPayablesAndAccruedExpense" FLOAT, 
	"ChangeInReceivables" FLOAT, 
	"ChangeInWorkingCapital" FLOAT, 
	"ChangesInAccountReceivables" FLOAT, 
	"ChangesInCash" FLOAT, 
	"CommercialPaper" FLOAT, 
	"CommonStock" FLOAT, 
	"CommonStockDividendPaid" FLOAT, 
	"CommonStockEquity" FLOAT, 
	"CommonStockIssuance" FLOAT, 
	"CommonStockPayments" FLOAT, 
	"CostOfRevenue" FLOAT, 
	"CurrentAssets" FLOAT, 
	"CurrentCapitalLeaseObligation" FLOAT, 
	"CurrentDebt" FLOAT, 
	"CurrentDebtAndCapitalLeaseObligation" FLOAT, 
	"CurrentDeferredLiabilities" FLOAT, 
	"CurrentDeferredRevenue" FLOAT, 
	"CurrentLiabilities" FLOAT, 
	"DeferredIncomeTax" FLOAT, 
	"DeferredTax" FLOAT, 
	"DepreciationAmortizationDepletion" FLOAT, 
	"DepreciationAndAmortization" FLOAT, 
	"DilutedAverageShares" FLOAT, 
	"DilutedEPS" FLOAT, 
	"DilutedNIAvailtoComStockholders" FLOAT, 
	"EBIT" FLOAT, 
	"EBITDA" FLOAT, 
	"EndCashPosition" FLOAT, 
	"EnterpriseValue" FLOAT, 
	"EnterprisesValueEBITDARatio" FLOAT, 
	"EnterprisesValueRevenueRatio" FLOAT, 
	"FinancingCashFlow" FLOAT, 
	"FreeCashFlow" FLOAT, 
	"GainsLossesNotAffectingRetainedEarnings" FLOAT, 
	"GrossPPE" FLOAT, 
	"GrossProfit" FLOAT, 
	"IncomeTaxPaidSupplementalData" FLOAT, 
	"IncomeTaxPayable" FLOAT, 
	"InterestExpense" FLOAT, 
	"InterestExpenseNonOperating" FLOAT, 
	"InterestIncome" FLOAT, 
	"InterestIncomeNonOperating" FLOAT, 
	"InterestPaidSupplementalData" FLOAT, 
	"Inventory" FLOAT, 
	"InvestedCapital" FLOAT, 
	"InvestingCashFlow" FLOAT, 
	"InvestmentinFinancialAssets" FLOAT, 
	"InvestmentsAndAdvances" FLOAT, 
	"IssuanceOfCapitalStock" FLOAT, 
	"IssuanceOfDebt" FLOAT, 
	"LandAndImprovements" FLOAT, 
	"Leases" FLOAT, 
	"LongTermCapitalLeaseObligation" FLOAT, 
	"LongTermDebt" FLOAT, 
	"LongTermDebtAndCapitalLeaseObligation" FLOAT, 
	"LongTermDebtIssuance" FLOAT, 
	"LongTermDebtPayments" FLOAT, 
	"MachineryFurnitureEquipment" FLOAT, 
	"MarketCap" FLOAT, 
	"NetBusinessPurchaseAndSale" FLOAT, 
	"NetCommonStockIssuance" FLOAT, 
	"NetDebt" FLOAT, 
	"NetIncome" FLOAT, 
	"NetIncomeCommonStockholders" FLOAT, 
	"NetIncomeContinuousOperations" FLOAT, 
	"NetIncomeFromContinuingAndDiscontinuedOperation" FLOAT, 
	"NetIncomeFromContinuingOperationNetMinorityInterest" FLOAT, 
	"NetIncomeFromContinuingOperations" FLOAT, 
	"NetIncomeIncludingNoncontrollingInterests" FLOAT, 
	"NetInterestIncome" FLOAT, 
	"NetInvestmentPurchaseAndSale" FLOAT, 
	"NetIssuancePaymentsOfDebt" FLOAT, 
	"NetLongTermDebtIssuance" FLOAT, 
	"NetNonOperatingInterestIncomeExpense" FLOAT, 
	"NetOtherFinancingCharges" FLOAT, 
	"NetOtherInvestingChanges" FLOAT, 
	"NetPPE" FLOAT, 
	"NetPPEPurchaseAndSale" FLOAT, 
	"NetShortTermDebtIssuance" FLOAT, 
	"NetTangibleAssets" FLOAT, 
	"NonCurrentDeferredAssets" FLOAT, 
	"NonCurrentDeferredTaxesAssets" FLOAT, 
	"NormalizedEBITDA" FLOAT, 
	"NormalizedIncome" FLOAT, 
	"OperatingCashFlow" FLOAT, 
	"OperatingExpense" FLOAT, 
	"OperatingIncome" FLOAT, 
	"OperatingRevenue" FLOAT, 
	"OrdinarySharesNumber" FLOAT, 
	"OtherCurrentAssets" FLOAT, 
	"OtherCurrentBorrowings" FLOAT, 
	"OtherCurrentLiabilities" FLOAT, 
	"OtherEquityAdjustments" FLOAT, 
	"OtherIncomeExpense" FLOAT, 
	"OtherInvestments" FLOAT, 
	"OtherNonCashItems" FLOAT, 
	"OtherNonCurrentAssets" FLOAT, 
	"OtherNonCurrentLiabilities" FLOAT, 
	"OtherNonOperatingIncomeExpenses" FLOAT, 
	"OtherProperties" FLOAT, 
	"OtherReceivables" FLOAT, 
	"OtherShortTermInvestments" FLOAT, 
	"Payables" FLOAT, 
	"PayablesAndAccruedExpenses" FLOAT, 
	"PretaxIncome" FLOAT, 
	"Properties" FLOAT, 
	"PurchaseOfBusiness" FLOAT, 
	"PurchaseOfInvestment" FLOAT, 
	"PurchaseOfPPE" FLOAT, 
	"Receivables" FLOAT, 
	"ReconciledCostOfRevenue" FLOAT, 
	"ReconciledDepreciation" FLOAT, 
	"RepaymentOfDebt" FLOAT, 
	"RepurchaseOfCapitalStock" FLOAT, 
	"ResearchAndDevelopment" FLOAT, 
	"RetainedEarnings" FLOAT, 
	"SaleOfInvestment" FLOAT, 
	"SellingGeneralAndAdministration" FLOAT, 
	"ShareIssued" FLOAT, 
	"StockBasedCompensation" FLOAT, 
	"StockholdersEquity" FLOAT, 
	"TangibleBookValue" FLOAT, 
	"TaxEffectOfUnusualItems" FLOAT, 
	"TaxProvision" FLOAT, 
	"TaxRateForCalcs" FLOAT, 
	"TotalAssets" FLOAT, 
	"TotalCapitalization" FLOAT, 
	"TotalDebt" FLOAT, 
	"TotalEquityGrossMinorityInterest" FLOAT, 
	"TotalExpenses" FLOAT, 
	"TotalLiabilitiesNetMinorityInterest" FLOAT, 
	"TotalNonCurrentAssets" FLOAT, 
	"TotalNonCurrentLiabilitiesNetMinorityInterest" FLOAT, 
	"TotalOperatingIncomeAsReported" FLOAT, 
	"TotalRevenue" FLOAT, 
	"TotalTaxPayable" FLOAT, 
	"TradeandOtherPayablesNonCurrent" FLOAT, 
	"TreasurySharesNumber" FLOAT, 
	"WorkingCapital" FLOAT, 
	"KeyStats_maxAge" BIGINT, 
	"KeyStats_priceHint" BIGINT, 
	"KeyStats_enterpriseValue" BIGINT, 
	"KeyStats_forwardPE" FLOAT, 
	"KeyStats_profitMargins" FLOAT, 
	"KeyStats_floatShares" BIGINT, 
	"KeyStats_sharesOutstanding" BIGINT, 
	"KeyStats_sharesShort" BIGINT, 
	"KeyStats_sharesShortPriorMonth" BIGINT, 
	"KeyStats_sharesShortPreviousMonthDate" TEXT, 
	"KeyStats_dateShortInterest" TEXT, 
	"KeyStats_sharesPercentSharesOut" FLOAT, 
	"KeyStats_heldPercentInsiders" FLOAT, 
	"KeyStats_heldPercentInstitutions" FLOAT, 
	"KeyStats_shortRatio" FLOAT, 
	"KeyStats_shortPercentOfFloat" FLOAT, 
	"KeyStats_beta" FLOAT, 
	"KeyStats_impliedSharesOutstanding" BIGINT, 
	"KeyStats_category" TEXT, 
	"KeyStats_bookValue" FLOAT, 
	"KeyStats_priceToBook" FLOAT, 
	"KeyStats_fundFamily" TEXT, 
	"KeyStats_legalType" TEXT, 
	"KeyStats_lastFiscalYearEnd" TEXT, 
	"KeyStats_nextFiscalYearEnd" TEXT, 
	"KeyStats_mostRecentQuarter" TEXT, 
	"KeyStats_earningsQuarterlyGrowth" FLOAT, 
	"KeyStats_netIncomeToCommon" BIGINT, 
	"KeyStats_trailingEps" FLOAT, 
	"KeyStats_forwardEps" FLOAT, 
	"KeyStats_lastSplitFactor" TEXT, 
	"KeyStats_lastSplitDate" TEXT, 
	"KeyStats_enterpriseToRevenue" FLOAT, 
	"KeyStats_enterpriseToEbitda" FLOAT, 
	"KeyStats_52WeekChange" FLOAT, 
	"KeyStats_SandP52WeekChange" FLOAT, 
	"KeyStats_lastDividendValue" FLOAT, 
	"KeyStats_lastDividendDate" BIGINT, 
	"KeyStats_latestShareClass" TEXT, 
	"KeyStats_leadInvestor" TEXT, 
	"Forward_EPS_Growth_Percent" FLOAT, 
	"Summary_maxAge" BIGINT, 
	"Summary_priceHint" BIGINT, 
	"Summary_previousClose" FLOAT, 
	"Summary_open" FLOAT, 
	"Summary_dayLow" FLOAT, 
	"Summary_dayHigh" FLOAT, 
	"Summary_regularMarketPreviousClose" FLOAT, 
	"Summary_regularMarketOpen" FLOAT, 
	"Summary_regularMarketDayLow" FLOAT, 
	"Summary_regularMarketDayHigh" FLOAT, 
	"Summary_dividendRate" FLOAT, 
	"Summary_dividendYield" FLOAT, 
	"Summary_exDividendDate" TEXT, 
	"Summary_payoutRatio" FLOAT, 
	"Summary_fiveYearAvgDividendYield" FLOAT, 
	"Summary_beta" FLOAT, 
	"Summary_trailingPE" FLOAT, 
	"Summary_forwardPE" FLOAT, 
	"Summary_volume" BIGINT, 
	"Summary_regularMarketVolume" BIGINT, 
	"Summary_averageVolume" BIGINT, 
	"Summary_averageVolume10days" BIGINT, 
	"Summary_averageDailyVolume10Day" BIGINT, 
	"Summary_bid" FLOAT, 
	"Summary_ask" FLOAT, 
	"Summary_bidSize" BIGINT, 
	"Summary_askSize" BIGINT, 
	"Summary_marketCap" BIGINT, 
	"Summary_fiftyTwoWeekLow" FLOAT, 
	"Summary_fiftyTwoWeekHigh" FLOAT, 
	"Summary_priceToSalesTrailing12Months" FLOAT, 
	"Summary_fiftyDayAverage" FLOAT, 
	"Summary_twoHundredDayAverage" FLOAT, 
	"Summary_trailingAnnualDividendRate" FLOAT, 
	"Summary_trailingAnnualDividendYield" FLOAT, 
	"Summary_currency" TEXT, 
	"Summary_fromCurrency" TEXT, 
	"Summary_toCurrency" TEXT, 
	"Summary_lastMarket" TEXT, 
	"Summary_coinMarketCapLink" TEXT, 
	"Summary_algorithm" TEXT, 
	"Summary_tradeable" BOOLEAN, 
	"FinData_maxAge" BIGINT, 
	"FinData_currentPrice" FLOAT, 
	"FinData_targetHighPrice" FLOAT, 
	"FinData_targetLowPrice" FLOAT, 
	"FinData_targetMeanPrice" FLOAT, 
	"FinData_targetMedianPrice" FLOAT, 
	"FinData_recommendationMean" FLOAT, 
	"FinData_recommendationKey" TEXT, 
	"FinData_numberOfAnalystOpinions" BIGINT, 
	"FinData_totalCash" BIGINT, 
	"FinData_totalCashPerShare" FLOAT, 
	"FinData_ebitda" BIGINT, 
	"FinData_totalDebt" BIGINT, 
	"FinData_quickRatio" FLOAT, 
	"FinData_currentRatio" FLOAT, 
	"FinData_totalRevenue" BIGINT, 
	"FinData_debtToEquity" FLOAT, 
	"FinData_revenuePerShare" FLOAT, 
	"FinData_returnOnAssets" FLOAT, 
	"FinData_returnOnEquity" FLOAT, 
	"FinData_grossProfits" BIGINT, 
	"FinData_freeCashflow" BIGINT, 
	"FinData_operatingCashflow" BIGINT, 
	"FinData_earningsGrowth" FLOAT, 
	"FinData_revenueGrowth" FLOAT, 
	"FinData_grossMargins" FLOAT, 
	"FinData_ebitdaMargins" FLOAT, 
	"FinData_operatingMargins" FLOAT, 
	"FinData_profitMargins" FLOAT, 
	"FinData_financialCurrency" TEXT
);
DROP TABLE IF EXISTS "FundamentalDataYahooProcessed";
CREATE TABLE "FundamentalDataYahooProcessed" (
	symbol TEXT, 
	"asOfDate" DATETIME, 
	"periodType" TEXT, 
	"currencyCode" TEXT, 
	"AccountsPayable" FLOAT, 
	"AccountsReceivable" FLOAT, 
	"AccumulatedDepreciation" FLOAT, 
	"AvailableForSaleSecurities" FLOAT, 
	"BasicAverageShares" FLOAT, 
	"BasicEPS" FLOAT, 
	"BeginningCashPosition" FLOAT, 
	"CapitalExpenditure" FLOAT, 
	"CapitalLeaseObligations" FLOAT, 
	"CapitalStock" FLOAT, 
	"CashAndCashEquivalents" FLOAT, 
	"CashCashEquivalentsAndShortTermInvestments" FLOAT, 
	"CashDividendsPaid" FLOAT, 
	"CashEquivalents" FLOAT, 
	"CashFinancial" FLOAT, 
	"CashFlowFromContinuingFinancingActivities" FLOAT, 
	"CashFlowFromContinuingInvestingActivities" FLOAT, 
	"CashFlowFromContinuingOperatingActivities" FLOAT, 
	"ChangeInAccountPayable" FLOAT, 
	"ChangeInCashSupplementalAsReported" FLOAT, 
	"ChangeInInventory" FLOAT, 
	"ChangeInOtherCurrentAssets" FLOAT, 
	"ChangeInOtherCurrentLiabilities" FLOAT, 
	"ChangeInOtherWorkingCapital" FLOAT, 
	"ChangeInPayable" FLOAT, 
	"ChangeInPayablesAndAccruedExpense" FLOAT, 
	"ChangeInReceivables" FLOAT, 
	"ChangeInWorkingCapital" FLOAT, 
	"ChangesInAccountReceivables" FLOAT, 
	"ChangesInCash" FLOAT, 
	"CommercialPaper" FLOAT, 
	"CommonStock" FLOAT, 
	"CommonStockDividendPaid" FLOAT, 
	"CommonStockEquity" FLOAT, 
	"CommonStockIssuance" FLOAT, 
	"CommonStockPayments" FLOAT, 
	"CostOfRevenue" FLOAT, 
	"CurrentAssets" FLOAT, 
	"CurrentCapitalLeaseObligation" FLOAT, 
	"CurrentDebt" FLOAT, 
	"CurrentDebtAndCapitalLeaseObligation" FLOAT, 
	"CurrentDeferredLiabilities" FLOAT, 
	"CurrentDeferredRevenue" FLOAT, 
	"CurrentLiabilities" FLOAT, 
	"DeferredIncomeTax" FLOAT, 
	"DeferredTax" FLOAT, 
	"DepreciationAmortizationDepletion" FLOAT, 
	"DepreciationAndAmortization" FLOAT, 
	"DilutedAverageShares" FLOAT, 
	"DilutedEPS" FLOAT, 
	"DilutedNIAvailtoComStockholders" FLOAT, 
	"EBIT" FLOAT, 
	"EBITDA" FLOAT, 
	"EndCashPosition" FLOAT, 
	"EnterpriseValue" FLOAT, 
	"EnterprisesValueEBITDARatio" FLOAT, 
	"EnterprisesValueRevenueRatio" FLOAT, 
	"FinancingCashFlow" FLOAT, 
	"FreeCashFlow" FLOAT, 
	"GainsLossesNotAffectingRetainedEarnings" FLOAT, 
	"GrossPPE" FLOAT, 
	"GrossProfit" FLOAT, 
	"IncomeTaxPaidSupplementalData" FLOAT, 
	"IncomeTaxPayable" FLOAT, 
	"InterestExpense" FLOAT, 
	"InterestExpenseNonOperating" FLOAT, 
	"InterestIncome" FLOAT, 
	"InterestIncomeNonOperating" FLOAT, 
	"InterestPaidSupplementalData" FLOAT, 
	"Inventory" FLOAT, 
	"InvestedCapital" FLOAT, 
	"InvestingCashFlow" FLOAT, 
	"InvestmentinFinancialAssets" FLOAT, 
	"InvestmentsAndAdvances" FLOAT, 
	"IssuanceOfCapitalStock" FLOAT, 
	"IssuanceOfDebt" FLOAT, 
	"LandAndImprovements" FLOAT, 
	"Leases" FLOAT, 
	"LongTermCapitalLeaseObligation" FLOAT, 
	"LongTermDebt" FLOAT, 
	"LongTermDebtAndCapitalLeaseObligation" FLOAT, 
	"LongTermDebtIssuance" FLOAT, 
	"LongTermDebtPayments" FLOAT, 
	"MachineryFurnitureEquipment" FLOAT, 
	"MarketCap" FLOAT, 
	"NetBusinessPurchaseAndSale" FLOAT, 
	"NetCommonStockIssuance" FLOAT, 
	"NetDebt" FLOAT, 
	"NetIncome" FLOAT, 
	"NetIncomeCommonStockholders" FLOAT, 
	"NetIncomeContinuousOperations" FLOAT, 
	"NetIncomeFromContinuingAndDiscontinuedOperation" FLOAT, 
	"NetIncomeFromContinuingOperationNetMinorityInterest" FLOAT, 
	"NetIncomeFromContinuingOperations" FLOAT, 
	"NetIncomeIncludingNoncontrollingInterests" FLOAT, 
	"NetInterestIncome" FLOAT, 
	"NetInvestmentPurchaseAndSale" FLOAT, 
	"NetIssuancePaymentsOfDebt" FLOAT, 
	"NetLongTermDebtIssuance" FLOAT, 
	"NetNonOperatingInterestIncomeExpense" FLOAT, 
	"NetOtherFinancingCharges" FLOAT, 
	"NetOtherInvestingChanges" FLOAT, 
	"NetPPE" FLOAT, 
	"NetPPEPurchaseAndSale" FLOAT, 
	"NetShortTermDebtIssuance" FLOAT, 
	"NetTangibleAssets" FLOAT, 
	"NonCurrentDeferredAssets" FLOAT, 
	"NonCurrentDeferredTaxesAssets" FLOAT, 
	"NormalizedEBITDA" FLOAT, 
	"NormalizedIncome" FLOAT, 
	"OperatingCashFlow" FLOAT, 
	"OperatingExpense" FLOAT, 
	"OperatingIncome" FLOAT, 
	"OperatingRevenue" FLOAT, 
	"OrdinarySharesNumber" FLOAT, 
	"OtherCurrentAssets" FLOAT, 
	"OtherCurrentBorrowings" FLOAT, 
	"OtherCurrentLiabilities" FLOAT, 
	"OtherEquityAdjustments" FLOAT, 
	"OtherIncomeExpense" FLOAT, 
	"OtherInvestments" FLOAT, 
	"OtherNonCashItems" FLOAT, 
	"OtherNonCurrentAssets" FLOAT, 
	"OtherNonCurrentLiabilities" FLOAT, 
	"OtherNonOperatingIncomeExpenses" FLOAT, 
	"OtherProperties" FLOAT, 
	"OtherReceivables" FLOAT, 
	"OtherShortTermInvestments" FLOAT, 
	"Payables" FLOAT, 
	"PayablesAndAccruedExpenses" FLOAT, 
	"PretaxIncome" FLOAT, 
	"Properties" FLOAT, 
	"PurchaseOfBusiness" FLOAT, 
	"PurchaseOfInvestment" FLOAT, 
	"PurchaseOfPPE" FLOAT, 
	"Receivables" FLOAT, 
	"ReconciledCostOfRevenue" FLOAT, 
	"ReconciledDepreciation" FLOAT, 
	"RepaymentOfDebt" FLOAT, 
	"RepurchaseOfCapitalStock" FLOAT, 
	"ResearchAndDevelopment" FLOAT, 
	"RetainedEarnings" FLOAT, 
	"SaleOfInvestment" FLOAT, 
	"SellingGeneralAndAdministration" FLOAT, 
	"ShareIssued" FLOAT, 
	"StockBasedCompensation" FLOAT, 
	"StockholdersEquity" FLOAT, 
	"TangibleBookValue" FLOAT, 
	"TaxEffectOfUnusualItems" FLOAT, 
	"TaxProvision" FLOAT, 
	"TaxRateForCalcs" FLOAT, 
	"TotalAssets" FLOAT, 
	"TotalCapitalization" FLOAT, 
	"TotalDebt" FLOAT, 
	"TotalEquityGrossMinorityInterest" FLOAT, 
	"TotalExpenses" FLOAT, 
	"TotalLiabilitiesNetMinorityInterest" FLOAT, 
	"TotalNonCurrentAssets" FLOAT, 
	"TotalNonCurrentLiabilitiesNetMinorityInterest" FLOAT, 
	"TotalOperatingIncomeAsReported" FLOAT, 
	"TotalRevenue" FLOAT, 
	"TotalTaxPayable" FLOAT, 
	"TradeandOtherPayablesNonCurrent" FLOAT, 
	"TreasurySharesNumber" FLOAT, 
	"WorkingCapital" FLOAT, 
	"KeyStats_maxAge" BIGINT, 
	"KeyStats_priceHint" BIGINT, 
	"KeyStats_enterpriseValue" BIGINT, 
	"KeyStats_forwardPE" FLOAT, 
	"KeyStats_profitMargins" FLOAT, 
	"KeyStats_floatShares" BIGINT, 
	"KeyStats_sharesOutstanding" BIGINT, 
	"KeyStats_sharesShort" BIGINT, 
	"KeyStats_sharesShortPriorMonth" BIGINT, 
	"KeyStats_sharesShortPreviousMonthDate" TEXT, 
	"KeyStats_dateShortInterest" TEXT, 
	"KeyStats_sharesPercentSharesOut" FLOAT, 
	"KeyStats_heldPercentInsiders" FLOAT, 
	"KeyStats_heldPercentInstitutions" FLOAT, 
	"KeyStats_shortRatio" FLOAT, 
	"KeyStats_shortPercentOfFloat" FLOAT, 
	"KeyStats_beta" FLOAT, 
	"KeyStats_impliedSharesOutstanding" BIGINT, 
	"KeyStats_category" TEXT, 
	"KeyStats_bookValue" FLOAT, 
	"KeyStats_priceToBook" FLOAT, 
	"KeyStats_fundFamily" TEXT, 
	"KeyStats_legalType" TEXT, 
	"KeyStats_lastFiscalYearEnd" TEXT, 
	"KeyStats_nextFiscalYearEnd" TEXT, 
	"KeyStats_mostRecentQuarter" TEXT, 
	"KeyStats_earningsQuarterlyGrowth" FLOAT, 
	"KeyStats_netIncomeToCommon" BIGINT, 
	"KeyStats_trailingEps" FLOAT, 
	"KeyStats_forwardEps" FLOAT, 
	"KeyStats_lastSplitFactor" TEXT, 
	"KeyStats_lastSplitDate" TEXT, 
	"KeyStats_enterpriseToRevenue" FLOAT, 
	"KeyStats_enterpriseToEbitda" FLOAT, 
	"KeyStats_52WeekChange" FLOAT, 
	"KeyStats_SandP52WeekChange" FLOAT, 
	"KeyStats_lastDividendValue" FLOAT, 
	"KeyStats_lastDividendDate" BIGINT, 
	"KeyStats_latestShareClass" TEXT, 
	"KeyStats_leadInvestor" TEXT, 
	"Forward_EPS_Growth_Percent" FLOAT, 
	"Summary_maxAge" BIGINT, 
	"Summary_priceHint" BIGINT, 
	"Summary_previousClose" FLOAT, 
	"Summary_open" FLOAT, 
	"Summary_dayLow" FLOAT, 
	"Summary_dayHigh" FLOAT, 
	"Summary_regularMarketPreviousClose" FLOAT, 
	"Summary_regularMarketOpen" FLOAT, 
	"Summary_regularMarketDayLow" FLOAT, 
	"Summary_regularMarketDayHigh" FLOAT, 
	"Summary_dividendRate" FLOAT, 
	"Summary_dividendYield" FLOAT, 
	"Summary_exDividendDate" TEXT, 
	"Summary_payoutRatio" FLOAT, 
	"Summary_fiveYearAvgDividendYield" FLOAT, 
	"Summary_beta" FLOAT, 
	"Summary_trailingPE" FLOAT, 
	"Summary_forwardPE" FLOAT, 
	"Summary_volume" BIGINT, 
	"Summary_regularMarketVolume" BIGINT, 
	"Summary_averageVolume" BIGINT, 
	"Summary_averageVolume10days" BIGINT, 
	"Summary_averageDailyVolume10Day" BIGINT, 
	"Summary_bid" FLOAT, 
	"Summary_ask" FLOAT, 
	"Summary_bidSize" BIGINT, 
	"Summary_askSize" BIGINT, 
	"Summary_marketCap" BIGINT, 
	"Summary_fiftyTwoWeekLow" FLOAT, 
	"Summary_fiftyTwoWeekHigh" FLOAT, 
	"Summary_priceToSalesTrailing12Months" FLOAT, 
	"Summary_fiftyDayAverage" FLOAT, 
	"Summary_twoHundredDayAverage" FLOAT, 
	"Summary_trailingAnnualDividendRate" FLOAT, 
	"Summary_trailingAnnualDividendYield" FLOAT, 
	"Summary_currency" TEXT, 
	"Summary_fromCurrency" TEXT, 
	"Summary_toCurrency" TEXT, 
	"Summary_lastMarket" TEXT, 
	"Summary_coinMarketCapLink" TEXT, 
	"Summary_algorithm" TEXT, 
	"Summary_tradeable" BOOLEAN, 
	"FinData_maxAge" BIGINT, 
	"FinData_currentPrice" FLOAT, 
	"FinData_targetHighPrice" FLOAT, 
	"FinData_targetLowPrice" FLOAT, 
	"FinData_targetMeanPrice" FLOAT, 
	"FinData_targetMedianPrice" FLOAT, 
	"FinData_recommendationMean" FLOAT, 
	"FinData_recommendationKey" TEXT, 
	"FinData_numberOfAnalystOpinions" BIGINT, 
	"FinData_totalCash" BIGINT, 
	"FinData_totalCashPerShare" FLOAT, 
	"FinData_ebitda" BIGINT, 
	"FinData_totalDebt" BIGINT, 
	"FinData_quickRatio" FLOAT, 
	"FinData_currentRatio" FLOAT, 
	"FinData_totalRevenue" BIGINT, 
	"FinData_debtToEquity" FLOAT, 
	"FinData_revenuePerShare" FLOAT, 
	"FinData_returnOnAssets" FLOAT, 
	"FinData_returnOnEquity" FLOAT, 
	"FinData_grossProfits" BIGINT, 
	"FinData_freeCashflow" BIGINT, 
	"FinData_operatingCashflow" BIGINT, 
	"FinData_earningsGrowth" FLOAT, 
	"FinData_revenueGrowth" FLOAT, 
	"FinData_grossMargins" FLOAT, 
	"FinData_ebitdaMargins" FLOAT, 
	"FinData_operatingMargins" FLOAT, 
	"FinData_profitMargins" FLOAT, 
	"FinData_financialCurrency" TEXT, 
	"PE_Ratio_Calc" FLOAT, 
	"PS_Ratio" FLOAT, 
	"DebtToMarketCap" FLOAT, 
	"EV_EBITDA_Approx" FLOAT
);

DROP VIEW IF EXISTS FundamentalData;
CREATE VIEW FundamentalData AS
SELECT 
	a."Symbol", 
	a."Company", 
	a."FV", 
	a."Sector", 
	a."No-Years", 
	a."Price", 
	a."Div-Yield", 
	a."5Y-Avg-Yield", 
	a."Current-Div", 
	a."Payouts/-Year", 
	a."Annualized", 
	a."Previous-Div", 
	a."Ex-Date", 
	a."Pay-Date", 
	a."Low", 
	a."High", 
	a."DGR-1Y", 
	a."DGR-3Y", 
	a."DGR-5Y", 
	a."DGR-10Y", 
	a."TTR-1Y", 
	a."TTR-3Y", 
	a."Fair-Value", 
	a."FV-%", 
	a."Streak-Basis", 
	a."Chowder-Number", 
	a."EPS-1Y", 
	a."Revenue-1Y", 
	a."NPM", 
	a."CF/Share", 
	a."ROE", 
	a."Current-R", 
	a."Debt/Capital", 
	a."ROTC", 
	a."P/E", 
	a."P/BV", 
	a."PEG", 
	a."New-Member", 
	a."Industry", 
	a."Classification",

    b."asOfDate", 
	b."periodType", 
	b."currencyCode", 
	b."AccountsPayable", 
	b."AccountsReceivable", 
	b."AccumulatedDepreciation", 
	b."AvailableForSaleSecurities", 
	b."BasicAverageShares", 
	b."BasicEPS", 
	b."BeginningCashPosition", 
	b."CapitalExpenditure", 
	b."CapitalLeaseObligations", 
	b."CapitalStock", 
	b."CashAndCashEquivalents", 
	b."CashCashEquivalentsAndShortTermInvestments", 
	b."CashDividendsPaid", 
	b."CashEquivalents", 
	b."CashFinancial", 
	b."CashFlowFromContinuingFinancingActivities", 
	b."CashFlowFromContinuingInvestingActivities", 
	b."CashFlowFromContinuingOperatingActivities", 
	b."ChangeInAccountPayable", 
	b."ChangeInCashSupplementalAsReported", 
	b."ChangeInInventory", 
	b."ChangeInOtherCurrentAssets", 
	b."ChangeInOtherCurrentLiabilities", 
	b."ChangeInOtherWorkingCapital", 
	b."ChangeInPayable", 
	b."ChangeInPayablesAndAccruedExpense", 
	b."ChangeInReceivables", 
	b."ChangeInWorkingCapital", 
	b."ChangesInAccountReceivables", 
	b."ChangesInCash", 
	b."CommercialPaper", 
	b."CommonStock", 
	b."CommonStockDividendPaid", 
	b."CommonStockEquity", 
	b."CommonStockIssuance", 
	b."CommonStockPayments", 
	b."CostOfRevenue", 
	b."CurrentAssets", 
	b."CurrentCapitalLeaseObligation", 
	b."CurrentDebt", 
	b."CurrentDebtAndCapitalLeaseObligation", 
	b."CurrentDeferredLiabilities", 
	b."CurrentDeferredRevenue", 
	b."CurrentLiabilities", 
	b."DeferredIncomeTax", 
	b."DeferredTax", 
	b."DepreciationAmortizationDepletion", 
	b."DepreciationAndAmortization", 
	b."DilutedAverageShares", 
	b."DilutedEPS", 
	b."DilutedNIAvailtoComStockholders", 
	b."EBIT", 
	b."EBITDA", 
	b."EndCashPosition", 
	b."EnterpriseValue", 
	b."EnterprisesValueEBITDARatio", 
	b."EnterprisesValueRevenueRatio", 
	b."FinancingCashFlow", 
	b."FreeCashFlow", 
	b."GainsLossesNotAffectingRetainedEarnings", 
	b."GrossPPE", 
	b."GrossProfit", 
	b."IncomeTaxPaidSupplementalData", 
	b."IncomeTaxPayable", 
	b."InterestExpense", 
	b."InterestExpenseNonOperating", 
	b."InterestIncome", 
	b."InterestIncomeNonOperating", 
	b."InterestPaidSupplementalData", 
	b."Inventory", 
	b."InvestedCapital", 
	b."InvestingCashFlow", 
	b."InvestmentinFinancialAssets", 
	b."InvestmentsAndAdvances", 
	b."IssuanceOfCapitalStock", 
	b."IssuanceOfDebt", 
	b."LandAndImprovements", 
	b."Leases", 
	b."LongTermCapitalLeaseObligation", 
	b."LongTermDebt", 
	b."LongTermDebtAndCapitalLeaseObligation", 
	b."LongTermDebtIssuance", 
	b."LongTermDebtPayments", 
	b."MachineryFurnitureEquipment", 
	b."MarketCap", 
	b."NetBusinessPurchaseAndSale", 
	b."NetCommonStockIssuance", 
	b."NetDebt", 
	b."NetIncome", 
	b."NetIncomeCommonStockholders", 
	b."NetIncomeContinuousOperations", 
	b."NetIncomeFromContinuingAndDiscontinuedOperation", 
	b."NetIncomeFromContinuingOperationNetMinorityInterest", 
	b."NetIncomeFromContinuingOperations", 
	b."NetIncomeIncludingNoncontrollingInterests", 
	b."NetInterestIncome", 
	b."NetInvestmentPurchaseAndSale", 
	b."NetIssuancePaymentsOfDebt", 
	b."NetLongTermDebtIssuance", 
	b."NetNonOperatingInterestIncomeExpense", 
	b."NetOtherFinancingCharges", 
	b."NetOtherInvestingChanges", 
	b."NetPPE", 
	b."NetPPEPurchaseAndSale", 
	b."NetShortTermDebtIssuance", 
	b."NetTangibleAssets", 
	b."NonCurrentDeferredAssets", 
	b."NonCurrentDeferredTaxesAssets", 
	b."NormalizedEBITDA", 
	b."NormalizedIncome", 
	b."OperatingCashFlow", 
	b."OperatingExpense", 
	b."OperatingIncome", 
	b."OperatingRevenue", 
	b."OrdinarySharesNumber", 
	b."OtherCurrentAssets", 
	b."OtherCurrentBorrowings", 
	b."OtherCurrentLiabilities", 
	b."OtherEquityAdjustments", 
	b."OtherIncomeExpense", 
	b."OtherInvestments", 
	b."OtherNonCashItems", 
	b."OtherNonCurrentAssets", 
	b."OtherNonCurrentLiabilities", 
	b."OtherNonOperatingIncomeExpenses", 
	b."OtherProperties", 
	b."OtherReceivables", 
	b."OtherShortTermInvestments", 
	b."Payables", 
	b."PayablesAndAccruedExpenses", 
	b."PretaxIncome", 
	b."Properties", 
	b."PurchaseOfBusiness", 
	b."PurchaseOfInvestment", 
	b."PurchaseOfPPE", 
	b."Receivables", 
	b."ReconciledCostOfRevenue", 
	b."ReconciledDepreciation", 
	b."RepaymentOfDebt", 
	b."RepurchaseOfCapitalStock", 
	b."ResearchAndDevelopment", 
	b."RetainedEarnings", 
	b."SaleOfInvestment", 
	b."SellingGeneralAndAdministration", 
	b."ShareIssued", 
	b."StockBasedCompensation", 
	b."StockholdersEquity", 
	b."TangibleBookValue", 
	b."TaxEffectOfUnusualItems", 
	b."TaxProvision", 
	b."TaxRateForCalcs", 
	b."TotalAssets", 
	b."TotalCapitalization", 
	b."TotalDebt", 
	b."TotalEquityGrossMinorityInterest", 
	b."TotalExpenses", 
	b."TotalLiabilitiesNetMinorityInterest", 
	b."TotalNonCurrentAssets", 
	b."TotalNonCurrentLiabilitiesNetMinorityInterest", 
	b."TotalOperatingIncomeAsReported", 
	b."TotalRevenue", 
	b."TotalTaxPayable", 
	b."TradeandOtherPayablesNonCurrent", 
	b."TreasurySharesNumber", 
	b."WorkingCapital", 
	b."KeyStats_maxAge", 
	b."KeyStats_priceHint", 
	b."KeyStats_enterpriseValue", 
	b."KeyStats_forwardPE", 
	b."KeyStats_profitMargins", 
	b."KeyStats_floatShares", 
	b."KeyStats_sharesOutstanding", 
	b."KeyStats_sharesShort", 
	b."KeyStats_sharesShortPriorMonth", 
	b."KeyStats_sharesShortPreviousMonthDate", 
	b."KeyStats_dateShortInterest", 
	b."KeyStats_sharesPercentSharesOut", 
	b."KeyStats_heldPercentInsiders", 
	b."KeyStats_heldPercentInstitutions", 
	b."KeyStats_shortRatio", 
	b."KeyStats_shortPercentOfFloat", 
	b."KeyStats_beta", 
	b."KeyStats_impliedSharesOutstanding", 
	b."KeyStats_category", 
	b."KeyStats_bookValue", 
	b."KeyStats_priceToBook", 
	b."KeyStats_fundFamily", 
	b."KeyStats_legalType", 
	b."KeyStats_lastFiscalYearEnd", 
	b."KeyStats_nextFiscalYearEnd", 
	b."KeyStats_mostRecentQuarter", 
	b."KeyStats_earningsQuarterlyGrowth", 
	b."KeyStats_netIncomeToCommon", 
	b."KeyStats_trailingEps", 
	b."KeyStats_forwardEps", 
	b."KeyStats_lastSplitFactor", 
	b."KeyStats_lastSplitDate", 
	b."KeyStats_enterpriseToRevenue", 
	b."KeyStats_enterpriseToEbitda", 
	b."KeyStats_52WeekChange", 
	b."KeyStats_SandP52WeekChange", 
	b."KeyStats_lastDividendValue", 
	b."KeyStats_lastDividendDate", 
	b."KeyStats_latestShareClass", 
	b."KeyStats_leadInvestor", 
	b."Forward_EPS_Growth_Percent", 
	b."Summary_maxAge", 
	b."Summary_priceHint", 
	b."Summary_previousClose", 
	b."Summary_open", 
	b."Summary_dayLow", 
	b."Summary_dayHigh", 
	b."Summary_regularMarketPreviousClose", 
	b."Summary_regularMarketOpen", 
	b."Summary_regularMarketDayLow", 
	b."Summary_regularMarketDayHigh", 
	b."Summary_dividendRate", 
	b."Summary_dividendYield", 
	b."Summary_exDividendDate", 
	b."Summary_payoutRatio", 
	b."Summary_fiveYearAvgDividendYield", 
	b."Summary_beta", 
	b."Summary_trailingPE", 
	b."Summary_forwardPE", 
	b."Summary_volume", 
	b."Summary_regularMarketVolume", 
	b."Summary_averageVolume", 
	b."Summary_averageVolume10days", 
	b."Summary_averageDailyVolume10Day", 
	b."Summary_bid", 
	b."Summary_ask", 
	b."Summary_bidSize", 
	b."Summary_askSize", 
	b."Summary_marketCap", 
	b."Summary_fiftyTwoWeekLow", 
	b."Summary_fiftyTwoWeekHigh", 
	b."Summary_priceToSalesTrailing12Months", 
	b."Summary_fiftyDayAverage", 
	b."Summary_twoHundredDayAverage", 
	b."Summary_trailingAnnualDividendRate", 
	b."Summary_trailingAnnualDividendYield", 
	b."Summary_currency", 
	b."Summary_fromCurrency", 
	b."Summary_toCurrency", 
	b."Summary_lastMarket", 
	b."Summary_coinMarketCapLink", 
	b."Summary_algorithm", 
	b."Summary_tradeable", 
	b."FinData_maxAge", 
	b."FinData_currentPrice", 
	b."FinData_targetHighPrice", 
	b."FinData_targetLowPrice", 
	b."FinData_targetMeanPrice", 
	b."FinData_targetMedianPrice", 
	b."FinData_recommendationMean", 
	b."FinData_recommendationKey", 
	b."FinData_numberOfAnalystOpinions", 
	b."FinData_totalCash", 
	b."FinData_totalCashPerShare", 
	b."FinData_ebitda", 
	b."FinData_totalDebt", 
	b."FinData_quickRatio", 
	b."FinData_currentRatio", 
	b."FinData_totalRevenue", 
	b."FinData_debtToEquity", 
	b."FinData_revenuePerShare", 
	b."FinData_returnOnAssets", 
	b."FinData_returnOnEquity", 
	b."FinData_grossProfits", 
	b."FinData_freeCashflow", 
	b."FinData_operatingCashflow", 
	b."FinData_earningsGrowth", 
	b."FinData_revenueGrowth", 
	b."FinData_grossMargins", 
	b."FinData_ebitdaMargins", 
	b."FinData_operatingMargins", 
	b."FinData_profitMargins", 
	b."FinData_financialCurrency", 
	b."PE_Ratio_Calc", 
	b."PS_Ratio", 
	b."DebtToMarketCap", 
	b."EV_EBITDA_Approx"
FROM 
    FundamentalDataDividendRadar AS a
JOIN 
    FundamentalDataYahooProcessed as b
ON a."Symbol" = b.symbol;

DROP VIEW IF EXISTS OptionDataMerged;
CREATE VIEW OptionDataMerged AS
SELECT 
	-- Option Data
    a.symbol, 
	a."option-type", 
	a.strike, 
	a.expiration_date, 
    a.ask, 
	a.bid, 
	a.delta, 
	a.gamma, 
	a.iv, 
	a.rho, 
    a."theoPrice", 
	a.theta, 
	a.vega, 
	a.option, 
	a.time, 
	a.exchange, 
	a.option_osi,
    a."contractSymbol",  
	a.currency, 
	a."lastPrice", 
	a.change, 
	a."percentChange", 
	a.option_open_interest, 
	a."contractSize", 
	a."lastTradeDate", 
	a."impliedVolatility", 
	a."inTheMoney", 
	a.option_volume,

    -- Fundamental Data
	b."Company", 
	b."FV", 
	b."Sector", 
	b."No-Years", 
	b."Price", 
	b."Div-Yield", 
	b."5Y-Avg-Yield", 
	b."Current-Div", 
	b."Payouts/-Year", 
	b."Annualized", 
	b."Previous-Div", 
	b."Ex-Date", 
	b."Pay-Date", 
	b."Low", 
	b."High", 
	b."DGR-1Y", 
	b."DGR-3Y", 
	b."DGR-5Y", 
	b."DGR-10Y", 
	b."TTR-1Y", 
	b."TTR-3Y", 
	b."Fair-Value", 
	b."FV-%", 
	b."Streak-Basis", 
	b."Chowder-Number", 
	b."EPS-1Y", 
	b."Revenue-1Y", 
	b."NPM", 
	b."CF/Share", 
	b."ROE", 
	b."Current-R", 
	b."Debt/Capital", 
	b."ROTC", 
	b."P/E", 
	b."P/BV", 
	b."PEG", 
	b."New-Member", 
	b."Industry", 
	b."Classification",
    b."asOfDate", 
	b."periodType", 
	b."currencyCode", 
	b."AccountsPayable", 
	b."AccountsReceivable", 
	b."AccumulatedDepreciation", 
	b."AvailableForSaleSecurities", 
	b."BasicAverageShares", 
	b."BasicEPS", 
	b."BeginningCashPosition", 
	b."CapitalExpenditure", 
	b."CapitalLeaseObligations", 
	b."CapitalStock", 
	b."CashAndCashEquivalents", 
	b."CashCashEquivalentsAndShortTermInvestments", 
	b."CashDividendsPaid", 
	b."CashEquivalents", 
	b."CashFinancial", 
	b."CashFlowFromContinuingFinancingActivities", 
	b."CashFlowFromContinuingInvestingActivities", 
	b."CashFlowFromContinuingOperatingActivities", 
	b."ChangeInAccountPayable", 
	b."ChangeInCashSupplementalAsReported", 
	b."ChangeInInventory", 
	b."ChangeInOtherCurrentAssets", 
	b."ChangeInOtherCurrentLiabilities", 
	b."ChangeInOtherWorkingCapital", 
	b."ChangeInPayable", 
	b."ChangeInPayablesAndAccruedExpense", 
	b."ChangeInReceivables", 
	b."ChangeInWorkingCapital", 
	b."ChangesInAccountReceivables", 
	b."ChangesInCash", 
	b."CommercialPaper", 
	b."CommonStock", 
	b."CommonStockDividendPaid", 
	b."CommonStockEquity", 
	b."CommonStockIssuance", 
	b."CommonStockPayments", 
	b."CostOfRevenue", 
	b."CurrentAssets", 
	b."CurrentCapitalLeaseObligation", 
	b."CurrentDebt", 
	b."CurrentDebtAndCapitalLeaseObligation", 
	b."CurrentDeferredLiabilities", 
	b."CurrentDeferredRevenue", 
	b."CurrentLiabilities", 
	b."DeferredIncomeTax", 
	b."DeferredTax", 
	b."DepreciationAmortizationDepletion", 
	b."DepreciationAndAmortization", 
	b."DilutedAverageShares", 
	b."DilutedEPS", 
	b."DilutedNIAvailtoComStockholders", 
	b."EBIT", 
	b."EBITDA", 
	b."EndCashPosition", 
	b."EnterpriseValue", 
	b."EnterprisesValueEBITDARatio", 
	b."EnterprisesValueRevenueRatio", 
	b."FinancingCashFlow", 
	b."FreeCashFlow", 
	b."GainsLossesNotAffectingRetainedEarnings", 
	b."GrossPPE", 
	b."GrossProfit", 
	b."IncomeTaxPaidSupplementalData", 
	b."IncomeTaxPayable", 
	b."InterestExpense", 
	b."InterestExpenseNonOperating", 
	b."InterestIncome", 
	b."InterestIncomeNonOperating", 
	b."InterestPaidSupplementalData", 
	b."Inventory", 
	b."InvestedCapital", 
	b."InvestingCashFlow", 
	b."InvestmentinFinancialAssets", 
	b."InvestmentsAndAdvances", 
	b."IssuanceOfCapitalStock", 
	b."IssuanceOfDebt", 
	b."LandAndImprovements", 
	b."Leases", 
	b."LongTermCapitalLeaseObligation", 
	b."LongTermDebt", 
	b."LongTermDebtAndCapitalLeaseObligation", 
	b."LongTermDebtIssuance", 
	b."LongTermDebtPayments", 
	b."MachineryFurnitureEquipment", 
	b."MarketCap", 
	b."NetBusinessPurchaseAndSale", 
	b."NetCommonStockIssuance", 
	b."NetDebt", 
	b."NetIncome", 
	b."NetIncomeCommonStockholders", 
	b."NetIncomeContinuousOperations", 
	b."NetIncomeFromContinuingAndDiscontinuedOperation", 
	b."NetIncomeFromContinuingOperationNetMinorityInterest", 
	b."NetIncomeFromContinuingOperations", 
	b."NetIncomeIncludingNoncontrollingInterests", 
	b."NetInterestIncome", 
	b."NetInvestmentPurchaseAndSale", 
	b."NetIssuancePaymentsOfDebt", 
	b."NetLongTermDebtIssuance", 
	b."NetNonOperatingInterestIncomeExpense", 
	b."NetOtherFinancingCharges", 
	b."NetOtherInvestingChanges", 
	b."NetPPE", 
	b."NetPPEPurchaseAndSale", 
	b."NetShortTermDebtIssuance", 
	b."NetTangibleAssets", 
	b."NonCurrentDeferredAssets", 
	b."NonCurrentDeferredTaxesAssets", 
	b."NormalizedEBITDA", 
	b."NormalizedIncome", 
	b."OperatingCashFlow", 
	b."OperatingExpense", 
	b."OperatingIncome", 
	b."OperatingRevenue", 
	b."OrdinarySharesNumber", 
	b."OtherCurrentAssets", 
	b."OtherCurrentBorrowings", 
	b."OtherCurrentLiabilities", 
	b."OtherEquityAdjustments", 
	b."OtherIncomeExpense", 
	b."OtherInvestments", 
	b."OtherNonCashItems", 
	b."OtherNonCurrentAssets", 
	b."OtherNonCurrentLiabilities", 
	b."OtherNonOperatingIncomeExpenses", 
	b."OtherProperties", 
	b."OtherReceivables", 
	b."OtherShortTermInvestments", 
	b."Payables", 
	b."PayablesAndAccruedExpenses", 
	b."PretaxIncome", 
	b."Properties", 
	b."PurchaseOfBusiness", 
	b."PurchaseOfInvestment", 
	b."PurchaseOfPPE", 
	b."Receivables", 
	b."ReconciledCostOfRevenue", 
	b."ReconciledDepreciation", 
	b."RepaymentOfDebt", 
	b."RepurchaseOfCapitalStock", 
	b."ResearchAndDevelopment", 
	b."RetainedEarnings", 
	b."SaleOfInvestment", 
	b."SellingGeneralAndAdministration", 
	b."ShareIssued", 
	b."StockBasedCompensation", 
	b."StockholdersEquity", 
	b."TangibleBookValue", 
	b."TaxEffectOfUnusualItems", 
	b."TaxProvision", 
	b."TaxRateForCalcs", 
	b."TotalAssets", 
	b."TotalCapitalization", 
	b."TotalDebt", 
	b."TotalEquityGrossMinorityInterest", 
	b."TotalExpenses", 
	b."TotalLiabilitiesNetMinorityInterest", 
	b."TotalNonCurrentAssets", 
	b."TotalNonCurrentLiabilitiesNetMinorityInterest", 
	b."TotalOperatingIncomeAsReported", 
	b."TotalRevenue", 
	b."TotalTaxPayable", 
	b."TradeandOtherPayablesNonCurrent", 
	b."TreasurySharesNumber", 
	b."WorkingCapital", 
	b."KeyStats_maxAge", 
	b."KeyStats_priceHint", 
	b."KeyStats_enterpriseValue", 
	b."KeyStats_forwardPE", 
	b."KeyStats_profitMargins", 
	b."KeyStats_floatShares", 
	b."KeyStats_sharesOutstanding", 
	b."KeyStats_sharesShort", 
	b."KeyStats_sharesShortPriorMonth", 
	b."KeyStats_sharesShortPreviousMonthDate", 
	b."KeyStats_dateShortInterest", 
	b."KeyStats_sharesPercentSharesOut", 
	b."KeyStats_heldPercentInsiders", 
	b."KeyStats_heldPercentInstitutions", 
	b."KeyStats_shortRatio", 
	b."KeyStats_shortPercentOfFloat", 
	b."KeyStats_beta", 
	b."KeyStats_impliedSharesOutstanding", 
	b."KeyStats_category", 
	b."KeyStats_bookValue", 
	b."KeyStats_priceToBook", 
	b."KeyStats_fundFamily", 
	b."KeyStats_legalType", 
	b."KeyStats_lastFiscalYearEnd", 
	b."KeyStats_nextFiscalYearEnd", 
	b."KeyStats_mostRecentQuarter", 
	b."KeyStats_earningsQuarterlyGrowth", 
	b."KeyStats_netIncomeToCommon", 
	b."KeyStats_trailingEps", 
	b."KeyStats_forwardEps", 
	b."KeyStats_lastSplitFactor", 
	b."KeyStats_lastSplitDate", 
	b."KeyStats_enterpriseToRevenue", 
	b."KeyStats_enterpriseToEbitda", 
	b."KeyStats_52WeekChange", 
	b."KeyStats_SandP52WeekChange", 
	b."KeyStats_lastDividendValue", 
	b."KeyStats_lastDividendDate", 
	b."KeyStats_latestShareClass", 
	b."KeyStats_leadInvestor", 
	b."Forward_EPS_Growth_Percent", 
	b."Summary_maxAge", 
	b."Summary_priceHint", 
	b."Summary_previousClose", 
	b."Summary_open", 
	b."Summary_dayLow", 
	b."Summary_dayHigh", 
	b."Summary_regularMarketPreviousClose", 
	b."Summary_regularMarketOpen", 
	b."Summary_regularMarketDayLow", 
	b."Summary_regularMarketDayHigh", 
	b."Summary_dividendRate", 
	b."Summary_dividendYield", 
	b."Summary_exDividendDate", 
	b."Summary_payoutRatio", 
	b."Summary_fiveYearAvgDividendYield", 
	b."Summary_beta", 
	b."Summary_trailingPE", 
	b."Summary_forwardPE", 
	b."Summary_volume", 
	b."Summary_regularMarketVolume", 
	b."Summary_averageVolume", 
	b."Summary_averageVolume10days", 
	b."Summary_averageDailyVolume10Day", 
	b."Summary_bid", 
	b."Summary_ask", 
	b."Summary_bidSize", 
	b."Summary_askSize", 
	b."Summary_marketCap", 
	b."Summary_fiftyTwoWeekLow", 
	b."Summary_fiftyTwoWeekHigh", 
	b."Summary_priceToSalesTrailing12Months", 
	b."Summary_fiftyDayAverage", 
	b."Summary_twoHundredDayAverage", 
	b."Summary_trailingAnnualDividendRate", 
	b."Summary_trailingAnnualDividendYield", 
	b."Summary_currency", 
	b."Summary_fromCurrency", 
	b."Summary_toCurrency", 
	b."Summary_lastMarket", 
	b."Summary_coinMarketCapLink", 
	b."Summary_algorithm", 
	b."Summary_tradeable", 
	b."FinData_maxAge", 
	b."FinData_currentPrice", 
	b."FinData_targetHighPrice", 
	b."FinData_targetLowPrice", 
	b."FinData_targetMeanPrice", 
	b."FinData_targetMedianPrice", 
	b."FinData_recommendationMean", 
	b."FinData_recommendationKey", 
	b."FinData_numberOfAnalystOpinions", 
	b."FinData_totalCash", 
	b."FinData_totalCashPerShare", 
	b."FinData_ebitda", 
	b."FinData_totalDebt", 
	b."FinData_quickRatio", 
	b."FinData_currentRatio", 
	b."FinData_totalRevenue", 
	b."FinData_debtToEquity", 
	b."FinData_revenuePerShare", 
	b."FinData_returnOnAssets", 
	b."FinData_returnOnEquity", 
	b."FinData_grossProfits", 
	b."FinData_freeCashflow", 
	b."FinData_operatingCashflow", 
	b."FinData_earningsGrowth", 
	b."FinData_revenueGrowth", 
	b."FinData_grossMargins", 
	b."FinData_ebitdaMargins", 
	b."FinData_operatingMargins", 
	b."FinData_profitMargins", 
	b."FinData_financialCurrency", 
	b."PE_Ratio_Calc", 
	b."PS_Ratio", 
	b."DebtToMarketCap", 
	b."EV_EBITDA_Approx",

    -- Stock Data
    c.analyst_mean_target,
    c.earnings_date,

    -- Technical Indicators
    d."Recommend.Other", 
	d."Recommend.All", 
	d."Recommend.MA", 
	d."RSI", 
	d."RSI[1]", 
	d."Stoch.K", 
	d."Stoch.D", 
	d."Stoch.K[1]", 
	d."Stoch.D[1]", 
	d."CCI20", 
	d."CCI20[1]", 
	d."ADX", 
	d."ADX+DI", 
	d."ADX-DI", 
	d."ADX+DI[1]", 
	d."ADX-DI[1]", 
	d."AO", 
	d."AO[1]", 
	d."Mom", 
	d."Mom[1]", 
	d."MACD.macd", 
	d."MACD.signal", 
	d."Rec.Stoch.RSI", 
	d."Stoch.RSI.K", 
	d."Rec.WR", 
	d."W.R", 
	d."Rec.BBPower", 
	d."BBPower", 
	d."Rec.UO", 
	d."UO", 
	d.close, 
	d."EMA5", 
	d."SMA5", 
	d."EMA10", 
	d."SMA10", 
	d."EMA20", 
	d."SMA20", 
	d."EMA30", 
	d."SMA30", 
	d."EMA50", 
	d."SMA50", 
	d."EMA100", 
	d."SMA100", 
	d."EMA200", 
	d."SMA200", 
	d."Rec.Ichimoku", 
	d."Ichimoku.BLine", 
	d."Rec.VWMA", 
	d."VWMA", 
	d."Rec.HullMA9", 
	d."HullMA9", 
	d."Pivot.M.Classic.S3", 
	d."Pivot.M.Classic.S2", 
	d."Pivot.M.Classic.S1", 
	d."Pivot.M.Classic.Middle", 
	d."Pivot.M.Classic.R1", 
	d."Pivot.M.Classic.R2", 
	d."Pivot.M.Classic.R3", 
	d."Pivot.M.Fibonacci.S3", 
	d."Pivot.M.Fibonacci.S2", 
	d."Pivot.M.Fibonacci.S1", 
	d."Pivot.M.Fibonacci.Middle", 
	d."Pivot.M.Fibonacci.R1", 
	d."Pivot.M.Fibonacci.R2", 
	d."Pivot.M.Fibonacci.R3", 
	d."Pivot.M.Camarilla.S3", 
	d."Pivot.M.Camarilla.S2", 
	d."Pivot.M.Camarilla.S1", 
	d."Pivot.M.Camarilla.Middle", 
	d."Pivot.M.Camarilla.R1", 
	d."Pivot.M.Camarilla.R2", 
	d."Pivot.M.Camarilla.R3", 
	d."Pivot.M.Woodie.S3", 
	d."Pivot.M.Woodie.S2", 
	d."Pivot.M.Woodie.S1", 
	d."Pivot.M.Woodie.Middle", 
	d."Pivot.M.Woodie.R1", 
	d."Pivot.M.Woodie.R2", 
	d."Pivot.M.Woodie.R3", 
	d."Pivot.M.Demark.S1", 
	d."Pivot.M.Demark.Middle", 
	d."Pivot.M.Demark.R1", 
	d.open, 
	d."P.SAR", 
	d."BB.lower", 
	d."BB.upper", 
	d."AO[2]", 
	d.volume, 
	d.change, 
	d.low, 
	d.high, 
	d.recommendation, 
	d.recommendation_buy_amount, 
	d.recommendation_neutral_amount, 
	d.recommendation_sell_amount
FROM 
    OptionData AS a
JOIN 
    FundamentalData as b
ON a.symbol = a.symbol
JOIN 
    StockData as c
ON a.symbol = c.symbol
JOIN 
    TechnicalIndicators as d
ON a.symbol = d.symbol;
