DROP VIEW IF EXISTS OptionPricingMetrics;

CREATE VIEW
    OptionPricingMetrics AS
Select
    symbol,
    contractSymbol,
    days_to_expiration,
    ROUND(premium_option_price, 2) as premium_option_price,
    spread,
    spread_ptc,
    ROUND(intrinsic_value, 2) as intrinsic_value,
    ROUND(premium_option_price - intrinsic_value, 2) as extrinsic_value,
    strike_stock_price_difference,
    strike_stock_price_difference_ptc
    -- strike - live_stock_price as moneyness
FROM
    (
        select
            a.symbol,
            a.contractSymbol,
            CAST(
                julianday (expiration_date) - julianday ('now') AS INTEGER
            ) AS days_to_expiration,
            a.strike,
            b.live_stock_price,
            ROUND(a.strike - b.live_stock_price, 2) as strike_stock_price_difference,
            ROUND(
                (a.strike - b.live_stock_price) / b.live_stock_price * 100,
                2
            ) as strike_stock_price_difference_ptc,
            case
                when "option-type" = 'calls' then max(live_stock_price - strike, 0)
                when "option-type" = 'puts' then max(strike - live_stock_price, 0)
                else null
            end as intrinsic_value,
            (ask + bid) / 2 as premium_option_price,
            ask - bid as spread,
            ROUND((ask - bid) / bid * 100, 2) as spread_ptc
        from
            OptionDataYahoo as a
            JOIN StockPrice as b ON a.symbol = b.symbol
    );

DROP VIEW IF EXISTS StockData;

CREATE VIEW
    StockData AS
SELECT
    a.symbol,
    a.live_stock_price,
    a.price_source,
    a.live_price_timestamp,
    CASE
        WHEN b.symbol IS NOT NULL THEN TRUE
        ELSE FALSE
    END as has_earnings_date,
    b.earnings_date,
    CAST(
        julianday (b.earnings_date) - julianday ('now') AS INTEGER
    ) AS days_to_earnings,
    CASE
        WHEN c.symbol IS NOT NULL THEN TRUE
        ELSE FALSE
    END as has_analyst_price_target,
    c.analyst_mean_target
FROM
    StockPrice AS a
    LEFT OUTER JOIN (
        SELECT
            symbol,
            CASE WHEN earnings_date LIKE '%.%.%' THEN
            substr (earnings_date, 7, 4) || '-' || substr (earnings_date, 4, 2) || '-' || substr (earnings_date, 1, 2)
            else NULL
            end as earnings_date
        FROM
            EarningDates
    ) AS b ON a.symbol = b.symbol
    LEFT OUTER JOIN AnalystPriceTargets AS c ON a.symbol = c.symbol;

DROP VIEW IF EXISTS OptionData;

CREATE VIEW
	OptionData AS
SELECT
	-- OptionDataYahoo
	a.symbol, 
	a."option-type", 
	DATE(a.expiration_date) as expiration_date, 
	a.strike, 
	a.bid, 
	a.ask, 
	a."contractSymbol",
	a.currency,
	a."lastPrice",
	a.change,
	a."percentChange",
	a.option_open_interest,
	a."contractSize",
	a."lastTradeDate",
	a."impliedVolatility",
	a."inTheMoney",
	a.option_volume,
	-- OptionDataTradingView
	CASE WHEN b.option_osi IS NOT NULL THEN TRUE ELSE FALSE END as has_option_data_tradingview,
	b.delta,
	b.gamma,
	b.iv,
	b.rho,
	b."theoPrice",
	b.theta,
	b.vega,
	b.option,
	b.time,
	b.exchange,
	b.option_osi,
	-- OptionPricingMetrics
	CASE WHEN c.contractSymbol IS NOT NULL THEN TRUE ELSE FALSE END as has_option_pricing_metrics,
	c.days_to_expiration,
	c.premium_option_price,
	c.spread,
    c.spread_ptc,
	c.intrinsic_value,
	c.extrinsic_value,
	c.strike_stock_price_difference,
    c.strike_stock_price_difference_ptc
FROM
	OptionDataYahoo as a
	LEFT OUTER JOIN OptionDataTradingView AS b ON a.contractSymbol = b.option_osi
	-- b.symbol = b.symbol
	-- and b.strike = b.strike
	-- and b.expiration_date = b.expiration_date -- expiration_date in different formats 20250905 vs 2025-09-05 00:00:00.000000	
	-- and b."option-type" = b."option-type" -- option-type in different formats call vs calls
	LEFT OUTER JOIN OptionPricingMetrics as c ON a.contractSymbol = c.contractSymbol;

DROP VIEW IF EXISTS OptionDataMerged;

CREATE VIEW OptionDataMerged AS
SELECT 
	-- Option Data
    a.symbol, 
	a.has_option_data_tradingview,
	a.has_option_pricing_metrics,
	a."option-type", 
	a.strike, 
	a.expiration_date, 
	a.days_to_expiration,
    a.ask, 
	a.bid, 
	a.delta, 
	a.gamma, 
	a.iv, 
	a.rho, 
    a."theoPrice", 
	a.theta, 
	a.vega, 
	a.option, 
	a.time, 
	a.exchange, 
	a.option_osi,
    a."contractSymbol",  
	a.currency, 
	a."lastPrice", 
	a.change, 
	a."percentChange", 
	a.option_open_interest, 
	a."contractSize", 
	a."lastTradeDate", 
	a."impliedVolatility", 
	a."inTheMoney", 
	a.option_volume,
	a.premium_option_price,
	a.spread,
    a.spread_ptc,
	a.intrinsic_value,
	a.extrinsic_value,
	a.strike_stock_price_difference,
    a.strike_stock_price_difference_ptc,

    -- Fundamental Data
	b.has_fundamental_data_dividend_radar,
	b."Company", 
	b."FV", 
	b."Sector", 
	b."No-Years", 
	b."Price", 
	b."Div-Yield", 
	b."5Y-Avg-Yield", 
	b."Current-Div", 
	b."Payouts/-Year", 
	b."Annualized", 
	b."Previous-Div", 
	b."Ex-Date", 
	b."Pay-Date", 
	b."Low", 
	b."High", 
	b."DGR-1Y", 
	b."DGR-3Y", 
	b."DGR-5Y", 
	b."DGR-10Y", 
	b."TTR-1Y", 
	b."TTR-3Y", 
	b."Fair-Value", 
	b."FV-%", 
	b."Streak-Basis", 
	b."Chowder-Number", 
	b."EPS-1Y", 
	b."Revenue-1Y", 
	b."NPM", 
	b."CF/Share", 
	b."ROE", 
	b."Current-R", 
	b."Debt/Capital", 
	b."ROTC", 
	b."P/E", 
	b."P/BV", 
	b."PEG", 
	b."New-Member", 
	b."Industry", 
	b."Classification",
    b."asOfDate", 
	b."periodType", 
	b."currencyCode", 
	b."AccountsPayable", 
	b."AccountsReceivable", 
	b."AccumulatedDepreciation", 
	b."AvailableForSaleSecurities", 
	b."BasicAverageShares", 
	b."BasicEPS", 
	b."BeginningCashPosition", 
	b."CapitalExpenditure", 
	b."CapitalLeaseObligations", 
	b."CapitalStock", 
	b."CashAndCashEquivalents", 
	b."CashCashEquivalentsAndShortTermInvestments", 
	b."CashDividendsPaid", 
	b."CashEquivalents", 
	b."CashFinancial", 
	b."CashFlowFromContinuingFinancingActivities", 
	b."CashFlowFromContinuingInvestingActivities", 
	b."CashFlowFromContinuingOperatingActivities", 
	b."ChangeInAccountPayable", 
	b."ChangeInCashSupplementalAsReported", 
	b."ChangeInInventory", 
	b."ChangeInOtherCurrentAssets", 
	b."ChangeInOtherCurrentLiabilities", 
	b."ChangeInOtherWorkingCapital", 
	b."ChangeInPayable", 
	b."ChangeInPayablesAndAccruedExpense", 
	b."ChangeInReceivables", 
	b."ChangeInWorkingCapital", 
	b."ChangesInAccountReceivables", 
	b."ChangesInCash", 
	b."CommercialPaper", 
	b."CommonStock", 
	b."CommonStockDividendPaid", 
	b."CommonStockEquity", 
	b."CommonStockIssuance", 
	b."CommonStockPayments", 
	b."CostOfRevenue", 
	b."CurrentAssets", 
	b."CurrentCapitalLeaseObligation", 
	b."CurrentDebt", 
	b."CurrentDebtAndCapitalLeaseObligation", 
	b."CurrentDeferredLiabilities", 
	b."CurrentDeferredRevenue", 
	b."CurrentLiabilities", 
	b."DeferredIncomeTax", 
	b."DeferredTax", 
	b."DepreciationAmortizationDepletion", 
	b."DepreciationAndAmortization", 
	b."DilutedAverageShares", 
	b."DilutedEPS", 
	b."DilutedNIAvailtoComStockholders", 
	b."EBIT", 
	b."EBITDA", 
	b."EndCashPosition", 
	b."EnterpriseValue", 
	b."EnterprisesValueEBITDARatio", 
	b."EnterprisesValueRevenueRatio", 
	b."FinancingCashFlow", 
	b."FreeCashFlow", 
	b."GainsLossesNotAffectingRetainedEarnings", 
	b."GrossPPE", 
	b."GrossProfit", 
	b."IncomeTaxPaidSupplementalData", 
	b."IncomeTaxPayable", 
	b."InterestExpense", 
	b."InterestExpenseNonOperating", 
	b."InterestIncome", 
	b."InterestIncomeNonOperating", 
	b."InterestPaidSupplementalData", 
	b."Inventory", 
	b."InvestedCapital", 
	b."InvestingCashFlow", 
	b."InvestmentinFinancialAssets", 
	b."InvestmentsAndAdvances", 
	b."IssuanceOfCapitalStock", 
	b."IssuanceOfDebt", 
	b."LandAndImprovements", 
	b."Leases", 
	b."LongTermCapitalLeaseObligation", 
	b."LongTermDebt", 
	b."LongTermDebtAndCapitalLeaseObligation", 
	b."LongTermDebtIssuance", 
	b."LongTermDebtPayments", 
	b."MachineryFurnitureEquipment", 
	b."MarketCap", 
	b."NetBusinessPurchaseAndSale", 
	b."NetCommonStockIssuance", 
	b."NetDebt", 
	b."NetIncome", 
	b."NetIncomeCommonStockholders", 
	b."NetIncomeContinuousOperations", 
	b."NetIncomeFromContinuingAndDiscontinuedOperation", 
	b."NetIncomeFromContinuingOperationNetMinorityInterest", 
	b."NetIncomeFromContinuingOperations", 
	b."NetIncomeIncludingNoncontrollingInterests", 
	b."NetInterestIncome", 
	b."NetInvestmentPurchaseAndSale", 
	b."NetIssuancePaymentsOfDebt", 
	b."NetLongTermDebtIssuance", 
	b."NetNonOperatingInterestIncomeExpense", 
	b."NetOtherFinancingCharges", 
	b."NetOtherInvestingChanges", 
	b."NetPPE", 
	b."NetPPEPurchaseAndSale", 
	b."NetShortTermDebtIssuance", 
	b."NetTangibleAssets", 
	b."NonCurrentDeferredAssets", 
	b."NonCurrentDeferredTaxesAssets", 
	b."NormalizedEBITDA", 
	b."NormalizedIncome", 
	b."OperatingCashFlow", 
	b."OperatingExpense", 
	b."OperatingIncome", 
	b."OperatingRevenue", 
	b."OrdinarySharesNumber", 
	b."OtherCurrentAssets", 
	b."OtherCurrentBorrowings", 
	b."OtherCurrentLiabilities", 
	b."OtherEquityAdjustments", 
	b."OtherIncomeExpense", 
	b."OtherInvestments", 
	b."OtherNonCashItems", 
	b."OtherNonCurrentAssets", 
	b."OtherNonCurrentLiabilities", 
	b."OtherNonOperatingIncomeExpenses", 
	b."OtherProperties", 
	b."OtherReceivables", 
	b."OtherShortTermInvestments", 
	b."Payables", 
	b."PayablesAndAccruedExpenses", 
	b."PretaxIncome", 
	b."Properties", 
	b."PurchaseOfBusiness", 
	b."PurchaseOfInvestment", 
	b."PurchaseOfPPE", 
	b."Receivables", 
	b."ReconciledCostOfRevenue", 
	b."ReconciledDepreciation", 
	b."RepaymentOfDebt", 
	b."RepurchaseOfCapitalStock", 
	b."ResearchAndDevelopment", 
	b."RetainedEarnings", 
	b."SaleOfInvestment", 
	b."SellingGeneralAndAdministration", 
	b."ShareIssued", 
	b."StockBasedCompensation", 
	b."StockholdersEquity", 
	b."TangibleBookValue", 
	b."TaxEffectOfUnusualItems", 
	b."TaxProvision", 
	b."TaxRateForCalcs", 
	b."TotalAssets", 
	b."TotalCapitalization", 
	b."TotalDebt", 
	b."TotalEquityGrossMinorityInterest", 
	b."TotalExpenses", 
	b."TotalLiabilitiesNetMinorityInterest", 
	b."TotalNonCurrentAssets", 
	b."TotalNonCurrentLiabilitiesNetMinorityInterest", 
	b."TotalOperatingIncomeAsReported", 
	b."TotalRevenue", 
	b."TotalTaxPayable", 
	b."TradeandOtherPayablesNonCurrent", 
	b."TreasurySharesNumber", 
	b."WorkingCapital", 
	b."KeyStats_maxAge", 
	b."KeyStats_priceHint", 
	b."KeyStats_enterpriseValue", 
	b."KeyStats_forwardPE", 
	b."KeyStats_profitMargins", 
	b."KeyStats_floatShares", 
	b."KeyStats_sharesOutstanding", 
	b."KeyStats_sharesShort", 
	b."KeyStats_sharesShortPriorMonth", 
	b."KeyStats_sharesShortPreviousMonthDate", 
	b."KeyStats_dateShortInterest", 
	b."KeyStats_sharesPercentSharesOut", 
	b."KeyStats_heldPercentInsiders", 
	b."KeyStats_heldPercentInstitutions", 
	b."KeyStats_shortRatio", 
	b."KeyStats_shortPercentOfFloat", 
	b."KeyStats_beta", 
	b."KeyStats_impliedSharesOutstanding", 
	b."KeyStats_category", 
	b."KeyStats_bookValue", 
	b."KeyStats_priceToBook", 
	b."KeyStats_fundFamily", 
	b."KeyStats_legalType", 
	b."KeyStats_lastFiscalYearEnd", 
	b."KeyStats_nextFiscalYearEnd", 
	b."KeyStats_mostRecentQuarter", 
	b."KeyStats_earningsQuarterlyGrowth", 
	b."KeyStats_netIncomeToCommon", 
	b."KeyStats_trailingEps", 
	b."KeyStats_forwardEps", 
	b."KeyStats_lastSplitFactor", 
	b."KeyStats_lastSplitDate", 
	b."KeyStats_enterpriseToRevenue", 
	b."KeyStats_enterpriseToEbitda", 
	b."KeyStats_52WeekChange", 
	b."KeyStats_SandP52WeekChange", 
	b."KeyStats_lastDividendValue", 
	b."KeyStats_lastDividendDate", 
	b."KeyStats_latestShareClass", 
	b."KeyStats_leadInvestor", 
	b."Forward_EPS_Growth_Percent", 
	b."Summary_maxAge", 
	b."Summary_priceHint", 
	b."Summary_previousClose", 
	b."Summary_open", 
	b."Summary_dayLow", 
	b."Summary_dayHigh", 
	b."Summary_regularMarketPreviousClose", 
	b."Summary_regularMarketOpen", 
	b."Summary_regularMarketDayLow", 
	b."Summary_regularMarketDayHigh", 
	b."Summary_dividendRate", 
	b."Summary_dividendYield", 
	b."Summary_exDividendDate", 
	b."Summary_payoutRatio", 
	b."Summary_fiveYearAvgDividendYield", 
	b."Summary_beta", 
	b."Summary_trailingPE", 
	b."Summary_forwardPE", 
	b."Summary_volume", 
	b."Summary_regularMarketVolume", 
	b."Summary_averageVolume", 
	b."Summary_averageVolume10days", 
	b."Summary_averageDailyVolume10Day", 
	b."Summary_bid", 
	b."Summary_ask", 
	b."Summary_bidSize", 
	b."Summary_askSize", 
	b."Summary_marketCap", 
	b."Summary_fiftyTwoWeekLow", 
	b."Summary_fiftyTwoWeekHigh", 
	b."Summary_priceToSalesTrailing12Months", 
	b."Summary_fiftyDayAverage", 
	b."Summary_twoHundredDayAverage", 
	b."Summary_trailingAnnualDividendRate", 
	b."Summary_trailingAnnualDividendYield", 
	b."Summary_currency", 
	b."Summary_fromCurrency", 
	b."Summary_toCurrency", 
	b."Summary_lastMarket", 
	b."Summary_coinMarketCapLink", 
	b."Summary_algorithm", 
	b."Summary_tradeable", 
	b."FinData_maxAge", 
	b."FinData_currentPrice", 
	b."FinData_targetHighPrice", 
	b."FinData_targetLowPrice", 
	b."FinData_targetMeanPrice", 
	b."FinData_targetMedianPrice", 
	b."FinData_recommendationMean", 
	b."FinData_recommendationKey", 
	b."FinData_numberOfAnalystOpinions", 
	b."FinData_totalCash", 
	b."FinData_totalCashPerShare", 
	b."FinData_ebitda", 
	b."FinData_totalDebt", 
	b."FinData_quickRatio", 
	b."FinData_currentRatio", 
	b."FinData_totalRevenue", 
	b."FinData_debtToEquity", 
	b."FinData_revenuePerShare", 
	b."FinData_returnOnAssets", 
	b."FinData_returnOnEquity", 
	b."FinData_grossProfits", 
	b."FinData_freeCashflow", 
	b."FinData_operatingCashflow", 
	b."FinData_earningsGrowth", 
	b."FinData_revenueGrowth", 
	b."FinData_grossMargins", 
	b."FinData_ebitdaMargins", 
	b."FinData_operatingMargins", 
	b."FinData_profitMargins", 
	b."FinData_financialCurrency", 
	b."PE_Ratio_Calc", 
	b."PS_Ratio", 
	b."DebtToMarketCap", 
	b."EV_EBITDA_Approx",

    -- Stock Data
	CASE WHEN c.symbol IS NOT NULL THEN TRUE ELSE FALSE END as has_stock_data,
	c.has_earnings_date,
	c.has_analyst_price_target,
	c.live_stock_price,
    c.price_source,
    c.live_price_timestamp,
    c.earnings_date,
	c.days_to_earnings,
    c.analyst_mean_target,

    -- Technical Indicators
	CASE WHEN d.symbol IS NOT NULL THEN TRUE ELSE FALSE END as has_technical_indicators,
    d."Recommend.Other", 
	d."Recommend.All", 
	d."Recommend.MA", 
	d."RSI", 
	d."RSI[1]", 
	d."Stoch.K", 
	d."Stoch.D", 
	d."Stoch.K[1]", 
	d."Stoch.D[1]", 
	d."CCI20", 
	d."CCI20[1]", 
	d."ADX", 
	d."ADX+DI", 
	d."ADX-DI", 
	d."ADX+DI[1]", 
	d."ADX-DI[1]", 
	d."AO", 
	d."AO[1]", 
	d."Mom", 
	d."Mom[1]", 
	d."MACD.macd", 
	d."MACD.signal", 
	d."Rec.Stoch.RSI", 
	d."Stoch.RSI.K", 
	d."Rec.WR", 
	d."W.R", 
	d."Rec.BBPower", 
	d."BBPower", 
	d."Rec.UO", 
	d."UO", 
	d.close, 
	d."EMA5", 
	d."SMA5", 
	d."EMA10", 
	d."SMA10", 
	d."EMA20", 
	d."SMA20", 
	d."EMA30", 
	d."SMA30", 
	d."EMA50", 
	d."SMA50", 
	d."EMA100", 
	d."SMA100", 
	d."EMA200", 
	d."SMA200", 
	d."Rec.Ichimoku", 
	d."Ichimoku.BLine", 
	d."Rec.VWMA", 
	d."VWMA", 
	d."Rec.HullMA9", 
	d."HullMA9", 
	d."Pivot.M.Classic.S3", 
	d."Pivot.M.Classic.S2", 
	d."Pivot.M.Classic.S1", 
	d."Pivot.M.Classic.Middle", 
	d."Pivot.M.Classic.R1", 
	d."Pivot.M.Classic.R2", 
	d."Pivot.M.Classic.R3", 
	d."Pivot.M.Fibonacci.S3", 
	d."Pivot.M.Fibonacci.S2", 
	d."Pivot.M.Fibonacci.S1", 
	d."Pivot.M.Fibonacci.Middle", 
	d."Pivot.M.Fibonacci.R1", 
	d."Pivot.M.Fibonacci.R2", 
	d."Pivot.M.Fibonacci.R3", 
	d."Pivot.M.Camarilla.S3", 
	d."Pivot.M.Camarilla.S2", 
	d."Pivot.M.Camarilla.S1", 
	d."Pivot.M.Camarilla.Middle", 
	d."Pivot.M.Camarilla.R1", 
	d."Pivot.M.Camarilla.R2", 
	d."Pivot.M.Camarilla.R3", 
	d."Pivot.M.Woodie.S3", 
	d."Pivot.M.Woodie.S2", 
	d."Pivot.M.Woodie.S1", 
	d."Pivot.M.Woodie.Middle", 
	d."Pivot.M.Woodie.R1", 
	d."Pivot.M.Woodie.R2", 
	d."Pivot.M.Woodie.R3", 
	d."Pivot.M.Demark.S1", 
	d."Pivot.M.Demark.Middle", 
	d."Pivot.M.Demark.R1", 
	d.open, 
	d."P.SAR", 
	d."BB.lower", 
	d."BB.upper", 
	d."AO[2]", 
	d.volume, 
	d.change, 
	d.low, 
	d.high, 
	d.recommendation, 
	d.recommendation_buy_amount, 
	d.recommendation_neutral_amount, 
	d.recommendation_sell_amount,

	-- Additional calculated fields
	ROUND(c.analyst_mean_target - d.close,2) as "target-close$",
	ROUND(ROUND(c.analyst_mean_target - d.close,2) / d.close * 100, 2) as "target-close%",
	d.close * a.iv * sqrt(a.days_to_expiration / 365) as expected_move

FROM 
    OptionData AS a
JOIN 
    FundamentalData as b
ON a.symbol = b.symbol
LEFT OUTER JOIN 
    StockData as c
ON a.symbol = c.symbol
LEFT OUTER JOIN 
    TechnicalIndicators as d
ON a.symbol = d.symbol;
