DROP TABLE IF EXISTS "FundamentalDataYahoo";
CREATE TABLE "FundamentalDataYahoo" (
	symbol TEXT, 
	"asOfDate" DATETIME, 
	"periodType" TEXT, 
	"currencyCode" TEXT, 
	"AccountsPayable" FLOAT, 
	"AccountsReceivable" FLOAT, 
	"AccruedInterestReceivable" FLOAT, 
	"AccumulatedDepreciation" FLOAT, 
	"AdditionalPaidInCapital" FLOAT, 
	"AllowanceForDoubtfulAccountsReceivable" FLOAT, 
	"Amortization" FLOAT, 
	"AmortizationCashFlow" FLOAT, 
	"AmortizationOfIntangibles" FLOAT, 
	"AmortizationOfIntangiblesIncomeStatement" FLOAT, 
	"AmortizationOfSecurities" FLOAT, 
	"AssetImpairmentCharge" FLOAT, 
	"AssetsHeldForSaleCurrent" FLOAT, 
	"AvailableForSaleSecurities" FLOAT, 
	"AverageDilutionEarnings" FLOAT, 
	"BasicAverageShares" FLOAT, 
	"BasicEPS" FLOAT, 
	"BeginningCashPosition" FLOAT, 
	"BuildingsAndImprovements" FLOAT, 
	"CapitalExpenditure" FLOAT, 
	"CapitalExpenditureReported" FLOAT, 
	"CapitalLeaseObligations" FLOAT, 
	"CapitalStock" FLOAT, 
	"CashAndCashEquivalents" FLOAT, 
	"CashCashEquivalentsAndShortTermInvestments" FLOAT, 
	"CashDividendsPaid" FLOAT, 
	"CashEquivalents" FLOAT, 
	"CashFinancial" FLOAT, 
	"CashFlowFromContinuingFinancingActivities" FLOAT, 
	"CashFlowFromContinuingInvestingActivities" FLOAT, 
	"CashFlowFromContinuingOperatingActivities" FLOAT, 
	"CashFlowFromDiscontinuedOperation" FLOAT, 
	"CashFlowsfromusedinOperatingActivitiesDirect" FLOAT, 
	"CashFromDiscontinuedFinancingActivities" FLOAT, 
	"CashFromDiscontinuedInvestingActivities" FLOAT, 
	"CashFromDiscontinuedOperatingActivities" FLOAT, 
	"ChangeInAccountPayable" FLOAT, 
	"ChangeInAccruedExpense" FLOAT, 
	"ChangeInCashSupplementalAsReported" FLOAT, 
	"ChangeInDividendPayable" FLOAT, 
	"ChangeInIncomeTaxPayable" FLOAT, 
	"ChangeInInterestPayable" FLOAT, 
	"ChangeInInventory" FLOAT, 
	"ChangeInOtherCurrentAssets" FLOAT, 
	"ChangeInOtherCurrentLiabilities" FLOAT, 
	"ChangeInOtherWorkingCapital" FLOAT, 
	"ChangeInPayable" FLOAT, 
	"ChangeInPayablesAndAccruedExpense" FLOAT, 
	"ChangeInPrepaidAssets" FLOAT, 
	"ChangeInReceivables" FLOAT, 
	"ChangeInTaxPayable" FLOAT, 
	"ChangeInWorkingCapital" FLOAT, 
	"ChangesInAccountReceivables" FLOAT, 
	"ChangesInCash" FLOAT, 
	"ClassesofCashPayments" FLOAT, 
	"ClassesofCashReceiptsfromOperatingActivities" FLOAT, 
	"CommercialPaper" FLOAT, 
	"CommonStock" FLOAT, 
	"CommonStockDividendPaid" FLOAT, 
	"CommonStockEquity" FLOAT, 
	"CommonStockIssuance" FLOAT, 
	"CommonStockPayments" FLOAT, 
	"ConstructionInProgress" FLOAT, 
	"CostOfRevenue" FLOAT, 
	"CurrentAccruedExpenses" FLOAT, 
	"CurrentAssets" FLOAT, 
	"CurrentCapitalLeaseObligation" FLOAT, 
	"CurrentDebt" FLOAT, 
	"CurrentDebtAndCapitalLeaseObligation" FLOAT, 
	"CurrentDeferredAssets" FLOAT, 
	"CurrentDeferredLiabilities" FLOAT, 
	"CurrentDeferredRevenue" FLOAT, 
	"CurrentDeferredTaxesAssets" FLOAT, 
	"CurrentDeferredTaxesLiabilities" FLOAT, 
	"CurrentLiabilities" FLOAT, 
	"CurrentNotesPayable" FLOAT, 
	"CurrentProvisions" FLOAT, 
	"DeferredIncomeTax" FLOAT, 
	"DeferredTax" FLOAT, 
	"DefinedPensionBenefit" FLOAT, 
	"Depletion" FLOAT, 
	"DepletionIncomeStatement" FLOAT, 
	"Depreciation" FLOAT, 
	"DepreciationAmortizationDepletion" FLOAT, 
	"DepreciationAmortizationDepletionIncomeStatement" FLOAT, 
	"DepreciationAndAmortization" FLOAT, 
	"DepreciationAndAmortizationInIncomeStatement" FLOAT, 
	"DepreciationIncomeStatement" FLOAT, 
	"DerivativeProductLiabilities" FLOAT, 
	"DilutedAverageShares" FLOAT, 
	"DilutedEPS" FLOAT, 
	"DilutedNIAvailtoComStockholders" FLOAT, 
	"DividendPaidCFO" FLOAT, 
	"DividendReceivedCFO" FLOAT, 
	"DividendsPayable" FLOAT, 
	"DividendsReceivedCFI" FLOAT, 
	"DuefromRelatedPartiesCurrent" FLOAT, 
	"DuefromRelatedPartiesNonCurrent" FLOAT, 
	"DuetoRelatedPartiesCurrent" FLOAT, 
	"DuetoRelatedPartiesNonCurrent" FLOAT, 
	"EBIT" FLOAT, 
	"EBITDA" FLOAT, 
	"EarningsFromEquityInterest" FLOAT, 
	"EarningsFromEquityInterestNetOfTax" FLOAT, 
	"EarningsLossesFromEquityInvestments" FLOAT, 
	"EffectOfExchangeRateChanges" FLOAT, 
	"EmployeeBenefits" FLOAT, 
	"EndCashPosition" FLOAT, 
	"EnterpriseValue" FLOAT, 
	"EnterprisesValueEBITDARatio" FLOAT, 
	"EnterprisesValueRevenueRatio" FLOAT, 
	"ExcessTaxBenefitFromStockBasedCompensation" FLOAT, 
	"ExciseTaxes" FLOAT, 
	"FinancialAssets" FLOAT, 
	"FinancialAssetsDesignatedasFairValueThroughProfitorLossTotal" FLOAT, 
	"FinancingCashFlow" FLOAT, 
	"FinishedGoods" FLOAT, 
	"FixedAssetsRevaluationReserve" FLOAT, 
	"ForeignCurrencyTranslationAdjustments" FLOAT, 
	"FreeCashFlow" FLOAT, 
	"GainLossOnInvestmentSecurities" FLOAT, 
	"GainLossOnSaleOfBusiness" FLOAT, 
	"GainLossOnSaleOfPPE" FLOAT, 
	"GainOnSaleOfBusiness" FLOAT, 
	"GainOnSaleOfPPE" FLOAT, 
	"GainOnSaleOfSecurity" FLOAT, 
	"GainsLossesNotAffectingRetainedEarnings" FLOAT, 
	"GeneralAndAdministrativeExpense" FLOAT, 
	"GeneralPartnershipCapital" FLOAT, 
	"Goodwill" FLOAT, 
	"GoodwillAndOtherIntangibleAssets" FLOAT, 
	"GrossAccountsReceivable" FLOAT, 
	"GrossPPE" FLOAT, 
	"GrossProfit" FLOAT, 
	"HedgingAssetsCurrent" FLOAT, 
	"HeldToMaturitySecurities" FLOAT, 
	"ImpairmentOfCapitalAssets" FLOAT, 
	"IncomeTaxPaidSupplementalData" FLOAT, 
	"IncomeTaxPayable" FLOAT, 
	"InsuranceAndClaims" FLOAT, 
	"InterestExpense" FLOAT, 
	"InterestExpenseNonOperating" FLOAT, 
	"InterestIncome" FLOAT, 
	"InterestIncomeNonOperating" FLOAT, 
	"InterestPaidCFF" FLOAT, 
	"InterestPaidCFO" FLOAT, 
	"InterestPaidSupplementalData" FLOAT, 
	"InterestPayable" FLOAT, 
	"InterestReceivedCFI" FLOAT, 
	"InterestReceivedCFO" FLOAT, 
	"InventoriesAdjustmentsAllowances" FLOAT, 
	"Inventory" FLOAT, 
	"InvestedCapital" FLOAT, 
	"InvestingCashFlow" FLOAT, 
	"InvestmentProperties" FLOAT, 
	"InvestmentinFinancialAssets" FLOAT, 
	"InvestmentsAndAdvances" FLOAT, 
	"InvestmentsInOtherVenturesUnderEquityMethod" FLOAT, 
	"InvestmentsinAssociatesatCost" FLOAT, 
	"InvestmentsinJointVenturesatCost" FLOAT, 
	"InvestmentsinSubsidiariesatCost" FLOAT, 
	"IssuanceOfCapitalStock" FLOAT, 
	"IssuanceOfDebt" FLOAT, 
	"LandAndImprovements" FLOAT, 
	"Leases" FLOAT, 
	"LiabilitiesHeldforSaleNonCurrent" FLOAT, 
	"LimitedPartnershipCapital" FLOAT, 
	"LineOfCredit" FLOAT, 
	"LoansReceivable" FLOAT, 
	"LongTermCapitalLeaseObligation" FLOAT, 
	"LongTermDebt" FLOAT, 
	"LongTermDebtAndCapitalLeaseObligation" FLOAT, 
	"LongTermDebtIssuance" FLOAT, 
	"LongTermDebtPayments" FLOAT, 
	"LongTermEquityInvestment" FLOAT, 
	"LongTermProvisions" FLOAT, 
	"MachineryFurnitureEquipment" FLOAT, 
	"MarketCap" FLOAT, 
	"MinimumPensionLiabilities" FLOAT, 
	"MinorityInterest" FLOAT, 
	"MinorityInterests" FLOAT, 
	"NetBusinessPurchaseAndSale" FLOAT, 
	"NetCommonStockIssuance" FLOAT, 
	"NetDebt" FLOAT, 
	"NetForeignCurrencyExchangeGainLoss" FLOAT, 
	"NetIncome" FLOAT, 
	"NetIncomeCommonStockholders" FLOAT, 
	"NetIncomeContinuousOperations" FLOAT, 
	"NetIncomeDiscontinuousOperations" FLOAT, 
	"NetIncomeExtraordinary" FLOAT, 
	"NetIncomeFromContinuingAndDiscontinuedOperation" FLOAT, 
	"NetIncomeFromContinuingOperationNetMinorityInterest" FLOAT, 
	"NetIncomeFromContinuingOperations" FLOAT, 
	"NetIncomeFromTaxLossCarryforward" FLOAT, 
	"NetIncomeIncludingNoncontrollingInterests" FLOAT, 
	"NetIntangiblesPurchaseAndSale" FLOAT, 
	"NetInterestIncome" FLOAT, 
	"NetInvestmentPropertiesPurchaseAndSale" FLOAT, 
	"NetInvestmentPurchaseAndSale" FLOAT, 
	"NetIssuancePaymentsOfDebt" FLOAT, 
	"NetLongTermDebtIssuance" FLOAT, 
	"NetNonOperatingInterestIncomeExpense" FLOAT, 
	"NetOtherFinancingCharges" FLOAT, 
	"NetOtherInvestingChanges" FLOAT, 
	"NetPPE" FLOAT, 
	"NetPPEPurchaseAndSale" FLOAT, 
	"NetPreferredStockIssuance" FLOAT, 
	"NetShortTermDebtIssuance" FLOAT, 
	"NetTangibleAssets" FLOAT, 
	"NonCurrentAccountsReceivable" FLOAT, 
	"NonCurrentAccruedExpenses" FLOAT, 
	"NonCurrentDeferredAssets" FLOAT, 
	"NonCurrentDeferredLiabilities" FLOAT, 
	"NonCurrentDeferredRevenue" FLOAT, 
	"NonCurrentDeferredTaxesAssets" FLOAT, 
	"NonCurrentDeferredTaxesLiabilities" FLOAT, 
	"NonCurrentNoteReceivables" FLOAT, 
	"NonCurrentPensionAndOtherPostretirementBenefitPlans" FLOAT, 
	"NonCurrentPrepaidAssets" FLOAT, 
	"NormalizedEBITDA" FLOAT, 
	"NormalizedIncome" FLOAT, 
	"NotesReceivable" FLOAT, 
	"OperatingCashFlow" FLOAT, 
	"OperatingExpense" FLOAT, 
	"OperatingGainsLosses" FLOAT, 
	"OperatingIncome" FLOAT, 
	"OperatingRevenue" FLOAT, 
	"OrdinarySharesNumber" FLOAT, 
	"OtherCashAdjustmentInsideChangeinCash" FLOAT, 
	"OtherCashAdjustmentOutsideChangeinCash" FLOAT, 
	"OtherCashPaymentsfromOperatingActivities" FLOAT, 
	"OtherCashReceiptsfromOperatingActivities" FLOAT, 
	"OtherCurrentAssets" FLOAT, 
	"OtherCurrentBorrowings" FLOAT, 
	"OtherCurrentLiabilities" FLOAT, 
	"OtherEquityAdjustments" FLOAT, 
	"OtherEquityInterest" FLOAT, 
	"OtherGandA" FLOAT, 
	"OtherIncomeExpense" FLOAT, 
	"OtherIntangibleAssets" FLOAT, 
	"OtherInventories" FLOAT, 
	"OtherInvestments" FLOAT, 
	"OtherNonCashItems" FLOAT, 
	"OtherNonCurrentAssets" FLOAT, 
	"OtherNonCurrentLiabilities" FLOAT, 
	"OtherNonOperatingIncomeExpenses" FLOAT, 
	"OtherOperatingExpenses" FLOAT, 
	"OtherPayable" FLOAT, 
	"OtherProperties" FLOAT, 
	"OtherReceivables" FLOAT, 
	"OtherShortTermInvestments" FLOAT, 
	"OtherSpecialCharges" FLOAT, 
	"OtherTaxes" FLOAT, 
	"OtherunderPreferredStockDividend" FLOAT, 
	"Payables" FLOAT, 
	"PayablesAndAccruedExpenses" FLOAT, 
	"PaymentsonBehalfofEmployees" FLOAT, 
	"PensionAndEmployeeBenefitExpense" FLOAT, 
	"PensionandOtherPostRetirementBenefitPlansCurrent" FLOAT, 
	"PreferredSecuritiesOutsideStockEquity" FLOAT, 
	"PreferredSharesNumber" FLOAT, 
	"PreferredStock" FLOAT, 
	"PreferredStockDividendPaid" FLOAT, 
	"PreferredStockDividends" FLOAT, 
	"PreferredStockEquity" FLOAT, 
	"PreferredStockIssuance" FLOAT, 
	"PreferredStockPayments" FLOAT, 
	"PrepaidAssets" FLOAT, 
	"PretaxIncome" FLOAT, 
	"ProceedsFromStockOptionExercised" FLOAT, 
	"Properties" FLOAT, 
	"ProvisionForDoubtfulAccounts" FLOAT, 
	"ProvisionandWriteOffofAssets" FLOAT, 
	"PurchaseOfBusiness" FLOAT, 
	"PurchaseOfIntangibles" FLOAT, 
	"PurchaseOfInvestment" FLOAT, 
	"PurchaseOfInvestmentProperties" FLOAT, 
	"PurchaseOfPPE" FLOAT, 
	"RawMaterials" FLOAT, 
	"Receivables" FLOAT, 
	"ReceivablesAdjustmentsAllowances" FLOAT, 
	"ReconciledCostOfRevenue" FLOAT, 
	"ReconciledDepreciation" FLOAT, 
	"RentAndLandingFees" FLOAT, 
	"RentExpenseSupplemental" FLOAT, 
	"RepaymentOfDebt" FLOAT, 
	"RepurchaseOfCapitalStock" FLOAT, 
	"ResearchAndDevelopment" FLOAT, 
	"RestrictedCash" FLOAT, 
	"RestructuringAndMergernAcquisition" FLOAT, 
	"RetainedEarnings" FLOAT, 
	"SalariesAndWages" FLOAT, 
	"SaleOfBusiness" FLOAT, 
	"SaleOfIntangibles" FLOAT, 
	"SaleOfInvestment" FLOAT, 
	"SaleOfInvestmentProperties" FLOAT, 
	"SaleOfPPE" FLOAT, 
	"SecuritiesAmortization" FLOAT, 
	"SellingAndMarketingExpense" FLOAT, 
	"SellingGeneralAndAdministration" FLOAT, 
	"ShareIssued" FLOAT, 
	"ShortTermDebtIssuance" FLOAT, 
	"ShortTermDebtPayments" FLOAT, 
	"SpecialIncomeCharges" FLOAT, 
	"StockBasedCompensation" FLOAT, 
	"StockholdersEquity" FLOAT, 
	"TangibleBookValue" FLOAT, 
	"TaxEffectOfUnusualItems" FLOAT, 
	"TaxProvision" FLOAT, 
	"TaxRateForCalcs" FLOAT, 
	"TaxesReceivable" FLOAT, 
	"TaxesRefundPaid" FLOAT, 
	"TotalAssets" FLOAT, 
	"TotalCapitalization" FLOAT, 
	"TotalDebt" FLOAT, 
	"TotalEquityGrossMinorityInterest" FLOAT, 
	"TotalExpenses" FLOAT, 
	"TotalLiabilitiesNetMinorityInterest" FLOAT, 
	"TotalNonCurrentAssets" FLOAT, 
	"TotalNonCurrentLiabilitiesNetMinorityInterest" FLOAT, 
	"TotalOperatingIncomeAsReported" FLOAT, 
	"TotalOtherFinanceCost" FLOAT, 
	"TotalPartnershipCapital" FLOAT, 
	"TotalRevenue" FLOAT, 
	"TotalTaxPayable" FLOAT, 
	"TotalUnusualItems" FLOAT, 
	"TotalUnusualItemsExcludingGoodwill" FLOAT, 
	"TradeandOtherPayablesNonCurrent" FLOAT, 
	"TradingSecurities" FLOAT, 
	"TreasurySharesNumber" FLOAT, 
	"TreasuryStock" FLOAT, 
	"UnrealizedGainLoss" FLOAT, 
	"UnrealizedGainLossOnInvestmentSecurities" FLOAT, 
	"WorkInProcess" FLOAT, 
	"WorkingCapital" FLOAT, 
	"WriteOff" FLOAT, 
	"InterestPaidDirect" FLOAT, 
	"InterestReceivedDirect" FLOAT, 
	"PaymentstoSuppliersforGoodsandServices" FLOAT, 
	"ReceiptsfromCustomers" FLOAT, 
	"RestrictedCommonStock" FLOAT, 
	"TaxesRefundPaidDirect" FLOAT, 
	"KeyStats_maxAge" FLOAT, 
	"KeyStats_priceHint" FLOAT, 
	"KeyStats_enterpriseValue" FLOAT, 
	"KeyStats_forwardPE" FLOAT, 
	"KeyStats_profitMargins" FLOAT, 
	"KeyStats_floatShares" FLOAT, 
	"KeyStats_sharesOutstanding" FLOAT, 
	"KeyStats_sharesShort" FLOAT, 
	"KeyStats_sharesShortPriorMonth" FLOAT, 
	"KeyStats_sharesShortPreviousMonthDate" TEXT, 
	"KeyStats_dateShortInterest" TEXT, 
	"KeyStats_sharesPercentSharesOut" FLOAT, 
	"KeyStats_heldPercentInsiders" FLOAT, 
	"KeyStats_heldPercentInstitutions" FLOAT, 
	"KeyStats_shortRatio" FLOAT, 
	"KeyStats_shortPercentOfFloat" FLOAT, 
	"KeyStats_beta" FLOAT, 
	"KeyStats_impliedSharesOutstanding" FLOAT, 
	"KeyStats_category" TEXT, 
	"KeyStats_bookValue" FLOAT, 
	"KeyStats_priceToBook" FLOAT, 
	"KeyStats_fundFamily" TEXT, 
	"KeyStats_legalType" TEXT, 
	"KeyStats_lastFiscalYearEnd" TEXT, 
	"KeyStats_nextFiscalYearEnd" TEXT, 
	"KeyStats_mostRecentQuarter" TEXT, 
	"KeyStats_earningsQuarterlyGrowth" FLOAT, 
	"KeyStats_netIncomeToCommon" FLOAT, 
	"KeyStats_trailingEps" FLOAT, 
	"KeyStats_forwardEps" FLOAT, 
	"KeyStats_lastSplitFactor" TEXT, 
	"KeyStats_lastSplitDate" TEXT, 
	"KeyStats_enterpriseToRevenue" FLOAT, 
	"KeyStats_enterpriseToEbitda" FLOAT, 
	"KeyStats_52WeekChange" FLOAT, 
	"KeyStats_SandP52WeekChange" FLOAT, 
	"KeyStats_lastDividendValue" FLOAT, 
	"KeyStats_lastDividendDate" FLOAT, 
	"KeyStats_latestShareClass" FLOAT, 
	"KeyStats_leadInvestor" FLOAT, 
	"Forward_EPS_Growth_Percent" FLOAT, 
	"Summary_maxAge" FLOAT, 
	"Summary_priceHint" FLOAT, 
	"Summary_previousClose" FLOAT, 
	"Summary_open" FLOAT, 
	"Summary_dayLow" FLOAT, 
	"Summary_dayHigh" FLOAT, 
	"Summary_regularMarketPreviousClose" FLOAT, 
	"Summary_regularMarketOpen" FLOAT, 
	"Summary_regularMarketDayLow" FLOAT, 
	"Summary_regularMarketDayHigh" FLOAT, 
	"Summary_dividendRate" FLOAT, 
	"Summary_dividendYield" FLOAT, 
	"Summary_exDividendDate" TEXT, 
	"Summary_payoutRatio" FLOAT, 
	"Summary_fiveYearAvgDividendYield" FLOAT, 
	"Summary_beta" FLOAT, 
	"Summary_trailingPE" FLOAT, 
	"Summary_forwardPE" FLOAT, 
	"Summary_volume" FLOAT, 
	"Summary_regularMarketVolume" FLOAT, 
	"Summary_averageVolume" FLOAT, 
	"Summary_averageVolume10days" FLOAT, 
	"Summary_averageDailyVolume10Day" FLOAT, 
	"Summary_bid" FLOAT, 
	"Summary_ask" FLOAT, 
	"Summary_bidSize" FLOAT, 
	"Summary_askSize" FLOAT, 
	"Summary_marketCap" FLOAT, 
	"Summary_fiftyTwoWeekLow" FLOAT, 
	"Summary_fiftyTwoWeekHigh" FLOAT, 
	"Summary_allTimeHigh" FLOAT, 
	"Summary_allTimeLow" FLOAT, 
	"Summary_priceToSalesTrailing12Months" FLOAT, 
	"Summary_fiftyDayAverage" FLOAT, 
	"Summary_twoHundredDayAverage" FLOAT, 
	"Summary_trailingAnnualDividendRate" FLOAT, 
	"Summary_trailingAnnualDividendYield" FLOAT, 
	"Summary_currency" TEXT, 
	"Summary_fromCurrency" FLOAT, 
	"Summary_toCurrency" FLOAT, 
	"Summary_lastMarket" FLOAT, 
	"Summary_coinMarketCapLink" FLOAT, 
	"Summary_algorithm" FLOAT, 
	"Summary_tradeable" TEXT, 
	"FinData_maxAge" FLOAT, 
	"FinData_currentPrice" FLOAT, 
	"FinData_targetHighPrice" FLOAT, 
	"FinData_targetLowPrice" FLOAT, 
	"FinData_targetMeanPrice" FLOAT, 
	"FinData_targetMedianPrice" FLOAT, 
	"FinData_recommendationMean" FLOAT, 
	"FinData_recommendationKey" TEXT, 
	"FinData_numberOfAnalystOpinions" FLOAT, 
	"FinData_totalCash" FLOAT, 
	"FinData_totalCashPerShare" FLOAT, 
	"FinData_ebitda" FLOAT, 
	"FinData_totalDebt" FLOAT, 
	"FinData_quickRatio" FLOAT, 
	"FinData_currentRatio" FLOAT, 
	"FinData_totalRevenue" FLOAT, 
	"FinData_debtToEquity" FLOAT, 
	"FinData_revenuePerShare" FLOAT, 
	"FinData_returnOnAssets" FLOAT, 
	"FinData_returnOnEquity" FLOAT, 
	"FinData_grossProfits" FLOAT, 
	"FinData_freeCashflow" FLOAT, 
	"FinData_operatingCashflow" FLOAT, 
	"FinData_earningsGrowth" FLOAT, 
	"FinData_revenueGrowth" FLOAT, 
	"FinData_grossMargins" FLOAT, 
	"FinData_ebitdaMargins" FLOAT, 
	"FinData_operatingMargins" FLOAT, 
	"FinData_profitMargins" FLOAT, 
	"FinData_financialCurrency" TEXT, 
	"KeyStats_ytdReturn" FLOAT, 
	"KeyStats_beta3Year" FLOAT, 
	"KeyStats_totalAssets" FLOAT, 
	"KeyStats_yield" FLOAT, 
	"KeyStats_fundInceptionDate" TEXT, 
	"KeyStats_threeYearAverageReturn" FLOAT, 
	"KeyStats_fiveYearAverageReturn" FLOAT, 
	"Summary_yield" FLOAT, 
	"Summary_totalAssets" FLOAT, 
	"Summary_navPrice" FLOAT
);
DROP VIEW IF EXISTS OptionDataMerged;
CREATE VIEW OptionDataMerged AS
SELECT 
	-- Option Data
    a.symbol, 
	a.has_option_data_tradingview,
	a.has_option_pricing_metrics,
	a."option-type", 
	a.strike, 
	a.expiration_date, 
	a.days_to_expiration,
    a.ask, 
	a.bid, 
	a.delta, 
	a.gamma, 
	a.iv, 
	a.rho, 
    a."theoPrice", 
	a.theta, 
	a.vega, 
	a.option, 
	a.time, 
	a.exchange, 
	a.option_osi,
    a."contractSymbol",  
	a.currency, 
	a."lastPrice", 
	a.change, 
	a."percentChange", 
	a.option_open_interest, 
	a."contractSize", 
	a."lastTradeDate", 
	a."impliedVolatility", 
	a."inTheMoney", 
	a.option_volume,
	a.premium_option_price,
	a.spread,
    a.spread_ptc,
	a.intrinsic_value,
	a.extrinsic_value,
	a.strike_stock_price_difference,
    a.strike_stock_price_difference_ptc,

    -- Fundamental Data
	b.has_fundamental_data_dividend_radar,
	b."Company", 
	b."FV", 
	b."Sector", 
	b."No-Years", 
	b."Price", 
	b."Div-Yield", 
	b."5Y-Avg-Yield", 
	b."Current-Div", 
	b."Payouts/-Year", 
	b."Annualized", 
	b."Previous-Div", 
	b."Ex-Date", 
	b."Pay-Date", 
	b."Low", 
	b."High", 
	b."DGR-1Y", 
	b."DGR-3Y", 
	b."DGR-5Y", 
	b."DGR-10Y", 
	b."TTR-1Y", 
	b."TTR-3Y", 
	b."Fair-Value", 
	b."FV-%", 
	b."Streak-Basis", 
	b."Chowder-Number", 
	b."EPS-1Y", 
	b."Revenue-1Y", 
	b."NPM", 
	b."CF/Share", 
	b."ROE", 
	b."Current-R", 
	b."Debt/Capital", 
	b."ROTC", 
	b."P/E", 
	b."P/BV", 
	b."PEG", 
	b."New-Member", 
	b."Industry", 
	b."Classification",
    b."asOfDate", 
	b."periodType", 
	b."currencyCode", 
	b."AccountsPayable", 
	b."AccountsReceivable", 
	b."AccruedInterestReceivable", 
	b."AccumulatedDepreciation", 
	b."AdditionalPaidInCapital", 
	b."AllowanceForDoubtfulAccountsReceivable", 
	b."Amortization", 
	b."AmortizationCashFlow", 
	b."AmortizationOfIntangibles", 
	b."AmortizationOfIntangiblesIncomeStatement", 
	b."AmortizationOfSecurities", 
	b."AssetImpairmentCharge", 
	b."AssetsHeldForSaleCurrent", 
	b."AvailableForSaleSecurities", 
	b."AverageDilutionEarnings", 
	b."BasicAverageShares", 
	b."BasicEPS", 
	b."BeginningCashPosition", 
	b."BuildingsAndImprovements", 
	b."CapitalExpenditure", 
	b."CapitalExpenditureReported", 
	b."CapitalLeaseObligations", 
	b."CapitalStock", 
	b."CashAndCashEquivalents", 
	b."CashCashEquivalentsAndShortTermInvestments", 
	b."CashDividendsPaid", 
	b."CashEquivalents", 
	b."CashFinancial", 
	b."CashFlowFromContinuingFinancingActivities", 
	b."CashFlowFromContinuingInvestingActivities", 
	b."CashFlowFromContinuingOperatingActivities", 
	b."CashFlowFromDiscontinuedOperation", 
	b."CashFlowsfromusedinOperatingActivitiesDirect", 
	b."CashFromDiscontinuedFinancingActivities", 
	b."CashFromDiscontinuedInvestingActivities", 
	b."CashFromDiscontinuedOperatingActivities", 
	b."ChangeInAccountPayable", 
	b."ChangeInAccruedExpense", 
	b."ChangeInCashSupplementalAsReported", 
	b."ChangeInDividendPayable", 
	b."ChangeInIncomeTaxPayable", 
	b."ChangeInInterestPayable", 
	b."ChangeInInventory", 
	b."ChangeInOtherCurrentAssets", 
	b."ChangeInOtherCurrentLiabilities", 
	b."ChangeInOtherWorkingCapital", 
	b."ChangeInPayable", 
	b."ChangeInPayablesAndAccruedExpense", 
	b."ChangeInPrepaidAssets", 
	b."ChangeInReceivables", 
	b."ChangeInTaxPayable", 
	b."ChangeInWorkingCapital", 
	b."ChangesInAccountReceivables", 
	b."ChangesInCash", 
	b."ClassesofCashPayments", 
	b."ClassesofCashReceiptsfromOperatingActivities", 
	b."CommercialPaper", 
	b."CommonStock", 
	b."CommonStockDividendPaid", 
	b."CommonStockEquity", 
	b."CommonStockIssuance", 
	b."CommonStockPayments", 
	b."ConstructionInProgress", 
	b."CostOfRevenue", 
	b."CurrentAccruedExpenses", 
	b."CurrentAssets", 
	b."CurrentCapitalLeaseObligation", 
	b."CurrentDebt", 
	b."CurrentDebtAndCapitalLeaseObligation", 
	b."CurrentDeferredAssets", 
	b."CurrentDeferredLiabilities", 
	b."CurrentDeferredRevenue", 
	b."CurrentDeferredTaxesAssets", 
	b."CurrentDeferredTaxesLiabilities", 
	b."CurrentLiabilities", 
	b."CurrentNotesPayable", 
	b."CurrentProvisions", 
	b."DeferredIncomeTax", 
	b."DeferredTax", 
	b."DefinedPensionBenefit", 
	b."Depletion", 
	b."DepletionIncomeStatement", 
	b."Depreciation", 
	b."DepreciationAmortizationDepletion", 
	b."DepreciationAmortizationDepletionIncomeStatement", 
	b."DepreciationAndAmortization", 
	b."DepreciationAndAmortizationInIncomeStatement", 
	b."DepreciationIncomeStatement", 
	b."DerivativeProductLiabilities", 
	b."DilutedAverageShares", 
	b."DilutedEPS", 
	b."DilutedNIAvailtoComStockholders", 
	b."DividendPaidCFO", 
	b."DividendReceivedCFO", 
	b."DividendsPayable", 
	b."DividendsReceivedCFI", 
	b."DuefromRelatedPartiesCurrent", 
	b."DuefromRelatedPartiesNonCurrent", 
	b."DuetoRelatedPartiesCurrent", 
	b."DuetoRelatedPartiesNonCurrent", 
	b."EBIT", 
	b."EBITDA", 
	b."EarningsFromEquityInterest", 
	b."EarningsFromEquityInterestNetOfTax", 
	b."EarningsLossesFromEquityInvestments", 
	b."EffectOfExchangeRateChanges", 
	b."EmployeeBenefits", 
	b."EndCashPosition", 
	b."EnterpriseValue", 
	b."EnterprisesValueEBITDARatio", 
	b."EnterprisesValueRevenueRatio", 
	b."ExcessTaxBenefitFromStockBasedCompensation", 
	b."ExciseTaxes", 
	b."FinancialAssets", 
	b."FinancialAssetsDesignatedasFairValueThroughProfitorLossTotal", 
	b."FinancingCashFlow", 
	b."FinishedGoods", 
	b."FixedAssetsRevaluationReserve", 
	b."ForeignCurrencyTranslationAdjustments", 
	b."FreeCashFlow", 
	b."GainLossOnInvestmentSecurities", 
	b."GainLossOnSaleOfBusiness", 
	b."GainLossOnSaleOfPPE", 
	b."GainOnSaleOfBusiness", 
	b."GainOnSaleOfPPE", 
	b."GainOnSaleOfSecurity", 
	b."GainsLossesNotAffectingRetainedEarnings", 
	b."GeneralAndAdministrativeExpense", 
	b."GeneralPartnershipCapital", 
	b."Goodwill", 
	b."GoodwillAndOtherIntangibleAssets", 
	b."GrossAccountsReceivable", 
	b."GrossPPE", 
	b."GrossProfit", 
	b."HedgingAssetsCurrent", 
	b."HeldToMaturitySecurities", 
	b."ImpairmentOfCapitalAssets", 
	b."IncomeTaxPaidSupplementalData", 
	b."IncomeTaxPayable", 
	b."InsuranceAndClaims", 
	b."InterestExpense", 
	b."InterestExpenseNonOperating", 
	b."InterestIncome", 
	b."InterestIncomeNonOperating", 
	b."InterestPaidCFF", 
	b."InterestPaidCFO", 
	b."InterestPaidSupplementalData", 
	b."InterestPayable", 
	b."InterestReceivedCFI", 
	b."InterestReceivedCFO", 
	b."InventoriesAdjustmentsAllowances", 
	b."Inventory", 
	b."InvestedCapital", 
	b."InvestingCashFlow", 
	b."InvestmentProperties", 
	b."InvestmentinFinancialAssets", 
	b."InvestmentsAndAdvances", 
	b."InvestmentsInOtherVenturesUnderEquityMethod", 
	b."InvestmentsinAssociatesatCost", 
	b."InvestmentsinJointVenturesatCost", 
	b."InvestmentsinSubsidiariesatCost", 
	b."IssuanceOfCapitalStock", 
	b."IssuanceOfDebt", 
	b."LandAndImprovements", 
	b."Leases", 
	b."LiabilitiesHeldforSaleNonCurrent", 
	b."LimitedPartnershipCapital", 
	b."LineOfCredit", 
	b."LoansReceivable", 
	b."LongTermCapitalLeaseObligation", 
	b."LongTermDebt", 
	b."LongTermDebtAndCapitalLeaseObligation", 
	b."LongTermDebtIssuance", 
	b."LongTermDebtPayments", 
	b."LongTermEquityInvestment", 
	b."LongTermProvisions", 
	b."MachineryFurnitureEquipment", 
	b."MarketCap", 
	b."MinimumPensionLiabilities", 
	b."MinorityInterest", 
	b."MinorityInterests", 
	b."NetBusinessPurchaseAndSale", 
	b."NetCommonStockIssuance", 
	b."NetDebt", 
	b."NetForeignCurrencyExchangeGainLoss", 
	b."NetIncome", 
	b."NetIncomeCommonStockholders", 
	b."NetIncomeContinuousOperations", 
	b."NetIncomeDiscontinuousOperations", 
	b."NetIncomeExtraordinary", 
	b."NetIncomeFromContinuingAndDiscontinuedOperation", 
	b."NetIncomeFromContinuingOperationNetMinorityInterest", 
	b."NetIncomeFromContinuingOperations", 
	b."NetIncomeFromTaxLossCarryforward", 
	b."NetIncomeIncludingNoncontrollingInterests", 
	b."NetIntangiblesPurchaseAndSale", 
	b."NetInterestIncome", 
	b."NetInvestmentPropertiesPurchaseAndSale", 
	b."NetInvestmentPurchaseAndSale", 
	b."NetIssuancePaymentsOfDebt", 
	b."NetLongTermDebtIssuance", 
	b."NetNonOperatingInterestIncomeExpense", 
	b."NetOtherFinancingCharges", 
	b."NetOtherInvestingChanges", 
	b."NetPPE", 
	b."NetPPEPurchaseAndSale", 
	b."NetPreferredStockIssuance", 
	b."NetShortTermDebtIssuance", 
	b."NetTangibleAssets", 
	b."NonCurrentAccountsReceivable", 
	b."NonCurrentAccruedExpenses", 
	b."NonCurrentDeferredAssets", 
	b."NonCurrentDeferredLiabilities", 
	b."NonCurrentDeferredRevenue", 
	b."NonCurrentDeferredTaxesAssets", 
	b."NonCurrentDeferredTaxesLiabilities", 
	b."NonCurrentNoteReceivables", 
	b."NonCurrentPensionAndOtherPostretirementBenefitPlans", 
	b."NonCurrentPrepaidAssets", 
	b."NormalizedEBITDA", 
	b."NormalizedIncome", 
	b."NotesReceivable", 
	b."OperatingCashFlow", 
	b."OperatingExpense", 
	b."OperatingGainsLosses", 
	b."OperatingIncome", 
	b."OperatingRevenue", 
	b."OrdinarySharesNumber", 
	b."OtherCashAdjustmentInsideChangeinCash", 
	b."OtherCashAdjustmentOutsideChangeinCash", 
	b."OtherCashPaymentsfromOperatingActivities", 
	b."OtherCashReceiptsfromOperatingActivities", 
	b."OtherCurrentAssets", 
	b."OtherCurrentBorrowings", 
	b."OtherCurrentLiabilities", 
	b."OtherEquityAdjustments", 
	b."OtherEquityInterest", 
	b."OtherGandA", 
	b."OtherIncomeExpense", 
	b."OtherIntangibleAssets", 
	b."OtherInventories", 
	b."OtherInvestments", 
	b."OtherNonCashItems", 
	b."OtherNonCurrentAssets", 
	b."OtherNonCurrentLiabilities", 
	b."OtherNonOperatingIncomeExpenses", 
	b."OtherOperatingExpenses", 
	b."OtherPayable", 
	b."OtherProperties", 
	b."OtherReceivables", 
	b."OtherShortTermInvestments", 
	b."OtherSpecialCharges", 
	b."OtherTaxes", 
	b."OtherunderPreferredStockDividend", 
	b."Payables", 
	b."PayablesAndAccruedExpenses", 
	b."PaymentsonBehalfofEmployees", 
	b."PensionAndEmployeeBenefitExpense", 
	b."PensionandOtherPostRetirementBenefitPlansCurrent", 
	b."PreferredSecuritiesOutsideStockEquity", 
	b."PreferredSharesNumber", 
	b."PreferredStock", 
	b."PreferredStockDividendPaid", 
	b."PreferredStockDividends", 
	b."PreferredStockEquity", 
	b."PreferredStockIssuance", 
	b."PreferredStockPayments", 
	b."PrepaidAssets", 
	b."PretaxIncome", 
	b."ProceedsFromStockOptionExercised", 
	b."Properties", 
	b."ProvisionForDoubtfulAccounts", 
	b."ProvisionandWriteOffofAssets", 
	b."PurchaseOfBusiness", 
	b."PurchaseOfIntangibles", 
	b."PurchaseOfInvestment", 
	b."PurchaseOfInvestmentProperties", 
	b."PurchaseOfPPE", 
	b."RawMaterials", 
	b."Receivables", 
	b."ReceivablesAdjustmentsAllowances", 
	b."ReconciledCostOfRevenue", 
	b."ReconciledDepreciation", 
	b."RentAndLandingFees", 
	b."RentExpenseSupplemental", 
	b."RepaymentOfDebt", 
	b."RepurchaseOfCapitalStock", 
	b."ResearchAndDevelopment", 
	b."RestrictedCash", 
	b."RestructuringAndMergernAcquisition", 
	b."RetainedEarnings", 
	b."SalariesAndWages", 
	b."SaleOfBusiness", 
	b."SaleOfIntangibles", 
	b."SaleOfInvestment", 
	b."SaleOfInvestmentProperties", 
	b."SaleOfPPE", 
	b."SecuritiesAmortization", 
	b."SellingAndMarketingExpense", 
	b."SellingGeneralAndAdministration", 
	b."ShareIssued", 
	b."ShortTermDebtIssuance", 
	b."ShortTermDebtPayments", 
	b."SpecialIncomeCharges", 
	b."StockBasedCompensation", 
	b."StockholdersEquity", 
	b."TangibleBookValue", 
	b."TaxEffectOfUnusualItems", 
	b."TaxProvision", 
	b."TaxRateForCalcs", 
	b."TaxesReceivable", 
	b."TaxesRefundPaid", 
	b."TotalAssets", 
	b."TotalCapitalization", 
	b."TotalDebt", 
	b."TotalEquityGrossMinorityInterest", 
	b."TotalExpenses", 
	b."TotalLiabilitiesNetMinorityInterest", 
	b."TotalNonCurrentAssets", 
	b."TotalNonCurrentLiabilitiesNetMinorityInterest", 
	b."TotalOperatingIncomeAsReported", 
	b."TotalOtherFinanceCost", 
	b."TotalPartnershipCapital", 
	b."TotalRevenue", 
	b."TotalTaxPayable", 
	b."TotalUnusualItems", 
	b."TotalUnusualItemsExcludingGoodwill", 
	b."TradeandOtherPayablesNonCurrent", 
	b."TradingSecurities", 
	b."TreasurySharesNumber", 
	b."TreasuryStock", 
	b."UnrealizedGainLoss", 
	b."UnrealizedGainLossOnInvestmentSecurities", 
	b."WorkInProcess", 
	b."WorkingCapital", 
	b."WriteOff", 
	b."InterestPaidDirect", 
	b."InterestReceivedDirect", 
	b."PaymentstoSuppliersforGoodsandServices", 
	b."ReceiptsfromCustomers", 
	b."RestrictedCommonStock", 
	b."TaxesRefundPaidDirect", 
	b."KeyStats_maxAge", 
	b."KeyStats_priceHint", 
	b."KeyStats_enterpriseValue", 
	b."KeyStats_forwardPE", 
	b."KeyStats_profitMargins", 
	b."KeyStats_floatShares", 
	b."KeyStats_sharesOutstanding", 
	b."KeyStats_sharesShort", 
	b."KeyStats_sharesShortPriorMonth", 
	b."KeyStats_sharesShortPreviousMonthDate", 
	b."KeyStats_dateShortInterest", 
	b."KeyStats_sharesPercentSharesOut", 
	b."KeyStats_heldPercentInsiders", 
	b."KeyStats_heldPercentInstitutions", 
	b."KeyStats_shortRatio", 
	b."KeyStats_shortPercentOfFloat", 
	b."KeyStats_beta", 
	b."KeyStats_impliedSharesOutstanding", 
	b."KeyStats_category", 
	b."KeyStats_bookValue", 
	b."KeyStats_priceToBook", 
	b."KeyStats_fundFamily", 
	b."KeyStats_legalType", 
	b."KeyStats_lastFiscalYearEnd", 
	b."KeyStats_nextFiscalYearEnd", 
	b."KeyStats_mostRecentQuarter", 
	b."KeyStats_earningsQuarterlyGrowth", 
	b."KeyStats_netIncomeToCommon", 
	b."KeyStats_trailingEps", 
	b."KeyStats_forwardEps", 
	b."KeyStats_lastSplitFactor", 
	b."KeyStats_lastSplitDate", 
	b."KeyStats_enterpriseToRevenue", 
	b."KeyStats_enterpriseToEbitda", 
	b."KeyStats_52WeekChange", 
	b."KeyStats_SandP52WeekChange", 
	b."KeyStats_lastDividendValue", 
	b."KeyStats_lastDividendDate", 
	b."KeyStats_latestShareClass", 
	b."KeyStats_leadInvestor", 
	b."Forward_EPS_Growth_Percent", 
	b."Summary_maxAge", 
	b."Summary_priceHint", 
	b."Summary_previousClose", 
	b."Summary_open", 
	b."Summary_dayLow", 
	b."Summary_dayHigh", 
	b."Summary_regularMarketPreviousClose", 
	b."Summary_regularMarketOpen", 
	b."Summary_regularMarketDayLow", 
	b."Summary_regularMarketDayHigh", 
	b."Summary_dividendRate", 
	b."Summary_dividendYield", 
	b."Summary_exDividendDate", 
	b."Summary_payoutRatio", 
	b."Summary_fiveYearAvgDividendYield", 
	b."Summary_beta", 
	b."Summary_trailingPE", 
	b."Summary_forwardPE", 
	b."Summary_volume", 
	b."Summary_regularMarketVolume", 
	b."Summary_averageVolume", 
	b."Summary_averageVolume10days", 
	b."Summary_averageDailyVolume10Day", 
	b."Summary_bid", 
	b."Summary_ask", 
	b."Summary_bidSize", 
	b."Summary_askSize", 
	b."Summary_marketCap", 
	b."Summary_fiftyTwoWeekLow", 
	b."Summary_fiftyTwoWeekHigh", 
	b."Summary_allTimeHigh", 
	b."Summary_allTimeLow", 
	b."Summary_priceToSalesTrailing12Months", 
	b."Summary_fiftyDayAverage", 
	b."Summary_twoHundredDayAverage", 
	b."Summary_trailingAnnualDividendRate", 
	b."Summary_trailingAnnualDividendYield", 
	b."Summary_currency", 
	b."Summary_fromCurrency", 
	b."Summary_toCurrency", 
	b."Summary_lastMarket", 
	b."Summary_coinMarketCapLink", 
	b."Summary_algorithm", 
	b."Summary_tradeable", 
	b."FinData_maxAge", 
	b."FinData_currentPrice", 
	b."FinData_targetHighPrice", 
	b."FinData_targetLowPrice", 
	b."FinData_targetMeanPrice", 
	b."FinData_targetMedianPrice", 
	b."FinData_recommendationMean", 
	b."FinData_recommendationKey", 
	b."FinData_numberOfAnalystOpinions", 
	b."FinData_totalCash", 
	b."FinData_totalCashPerShare", 
	b."FinData_ebitda", 
	b."FinData_totalDebt", 
	b."FinData_quickRatio", 
	b."FinData_currentRatio", 
	b."FinData_totalRevenue", 
	b."FinData_debtToEquity", 
	b."FinData_revenuePerShare", 
	b."FinData_returnOnAssets", 
	b."FinData_returnOnEquity", 
	b."FinData_grossProfits", 
	b."FinData_freeCashflow", 
	b."FinData_operatingCashflow", 
	b."FinData_earningsGrowth", 
	b."FinData_revenueGrowth", 
	b."FinData_grossMargins", 
	b."FinData_ebitdaMargins", 
	b."FinData_operatingMargins", 
	b."FinData_profitMargins", 
	b."FinData_financialCurrency", 
	b."KeyStats_ytdReturn", 
	b."KeyStats_beta3Year", 
	b."KeyStats_totalAssets", 
	b."KeyStats_yield", 
	b."KeyStats_fundInceptionDate", 
	b."KeyStats_threeYearAverageReturn", 
	b."KeyStats_fiveYearAverageReturn", 
	b."Summary_yield", 
	b."Summary_totalAssets", 
	b."Summary_navPrice",

    -- Stock Data
	CASE WHEN c.symbol IS NOT NULL THEN TRUE ELSE FALSE END as has_stock_data,
	c.has_earnings_date,
	c.has_analyst_price_target,
	c.live_stock_price,
    c.price_source,
    c.live_price_timestamp,
    c.earnings_date,
	c.days_to_ernings,
    c.analyst_mean_target,

    -- Technical Indicators
	CASE WHEN d.symbol IS NOT NULL THEN TRUE ELSE FALSE END as has_technical_indicators,
    d."Recommend.Other", 
	d."Recommend.All", 
	d."Recommend.MA", 
	d."RSI", 
	d."RSI[1]", 
	d."Stoch.K", 
	d."Stoch.D", 
	d."Stoch.K[1]", 
	d."Stoch.D[1]", 
	d."CCI20", 
	d."CCI20[1]", 
	d."ADX", 
	d."ADX+DI", 
	d."ADX-DI", 
	d."ADX+DI[1]", 
	d."ADX-DI[1]", 
	d."AO", 
	d."AO[1]", 
	d."Mom", 
	d."Mom[1]", 
	d."MACD.macd", 
	d."MACD.signal", 
	d."Rec.Stoch.RSI", 
	d."Stoch.RSI.K", 
	d."Rec.WR", 
	d."W.R", 
	d."Rec.BBPower", 
	d."BBPower", 
	d."Rec.UO", 
	d."UO", 
	d.close, 
	d."EMA5", 
	d."SMA5", 
	d."EMA10", 
	d."SMA10", 
	d."EMA20", 
	d."SMA20", 
	d."EMA30", 
	d."SMA30", 
	d."EMA50", 
	d."SMA50", 
	d."EMA100", 
	d."SMA100", 
	d."EMA200", 
	d."SMA200", 
	d."Rec.Ichimoku", 
	d."Ichimoku.BLine", 
	d."Rec.VWMA", 
	d."VWMA", 
	d."Rec.HullMA9", 
	d."HullMA9", 
	d."Pivot.M.Classic.S3", 
	d."Pivot.M.Classic.S2", 
	d."Pivot.M.Classic.S1", 
	d."Pivot.M.Classic.Middle", 
	d."Pivot.M.Classic.R1", 
	d."Pivot.M.Classic.R2", 
	d."Pivot.M.Classic.R3", 
	d."Pivot.M.Fibonacci.S3", 
	d."Pivot.M.Fibonacci.S2", 
	d."Pivot.M.Fibonacci.S1", 
	d."Pivot.M.Fibonacci.Middle", 
	d."Pivot.M.Fibonacci.R1", 
	d."Pivot.M.Fibonacci.R2", 
	d."Pivot.M.Fibonacci.R3", 
	d."Pivot.M.Camarilla.S3", 
	d."Pivot.M.Camarilla.S2", 
	d."Pivot.M.Camarilla.S1", 
	d."Pivot.M.Camarilla.Middle", 
	d."Pivot.M.Camarilla.R1", 
	d."Pivot.M.Camarilla.R2", 
	d."Pivot.M.Camarilla.R3", 
	d."Pivot.M.Woodie.S3", 
	d."Pivot.M.Woodie.S2", 
	d."Pivot.M.Woodie.S1", 
	d."Pivot.M.Woodie.Middle", 
	d."Pivot.M.Woodie.R1", 
	d."Pivot.M.Woodie.R2", 
	d."Pivot.M.Woodie.R3", 
	d."Pivot.M.Demark.S1", 
	d."Pivot.M.Demark.Middle", 
	d."Pivot.M.Demark.R1", 
	d.open, 
	d."P.SAR", 
	d."BB.lower", 
	d."BB.upper", 
	d."AO[2]", 
	d.volume, 
	d.change, 
	d.low, 
	d.high, 
	d.recommendation, 
	d.recommendation_buy_amount, 
	d.recommendation_neutral_amount, 
	d.recommendation_sell_amount,

	-- Additional calculated fields
	ROUND(c.analyst_mean_target - d.close,2) as "target-close$",
	ROUND(ROUND(c.analyst_mean_target - d.close,2) / d.close * 100, 2) as "target-close%",
	d.close * a.iv * sqrt(a.days_to_expiration / 365) as expected_move

FROM 
    OptionData AS a
JOIN 
    FundamentalData as b
ON a.symbol = b.symbol
LEFT OUTER JOIN 
    StockData as c
ON a.symbol = c.symbol
LEFT OUTER JOIN 
    TechnicalIndicators as d
ON a.symbol = d.symbol;
DROP TABLE IF EXISTS "FundamentalDataYahooProcessed";