
    -- generated by HistorizationService
    CREATE VIEW
        "AnalystPriceTargetsHistory" AS
    
    SELECT
        daily.snapshot_date as date,
        daily."symbol",
        coalesce(
                daily."analyst_mean_target",
                weekly."analyst_mean_target",
                monthly."analyst_mean_target",
                master_data."analyst_mean_target"  
            ) as "analyst_mean_target"
    FROM
        "AnalystPriceTargetsHistoryDaily" as daily
        LEFT JOIN "AnalystPriceTargetsHistoryWeekly" as weekly ON strftime ('%Y', daily.snapshot_date) = weekly.year
        AND strftime ('%W', daily.snapshot_date) = weekly.week
        AND daily."symbol" = weekly."symbol"
        LEFT JOIN "AnalystPriceTargetsHistoryMonthly" as monthly ON strftime ('%Y', daily.snapshot_date) = monthly.year
        AND strftime ('%m', daily.snapshot_date) = monthly.month
        AND daily."symbol" = monthly."symbol"
        LEFT JOIN "AnalystPriceTargetsMasterData" as master_data ON daily."symbol" = master_data."symbol"
    ;
    