
    -- generated by HistorizationService
    CREATE VIEW
        "AnalystPriceTargetsHistory" AS
    
            SELECT
                daily.snapshot_date AS date,
                daily."symbol",
            daily."analyst_mean_target" as "analyst_mean_target"
            FROM
                "AnalystPriceTargetsHistoryDaily" as daily
            ;
    