
    -- generated by HistorizationService
    CREATE VIEW
        "AnalystPriceTargetsHistory" AS
    
        SELECT
            daily.snapshot_date AS date,
            master_data."symbol",
        coalesce(
                daily."analyst_mean_target",
                master_data."analyst_mean_target"
            ) as "analyst_mean_target"
        FROM
            "AnalystPriceTargetsMasterData" as master_data
            INNER JOIN "AnalystPriceTargetsHistoryDaily" as daily
        ON master_data."symbol" = daily."symbol"
        ;
    