
    -- generated by HistorizationService
    CREATE VIEW
        "DividendDataYahooHistory" AS
    
        SELECT
            daily.snapshot_date AS date,
            master_data."symbol",
        coalesce(
                daily."years_of_growth",
                master_data."years_of_growth"
            ) as "years_of_growth",
		coalesce(
                daily."classification",
                master_data."classification"
            ) as "classification"
        FROM
            "DividendDataYahooMasterData" as master_data
            INNER JOIN "DividendDataYahooHistoryDaily" as daily
        ON master_data."symbol" = daily."symbol"
        ;
    