
    -- generated by HistorizationService
    CREATE VIEW
        "DividendDataYahooHistory" AS
    
    SELECT
        dates.date,
        dates.year,
        dates.month,
        dates.isoyear,
        dates.week,
        master_data."symbol",
        coalesce(
                daily."years_of_growth",
                master_data."years_of_growth"
            ) as "years_of_growth",
		coalesce(
                daily."classification",
                master_data."classification"
            ) as "classification"
    FROM
        "DatesHistory" as dates
        INNER JOIN "DividendDataYahooMasterData" as master_data
        ON dates.date BETWEEN master_data.from_date AND master_data.to_date 
        LEFT JOIN "DividendDataYahooHistoryDaily" as daily
        ON dates.date = daily.snapshot_date
        AND master_data."symbol" = daily."symbol"
    ;
    