
    -- generated by HistorizationService
    CREATE VIEW
        "DividendDataYahooHistory" AS
    
            SELECT
                daily.snapshot_date AS date,
                daily."symbol",
            daily."years_of_growth" as "years_of_growth",
			daily."classification" as "classification"
            FROM
                "DividendDataYahooHistoryDaily" as daily
            ;
    