
    -- generated by HistorizationService
    CREATE VIEW
        "EarningDatesHistory" AS
    
            SELECT
                daily.snapshot_date AS date,
                daily."symbol",
            daily."earnings_date" as "earnings_date"
            FROM
                "EarningDatesHistoryDaily" as daily
            ;
    