
    -- generated by HistorizationService
    CREATE VIEW
        "EarningDatesHistory" AS
    
        SELECT
            daily.snapshot_date AS date,
            master_data."symbol",
        coalesce(
                daily."earnings_date",
                master_data."earnings_date"
            ) as "earnings_date"
        FROM
            "EarningDatesMasterData" as master_data
            INNER JOIN "EarningDatesHistoryDaily" as daily
        ON master_data."symbol" = daily."symbol"
        ;
    