
    -- generated by HistorizationService
    CREATE VIEW
        "FundamentalDataDividendRadarHistory" AS
    
    SELECT
        dates.date,
        dates.year,
        dates.month,
        dates.isoyear,
        dates.week,
        master_data."Symbol",
        coalesce(
                daily."Company",
                weekly."Company",
                monthly."Company",
                master_data."Company"  
            ) as "Company",
		coalesce(
                daily."FV",
                weekly."FV",
                monthly."FV",
                master_data."FV"  
            ) as "FV",
		coalesce(
                daily."Sector",
                weekly."Sector",
                monthly."Sector",
                master_data."Sector"  
            ) as "Sector",
		coalesce(
                daily."No-Years",
                weekly."No-Years",
                monthly."No-Years",
                master_data."No-Years"  
            ) as "No-Years",
		coalesce(
                daily."Price",
                weekly."Price",
                monthly."Price",
                master_data."Price"  
            ) as "Price",
		coalesce(
                daily."Div-Yield",
                weekly."Div-Yield",
                monthly."Div-Yield",
                master_data."Div-Yield"  
            ) as "Div-Yield",
		coalesce(
                daily."5Y-Avg-Yield",
                weekly."5Y-Avg-Yield",
                monthly."5Y-Avg-Yield",
                master_data."5Y-Avg-Yield"  
            ) as "5Y-Avg-Yield",
		coalesce(
                daily."Current-Div",
                weekly."Current-Div",
                monthly."Current-Div",
                master_data."Current-Div"  
            ) as "Current-Div",
		coalesce(
                daily."Payouts/-Year",
                weekly."Payouts/-Year",
                monthly."Payouts/-Year",
                master_data."Payouts/-Year"  
            ) as "Payouts/-Year",
		coalesce(
                daily."Annualized",
                weekly."Annualized",
                monthly."Annualized",
                master_data."Annualized"  
            ) as "Annualized",
		coalesce(
                daily."Previous-Div",
                weekly."Previous-Div",
                monthly."Previous-Div",
                master_data."Previous-Div"  
            ) as "Previous-Div",
		coalesce(
                daily."Ex-Date",
                weekly."Ex-Date",
                monthly."Ex-Date",
                master_data."Ex-Date"  
            ) as "Ex-Date",
		coalesce(
                daily."Pay-Date",
                weekly."Pay-Date",
                monthly."Pay-Date",
                master_data."Pay-Date"  
            ) as "Pay-Date",
		coalesce(
                daily."Low",
                weekly."Low",
                monthly."Low",
                master_data."Low"  
            ) as "Low",
		coalesce(
                daily."High",
                weekly."High",
                monthly."High",
                master_data."High"  
            ) as "High",
		coalesce(
                daily."DGR-1Y",
                weekly."DGR-1Y",
                monthly."DGR-1Y",
                master_data."DGR-1Y"  
            ) as "DGR-1Y",
		coalesce(
                daily."DGR-3Y",
                weekly."DGR-3Y",
                monthly."DGR-3Y",
                master_data."DGR-3Y"  
            ) as "DGR-3Y",
		coalesce(
                daily."DGR-5Y",
                weekly."DGR-5Y",
                monthly."DGR-5Y",
                master_data."DGR-5Y"  
            ) as "DGR-5Y",
		coalesce(
                daily."DGR-10Y",
                weekly."DGR-10Y",
                monthly."DGR-10Y",
                master_data."DGR-10Y"  
            ) as "DGR-10Y",
		coalesce(
                daily."TTR-1Y",
                weekly."TTR-1Y",
                monthly."TTR-1Y",
                master_data."TTR-1Y"  
            ) as "TTR-1Y",
		coalesce(
                daily."TTR-3Y",
                weekly."TTR-3Y",
                monthly."TTR-3Y",
                master_data."TTR-3Y"  
            ) as "TTR-3Y",
		coalesce(
                daily."Fair-Value",
                weekly."Fair-Value",
                monthly."Fair-Value",
                master_data."Fair-Value"  
            ) as "Fair-Value",
		coalesce(
                daily."FV-%",
                weekly."FV-%",
                monthly."FV-%",
                master_data."FV-%"  
            ) as "FV-%",
		coalesce(
                daily."Streak-Basis",
                weekly."Streak-Basis",
                monthly."Streak-Basis",
                master_data."Streak-Basis"  
            ) as "Streak-Basis",
		coalesce(
                daily."Chowder-Number",
                weekly."Chowder-Number",
                monthly."Chowder-Number",
                master_data."Chowder-Number"  
            ) as "Chowder-Number",
		coalesce(
                daily."EPS-1Y",
                weekly."EPS-1Y",
                monthly."EPS-1Y",
                master_data."EPS-1Y"  
            ) as "EPS-1Y",
		coalesce(
                daily."Revenue-1Y",
                weekly."Revenue-1Y",
                monthly."Revenue-1Y",
                master_data."Revenue-1Y"  
            ) as "Revenue-1Y",
		coalesce(
                daily."NPM",
                weekly."NPM",
                monthly."NPM",
                master_data."NPM"  
            ) as "NPM",
		coalesce(
                daily."CF/Share",
                weekly."CF/Share",
                monthly."CF/Share",
                master_data."CF/Share"  
            ) as "CF/Share",
		coalesce(
                daily."ROE",
                weekly."ROE",
                monthly."ROE",
                master_data."ROE"  
            ) as "ROE",
		coalesce(
                daily."Current-R",
                weekly."Current-R",
                monthly."Current-R",
                master_data."Current-R"  
            ) as "Current-R",
		coalesce(
                daily."Debt/Capital",
                weekly."Debt/Capital",
                monthly."Debt/Capital",
                master_data."Debt/Capital"  
            ) as "Debt/Capital",
		coalesce(
                daily."ROTC",
                weekly."ROTC",
                monthly."ROTC",
                master_data."ROTC"  
            ) as "ROTC",
		coalesce(
                daily."P/E",
                weekly."P/E",
                monthly."P/E",
                master_data."P/E"  
            ) as "P/E",
		coalesce(
                daily."P/BV",
                weekly."P/BV",
                monthly."P/BV",
                master_data."P/BV"  
            ) as "P/BV",
		coalesce(
                daily."PEG",
                weekly."PEG",
                monthly."PEG",
                master_data."PEG"  
            ) as "PEG",
		coalesce(
                daily."New-Member",
                weekly."New-Member",
                monthly."New-Member",
                master_data."New-Member"  
            ) as "New-Member",
		coalesce(
                daily."Industry",
                weekly."Industry",
                monthly."Industry",
                master_data."Industry"  
            ) as "Industry",
		coalesce(
                daily."Classification",
                weekly."Classification",
                monthly."Classification",
                master_data."Classification"  
            ) as "Classification"
    FROM
        "DatesHistory" as dates
        CROSS JOIN "FundamentalDataDividendRadarMasterData" as master_data 
        LEFT JOIN "FundamentalDataDividendRadarHistoryDaily" as daily
        ON dates.date = daily.snapshot_date
        AND master_data."Symbol" = daily."Symbol"
        LEFT JOIN "FundamentalDataDividendRadarHistoryWeekly" as weekly 
        ON dates.isoyear = weekly.isoyear
        AND dates.week = weekly.week
        AND master_data."Symbol" = weekly."Symbol"
        LEFT JOIN "FundamentalDataDividendRadarHistoryMonthly" as monthly 
        ON dates.year = monthly.year
        AND dates.month = monthly.month
        AND master_data."Symbol" = monthly."Symbol"
    ;
    