
    -- generated by HistorizationService
    CREATE VIEW
        "FundamentalDataDividendRadarHistory" AS
    
    SELECT
        dates.date,
        dates.year,
        dates.month,
        dates.isoyear,
        dates.week,
        master_data."Symbol",
        coalesce(
                daily."Company",
                master_data."Company"
            ) as "Company",
		coalesce(
                daily."FV",
                master_data."FV"
            ) as "FV",
		coalesce(
                daily."Sector",
                master_data."Sector"
            ) as "Sector",
		coalesce(
                daily."No-Years",
                master_data."No-Years"
            ) as "No-Years",
		coalesce(
                daily."Price",
                master_data."Price"
            ) as "Price",
		coalesce(
                daily."Div-Yield",
                master_data."Div-Yield"
            ) as "Div-Yield",
		coalesce(
                daily."5Y-Avg-Yield",
                master_data."5Y-Avg-Yield"
            ) as "5Y-Avg-Yield",
		coalesce(
                daily."Current-Div",
                master_data."Current-Div"
            ) as "Current-Div",
		coalesce(
                daily."Payouts/-Year",
                master_data."Payouts/-Year"
            ) as "Payouts/-Year",
		coalesce(
                daily."Annualized",
                master_data."Annualized"
            ) as "Annualized",
		coalesce(
                daily."Previous-Div",
                master_data."Previous-Div"
            ) as "Previous-Div",
		coalesce(
                daily."Ex-Date",
                master_data."Ex-Date"
            ) as "Ex-Date",
		coalesce(
                daily."Pay-Date",
                master_data."Pay-Date"
            ) as "Pay-Date",
		coalesce(
                daily."Low",
                master_data."Low"
            ) as "Low",
		coalesce(
                daily."High",
                master_data."High"
            ) as "High",
		coalesce(
                daily."DGR-1Y",
                master_data."DGR-1Y"
            ) as "DGR-1Y",
		coalesce(
                daily."DGR-3Y",
                master_data."DGR-3Y"
            ) as "DGR-3Y",
		coalesce(
                daily."DGR-5Y",
                master_data."DGR-5Y"
            ) as "DGR-5Y",
		coalesce(
                daily."DGR-10Y",
                master_data."DGR-10Y"
            ) as "DGR-10Y",
		coalesce(
                daily."TTR-1Y",
                master_data."TTR-1Y"
            ) as "TTR-1Y",
		coalesce(
                daily."TTR-3Y",
                master_data."TTR-3Y"
            ) as "TTR-3Y",
		coalesce(
                daily."Fair-Value",
                master_data."Fair-Value"
            ) as "Fair-Value",
		coalesce(
                daily."FV-%",
                master_data."FV-%"
            ) as "FV-%",
		coalesce(
                daily."Streak-Basis",
                master_data."Streak-Basis"
            ) as "Streak-Basis",
		coalesce(
                daily."Chowder-Number",
                master_data."Chowder-Number"
            ) as "Chowder-Number",
		coalesce(
                daily."EPS-1Y",
                master_data."EPS-1Y"
            ) as "EPS-1Y",
		coalesce(
                daily."Revenue-1Y",
                master_data."Revenue-1Y"
            ) as "Revenue-1Y",
		coalesce(
                daily."NPM",
                master_data."NPM"
            ) as "NPM",
		coalesce(
                daily."CF/Share",
                master_data."CF/Share"
            ) as "CF/Share",
		coalesce(
                daily."ROE",
                master_data."ROE"
            ) as "ROE",
		coalesce(
                daily."Current-R",
                master_data."Current-R"
            ) as "Current-R",
		coalesce(
                daily."Debt/Capital",
                master_data."Debt/Capital"
            ) as "Debt/Capital",
		coalesce(
                daily."ROTC",
                master_data."ROTC"
            ) as "ROTC",
		coalesce(
                daily."P/E",
                master_data."P/E"
            ) as "P/E",
		coalesce(
                daily."P/BV",
                master_data."P/BV"
            ) as "P/BV",
		coalesce(
                daily."PEG",
                master_data."PEG"
            ) as "PEG",
		coalesce(
                daily."New-Member",
                master_data."New-Member"
            ) as "New-Member",
		coalesce(
                daily."Industry",
                master_data."Industry"
            ) as "Industry",
		coalesce(
                daily."Classification",
                master_data."Classification"
            ) as "Classification"
    FROM
        "DatesHistory" as dates
        INNER JOIN "FundamentalDataDividendRadarMasterData" as master_data
        ON dates.date BETWEEN master_data.from_date AND master_data.to_date 
        LEFT JOIN "FundamentalDataDividendRadarHistoryDaily" as daily
        ON dates.date = daily.snapshot_date
        AND master_data."Symbol" = daily."Symbol"
    ;
    