
    -- generated by HistorizationService
    CREATE VIEW
        "OptionDataYahooHistory" AS
    
    SELECT
        dates.date,
        master_data."contractSymbol",
        master_data."symbol" as "symbol",
		master_data."option-type" as "option-type",
		master_data."expiration_date" as "expiration_date",
		master_data."strike" as "strike",
		master_data."currency" as "currency",
		coalesce(
                daily."lastPrice",
                weekly."lastPrice",
                monthly."lastPrice",
                master_data."lastPrice"  
            ) as "lastPrice",
		coalesce(
                daily."change",
                weekly."change",
                monthly."change",
                master_data."change"  
            ) as "change",
		coalesce(
                daily."percentChange",
                weekly."percentChange",
                monthly."percentChange",
                master_data."percentChange"  
            ) as "percentChange",
		coalesce(
                daily."option_open_interest",
                weekly."option_open_interest",
                monthly."option_open_interest",
                master_data."option_open_interest"  
            ) as "option_open_interest",
		coalesce(
                daily."bid",
                weekly."bid",
                monthly."bid",
                master_data."bid"  
            ) as "bid",
		coalesce(
                daily."ask",
                weekly."ask",
                monthly."ask",
                master_data."ask"  
            ) as "ask",
		master_data."contractSize" as "contractSize",
		coalesce(
                daily."lastTradeDate",
                weekly."lastTradeDate",
                monthly."lastTradeDate",
                master_data."lastTradeDate"  
            ) as "lastTradeDate",
		coalesce(
                daily."impliedVolatility",
                weekly."impliedVolatility",
                monthly."impliedVolatility",
                master_data."impliedVolatility"  
            ) as "impliedVolatility",
		coalesce(
                daily."inTheMoney",
                weekly."inTheMoney",
                monthly."inTheMoney",
                master_data."inTheMoney"  
            ) as "inTheMoney",
		coalesce(
                daily."option_volume",
                weekly."option_volume",
                monthly."option_volume",
                master_data."option_volume"  
            ) as "option_volume"
    FROM
        "DatesHistory" as dates
        CROSS JOIN "OptionDataYahooMasterData" as master_data 
        LEFT JOIN "OptionDataYahooHistoryDaily" as daily
        ON dates.date = daily.snapshot_date
        AND master_data."contractSymbol" = daily."contractSymbol"
        LEFT JOIN "OptionDataYahooHistoryWeekly" as weekly 
        ON dates.isoyear = weekly.isoyear
        AND dates.week = weekly.week
        AND master_data."contractSymbol" = weekly."contractSymbol"
        LEFT JOIN "OptionDataYahooHistoryMonthly" as monthly 
        ON dates.year = monthly.year
        AND dates.month = monthly.month
        AND master_data."contractSymbol" = monthly."contractSymbol"
    ;
    