
    -- generated by HistorizationService
    CREATE VIEW
        "OptionDataTradingViewHistory" AS
    
    SELECT
        daily.snapshot_date as date,
        daily."option_osi",
        master_data."symbol" as "symbol",
		master_data."option-type" as "option-type",
		master_data."expiration_date" as "expiration_date",
		master_data."strike" as "strike",
		coalesce(
                daily."ask",
                weekly."ask",
                monthly."ask",
                master_data."ask"  
            ) as "ask",
		coalesce(
                daily."bid",
                weekly."bid",
                monthly."bid",
                master_data."bid"  
            ) as "bid",
		coalesce(
                daily."delta",
                weekly."delta",
                monthly."delta",
                master_data."delta"  
            ) as "delta",
		coalesce(
                daily."gamma",
                weekly."gamma",
                monthly."gamma",
                master_data."gamma"  
            ) as "gamma",
		coalesce(
                daily."iv",
                weekly."iv",
                monthly."iv",
                master_data."iv"  
            ) as "iv",
		coalesce(
                daily."rho",
                weekly."rho",
                monthly."rho",
                master_data."rho"  
            ) as "rho",
		coalesce(
                daily."theoPrice",
                weekly."theoPrice",
                monthly."theoPrice",
                master_data."theoPrice"  
            ) as "theoPrice",
		coalesce(
                daily."theta",
                weekly."theta",
                monthly."theta",
                master_data."theta"  
            ) as "theta",
		coalesce(
                daily."vega",
                weekly."vega",
                monthly."vega",
                master_data."vega"  
            ) as "vega",
		master_data."option" as "option",
		coalesce(
                daily."time",
                weekly."time",
                monthly."time",
                master_data."time"  
            ) as "time",
		master_data."exchange" as "exchange"
    FROM
        "OptionDataTradingViewHistoryDaily" as daily
        LEFT JOIN "OptionDataTradingViewHistoryWeekly" as weekly ON strftime ('%Y', daily.snapshot_date) = weekly.year
        AND strftime ('%W', daily.snapshot_date) = weekly.week
        AND daily."option_osi" = weekly."option_osi"
        LEFT JOIN "OptionDataTradingViewHistoryMonthly" as monthly ON strftime ('%Y', daily.snapshot_date) = monthly.year
        AND strftime ('%m', daily.snapshot_date) = monthly.month
        AND daily."option_osi" = monthly."option_osi"
        LEFT JOIN "OptionDataTradingViewMasterData" as master_data ON daily."option_osi" = master_data."option_osi"
    ;
    