
    -- generated by HistorizationService
    CREATE VIEW
        "OptionDataTradingViewHistory" AS
    
    SELECT
        dates.date,
        dates.year,
        dates.month,
        dates.isoyear,
        dates.week,
        master_data."option_osi",
        master_data."symbol" as "symbol",
		master_data."option-type" as "option-type",
		master_data."expiration_date" as "expiration_date",
		master_data."strike" as "strike",
		coalesce(
                daily."ask",
                weekly."ask",
                monthly."ask",
                master_data."ask"  
            ) as "ask",
		coalesce(
                daily."bid",
                weekly."bid",
                monthly."bid",
                master_data."bid"  
            ) as "bid",
		coalesce(
                daily."delta",
                weekly."delta",
                monthly."delta",
                master_data."delta"  
            ) as "delta",
		coalesce(
                daily."gamma",
                weekly."gamma",
                monthly."gamma",
                master_data."gamma"  
            ) as "gamma",
		coalesce(
                daily."iv",
                weekly."iv",
                monthly."iv",
                master_data."iv"  
            ) as "iv",
		coalesce(
                daily."rho",
                weekly."rho",
                monthly."rho",
                master_data."rho"  
            ) as "rho",
		coalesce(
                daily."theoPrice",
                weekly."theoPrice",
                monthly."theoPrice",
                master_data."theoPrice"  
            ) as "theoPrice",
		coalesce(
                daily."theta",
                weekly."theta",
                monthly."theta",
                master_data."theta"  
            ) as "theta",
		coalesce(
                daily."vega",
                weekly."vega",
                monthly."vega",
                master_data."vega"  
            ) as "vega",
		master_data."option" as "option",
		coalesce(
                daily."time",
                weekly."time",
                monthly."time",
                master_data."time"  
            ) as "time",
		master_data."exchange" as "exchange"
    FROM
        "DatesHistory" as dates
        CROSS JOIN "OptionDataTradingViewMasterData" as master_data 
        LEFT JOIN "OptionDataTradingViewHistoryDaily" as daily
        ON dates.date = daily.snapshot_date
        AND master_data."option_osi" = daily."option_osi"
        LEFT JOIN "OptionDataTradingViewHistoryWeekly" as weekly 
        ON dates.isoyear = weekly.isoyear
        AND dates.week = weekly.week
        AND master_data."option_osi" = weekly."option_osi"
        LEFT JOIN "OptionDataTradingViewHistoryMonthly" as monthly 
        ON dates.year = monthly.year
        AND dates.month = monthly.month
        AND master_data."option_osi" = monthly."option_osi"
    ;
    