
    -- generated by HistorizationService
    CREATE VIEW
        "StockPriceHistory" AS
    
    SELECT
        daily.snapshot_date as date,
        daily."symbol",
        coalesce(
                daily."live_stock_price",
                weekly."live_stock_price",
                monthly."live_stock_price",
                master_data."live_stock_price"  
            ) as "live_stock_price",
		coalesce(
                daily."price_source",
                weekly."price_source",
                monthly."price_source",
                master_data."price_source"  
            ) as "price_source",
		coalesce(
                daily."live_price_timestamp",
                weekly."live_price_timestamp",
                monthly."live_price_timestamp",
                master_data."live_price_timestamp"  
            ) as "live_price_timestamp"
    FROM
        "StockPriceHistoryDaily" as daily
        LEFT JOIN "StockPriceHistoryWeekly" as weekly ON strftime ('%Y', daily.snapshot_date) = weekly.year
        AND strftime ('%W', daily.snapshot_date) = weekly.week
        AND daily."symbol" = weekly."symbol"
        LEFT JOIN "StockPriceHistoryMonthly" as monthly ON strftime ('%Y', daily.snapshot_date) = monthly.year
        AND strftime ('%m', daily.snapshot_date) = monthly.month
        AND daily."symbol" = monthly."symbol"
        LEFT JOIN "StockPriceMasterData" as master_data ON daily."symbol" = master_data."symbol"
    ;
    