
    -- generated by HistorizationService
    CREATE VIEW
        "StockAssetProfilesYahooHistory" AS
    
    SELECT
        dates.date,
        dates.year,
        dates.month,
        dates.isoyear,
        dates.week,
        master_data."symbol",
        coalesce(
                daily."name",
                master_data."name"
            ) as "name",
		coalesce(
                daily."industry",
                master_data."industry"
            ) as "industry",
		coalesce(
                daily."sector",
                master_data."sector"
            ) as "sector",
		coalesce(
                daily."country",
                master_data."country"
            ) as "country",
		coalesce(
                daily."long_business_summary",
                master_data."long_business_summary"
            ) as "long_business_summary"
    FROM
        "DatesHistory" as dates
        INNER JOIN "StockAssetProfilesYahooMasterData" as master_data
        ON dates.date BETWEEN master_data.from_date AND master_data.to_date 
        LEFT JOIN "StockAssetProfilesYahooHistoryDaily" as daily
        ON dates.date = daily.snapshot_date
        AND master_data."symbol" = daily."symbol"
    ;
    