
    -- generated by HistorizationService
    CREATE VIEW
        "StockHistoricalVolatilityYahooHistory" AS
    
            SELECT
                daily.snapshot_date AS date,
                daily."symbol",
            daily."historical_volatility_30d" as "historical_volatility_30d"
            FROM
                "StockHistoricalVolatilityYahooHistoryDaily" as daily
            ;
    