
    -- generated by HistorizationService
    CREATE VIEW
        "StockImpliedVolatilityMassiveHistory" AS
    
    SELECT
        dates.date,
        dates.year,
        dates.month,
        dates.isoyear,
        dates.week,
        master_data."symbol",
        coalesce(
                daily."iv",
                master_data."iv"
            ) as "iv",
		coalesce(
                daily."iv_low",
                master_data."iv_low"
            ) as "iv_low",
		coalesce(
                daily."iv_high",
                master_data."iv_high"
            ) as "iv_high",
		coalesce(
                daily."iv_rank",
                master_data."iv_rank"
            ) as "iv_rank",
		coalesce(
                daily."iv_percentile",
                master_data."iv_percentile"
            ) as "iv_percentile"
    FROM
        "DatesHistory" as dates
        INNER JOIN "StockImpliedVolatilityMassiveMasterData" as master_data
        ON dates.date BETWEEN master_data.from_date AND master_data.to_date 
        LEFT JOIN "StockImpliedVolatilityMassiveHistoryDaily" as daily
        ON dates.date = daily.snapshot_date
        AND master_data."symbol" = daily."symbol"
    ;
    