
    -- generated by HistorizationService
    CREATE VIEW
        "StockHistoricalVolatilityYahooHistory" AS
    
        SELECT
            daily.snapshot_date AS date,
            master_data."symbol",
        coalesce(
                daily."historical_volatility_30d",
                master_data."historical_volatility_30d"
            ) as "historical_volatility_30d"
        FROM
            "StockHistoricalVolatilityYahooMasterData" as master_data
            INNER JOIN "StockHistoricalVolatilityYahooHistoryDaily" as daily
        ON master_data."symbol" = daily."symbol"
        ;
    