
    -- generated by HistorizationService
    CREATE VIEW
        "StockAssetProfilesYahooHistory" AS
    
        SELECT
            daily.snapshot_date AS date,
            master_data.from_date AS from_date,
            master_data.to_date AS to_date,
            master_data."symbol",
        coalesce(
                daily."name",
                master_data."name"
            ) as "name",
		coalesce(
                daily."industry",
                master_data."industry"
            ) as "industry",
		coalesce(
                daily."sector",
                master_data."sector"
            ) as "sector",
		coalesce(
                daily."country",
                master_data."country"
            ) as "country",
		coalesce(
                daily."long_business_summary",
                master_data."long_business_summary"
            ) as "long_business_summary"
        FROM
            "StockAssetProfilesYahooMasterData" as master_data
            LEFT OUTER JOIN "StockAssetProfilesYahooHistoryDaily" as daily
        ON master_data."symbol" = daily."symbol"
        ;
    