
    -- generated by HistorizationService
    CREATE VIEW
        "StockPricesYahooHistory" AS
    
    SELECT
        dates.date,
        dates.year,
        dates.month,
        dates.isoyear,
        dates.week,
        master_data."symbol",
        coalesce(
                daily."open",
                master_data."open"
            ) as "open",
		coalesce(
                daily."high",
                master_data."high"
            ) as "high",
		coalesce(
                daily."low",
                master_data."low"
            ) as "low",
		coalesce(
                daily."close",
                master_data."close"
            ) as "close",
		coalesce(
                daily."volume",
                master_data."volume"
            ) as "volume",
		coalesce(
                daily."adjclose",
                master_data."adjclose"
            ) as "adjclose",
		coalesce(
                daily."dividends",
                master_data."dividends"
            ) as "dividends",
		coalesce(
                daily."splits",
                master_data."splits"
            ) as "splits"
    FROM
        "DatesHistory" as dates
        INNER JOIN "StockPricesYahooMasterData" as master_data
        ON dates.date BETWEEN master_data.from_date AND master_data.to_date 
        LEFT JOIN "StockPricesYahooHistoryDaily" as daily
        ON dates.date = daily.snapshot_date
        AND master_data."symbol" = daily."symbol"
    ;
    