
    -- generated by HistorizationService
    CREATE VIEW
        "StockDataBarchartHistory" AS
    
    SELECT
        daily.snapshot_date as date,
        daily."symbol",
        coalesce(
                daily."implied_volatility",
                weekly."implied_volatility",
                monthly."implied_volatility",
                master_data."implied_volatility"  
            ) as "implied_volatility",
		coalesce(
                daily."historical_volatility",
                weekly."historical_volatility",
                monthly."historical_volatility",
                master_data."historical_volatility"  
            ) as "historical_volatility",
		coalesce(
                daily."iv_percentile",
                weekly."iv_percentile",
                monthly."iv_percentile",
                master_data."iv_percentile"  
            ) as "iv_percentile",
		coalesce(
                daily."iv_rank",
                weekly."iv_rank",
                monthly."iv_rank",
                master_data."iv_rank"  
            ) as "iv_rank",
		coalesce(
                daily."iv_high",
                weekly."iv_high",
                monthly."iv_high",
                master_data."iv_high"  
            ) as "iv_high",
		coalesce(
                daily."iv_low",
                weekly."iv_low",
                monthly."iv_low",
                master_data."iv_low"  
            ) as "iv_low",
		coalesce(
                daily."put_call_vol_ratio",
                weekly."put_call_vol_ratio",
                monthly."put_call_vol_ratio",
                master_data."put_call_vol_ratio"  
            ) as "put_call_vol_ratio",
		coalesce(
                daily."put_call_oi_ratio",
                weekly."put_call_oi_ratio",
                monthly."put_call_oi_ratio",
                master_data."put_call_oi_ratio"  
            ) as "put_call_oi_ratio",
		coalesce(
                daily."todays_volume",
                weekly."todays_volume",
                monthly."todays_volume",
                master_data."todays_volume"  
            ) as "todays_volume",
		coalesce(
                daily."volume_avg_30d",
                weekly."volume_avg_30d",
                monthly."volume_avg_30d",
                master_data."volume_avg_30d"  
            ) as "volume_avg_30d",
		coalesce(
                daily."todays_open_interest",
                weekly."todays_open_interest",
                monthly."todays_open_interest",
                master_data."todays_open_interest"  
            ) as "todays_open_interest",
		coalesce(
                daily."open_int_30d",
                weekly."open_int_30d",
                monthly."open_int_30d",
                master_data."open_int_30d"  
            ) as "open_int_30d"
    FROM
        "StockDataBarchartHistoryDaily" as daily
        LEFT JOIN "StockDataBarchartHistoryWeekly" as weekly ON strftime ('%Y', daily.snapshot_date) = weekly.year
        AND strftime ('%W', daily.snapshot_date) = weekly.week
        AND daily."symbol" = weekly."symbol"
        LEFT JOIN "StockDataBarchartHistoryMonthly" as monthly ON strftime ('%Y', daily.snapshot_date) = monthly.year
        AND strftime ('%m', daily.snapshot_date) = monthly.month
        AND daily."symbol" = monthly."symbol"
        LEFT JOIN "StockDataBarchartMasterData" as master_data ON daily."symbol" = master_data."symbol"
    ;
    