
    -- generated by HistorizationService
    CREATE VIEW
        "TechnicalIndicatorsHistory" AS
    
    SELECT
        dates.date,
        master_data."symbol",
        coalesce(
                daily."Recommend.Other",
                weekly."Recommend.Other",
                monthly."Recommend.Other",
                master_data."Recommend.Other"  
            ) as "Recommend.Other",
		coalesce(
                daily."Recommend.All",
                weekly."Recommend.All",
                monthly."Recommend.All",
                master_data."Recommend.All"  
            ) as "Recommend.All",
		coalesce(
                daily."Recommend.MA",
                weekly."Recommend.MA",
                monthly."Recommend.MA",
                master_data."Recommend.MA"  
            ) as "Recommend.MA",
		coalesce(
                daily."RSI",
                weekly."RSI",
                monthly."RSI",
                master_data."RSI"  
            ) as "RSI",
		coalesce(
                daily."RSI[1]",
                weekly."RSI[1]",
                monthly."RSI[1]",
                master_data."RSI[1]"  
            ) as "RSI[1]",
		coalesce(
                daily."Stoch.K",
                weekly."Stoch.K",
                monthly."Stoch.K",
                master_data."Stoch.K"  
            ) as "Stoch.K",
		coalesce(
                daily."Stoch.D",
                weekly."Stoch.D",
                monthly."Stoch.D",
                master_data."Stoch.D"  
            ) as "Stoch.D",
		coalesce(
                daily."Stoch.K[1]",
                weekly."Stoch.K[1]",
                monthly."Stoch.K[1]",
                master_data."Stoch.K[1]"  
            ) as "Stoch.K[1]",
		coalesce(
                daily."Stoch.D[1]",
                weekly."Stoch.D[1]",
                monthly."Stoch.D[1]",
                master_data."Stoch.D[1]"  
            ) as "Stoch.D[1]",
		coalesce(
                daily."CCI20",
                weekly."CCI20",
                monthly."CCI20",
                master_data."CCI20"  
            ) as "CCI20",
		coalesce(
                daily."CCI20[1]",
                weekly."CCI20[1]",
                monthly."CCI20[1]",
                master_data."CCI20[1]"  
            ) as "CCI20[1]",
		coalesce(
                daily."ADX",
                weekly."ADX",
                monthly."ADX",
                master_data."ADX"  
            ) as "ADX",
		coalesce(
                daily."ADX+DI",
                weekly."ADX+DI",
                monthly."ADX+DI",
                master_data."ADX+DI"  
            ) as "ADX+DI",
		coalesce(
                daily."ADX-DI",
                weekly."ADX-DI",
                monthly."ADX-DI",
                master_data."ADX-DI"  
            ) as "ADX-DI",
		coalesce(
                daily."ADX+DI[1]",
                weekly."ADX+DI[1]",
                monthly."ADX+DI[1]",
                master_data."ADX+DI[1]"  
            ) as "ADX+DI[1]",
		coalesce(
                daily."ADX-DI[1]",
                weekly."ADX-DI[1]",
                monthly."ADX-DI[1]",
                master_data."ADX-DI[1]"  
            ) as "ADX-DI[1]",
		coalesce(
                daily."AO",
                weekly."AO",
                monthly."AO",
                master_data."AO"  
            ) as "AO",
		coalesce(
                daily."AO[1]",
                weekly."AO[1]",
                monthly."AO[1]",
                master_data."AO[1]"  
            ) as "AO[1]",
		coalesce(
                daily."Mom",
                weekly."Mom",
                monthly."Mom",
                master_data."Mom"  
            ) as "Mom",
		coalesce(
                daily."Mom[1]",
                weekly."Mom[1]",
                monthly."Mom[1]",
                master_data."Mom[1]"  
            ) as "Mom[1]",
		coalesce(
                daily."MACD.macd",
                weekly."MACD.macd",
                monthly."MACD.macd",
                master_data."MACD.macd"  
            ) as "MACD.macd",
		coalesce(
                daily."MACD.signal",
                weekly."MACD.signal",
                monthly."MACD.signal",
                master_data."MACD.signal"  
            ) as "MACD.signal",
		coalesce(
                daily."Rec.Stoch.RSI",
                weekly."Rec.Stoch.RSI",
                monthly."Rec.Stoch.RSI",
                master_data."Rec.Stoch.RSI"  
            ) as "Rec.Stoch.RSI",
		coalesce(
                daily."Stoch.RSI.K",
                weekly."Stoch.RSI.K",
                monthly."Stoch.RSI.K",
                master_data."Stoch.RSI.K"  
            ) as "Stoch.RSI.K",
		coalesce(
                daily."Rec.WR",
                weekly."Rec.WR",
                monthly."Rec.WR",
                master_data."Rec.WR"  
            ) as "Rec.WR",
		coalesce(
                daily."W.R",
                weekly."W.R",
                monthly."W.R",
                master_data."W.R"  
            ) as "W.R",
		coalesce(
                daily."Rec.BBPower",
                weekly."Rec.BBPower",
                monthly."Rec.BBPower",
                master_data."Rec.BBPower"  
            ) as "Rec.BBPower",
		coalesce(
                daily."BBPower",
                weekly."BBPower",
                monthly."BBPower",
                master_data."BBPower"  
            ) as "BBPower",
		coalesce(
                daily."Rec.UO",
                weekly."Rec.UO",
                monthly."Rec.UO",
                master_data."Rec.UO"  
            ) as "Rec.UO",
		coalesce(
                daily."UO",
                weekly."UO",
                monthly."UO",
                master_data."UO"  
            ) as "UO",
		coalesce(
                daily."close",
                weekly."close",
                monthly."close",
                master_data."close"  
            ) as "close",
		coalesce(
                daily."EMA5",
                weekly."EMA5",
                monthly."EMA5",
                master_data."EMA5"  
            ) as "EMA5",
		coalesce(
                daily."SMA5",
                weekly."SMA5",
                monthly."SMA5",
                master_data."SMA5"  
            ) as "SMA5",
		coalesce(
                daily."EMA10",
                weekly."EMA10",
                monthly."EMA10",
                master_data."EMA10"  
            ) as "EMA10",
		coalesce(
                daily."SMA10",
                weekly."SMA10",
                monthly."SMA10",
                master_data."SMA10"  
            ) as "SMA10",
		coalesce(
                daily."EMA20",
                weekly."EMA20",
                monthly."EMA20",
                master_data."EMA20"  
            ) as "EMA20",
		coalesce(
                daily."SMA20",
                weekly."SMA20",
                monthly."SMA20",
                master_data."SMA20"  
            ) as "SMA20",
		coalesce(
                daily."EMA30",
                weekly."EMA30",
                monthly."EMA30",
                master_data."EMA30"  
            ) as "EMA30",
		coalesce(
                daily."SMA30",
                weekly."SMA30",
                monthly."SMA30",
                master_data."SMA30"  
            ) as "SMA30",
		coalesce(
                daily."EMA50",
                weekly."EMA50",
                monthly."EMA50",
                master_data."EMA50"  
            ) as "EMA50",
		coalesce(
                daily."SMA50",
                weekly."SMA50",
                monthly."SMA50",
                master_data."SMA50"  
            ) as "SMA50",
		coalesce(
                daily."EMA100",
                weekly."EMA100",
                monthly."EMA100",
                master_data."EMA100"  
            ) as "EMA100",
		coalesce(
                daily."SMA100",
                weekly."SMA100",
                monthly."SMA100",
                master_data."SMA100"  
            ) as "SMA100",
		coalesce(
                daily."EMA200",
                weekly."EMA200",
                monthly."EMA200",
                master_data."EMA200"  
            ) as "EMA200",
		coalesce(
                daily."SMA200",
                weekly."SMA200",
                monthly."SMA200",
                master_data."SMA200"  
            ) as "SMA200",
		coalesce(
                daily."Rec.Ichimoku",
                weekly."Rec.Ichimoku",
                monthly."Rec.Ichimoku",
                master_data."Rec.Ichimoku"  
            ) as "Rec.Ichimoku",
		coalesce(
                daily."Ichimoku.BLine",
                weekly."Ichimoku.BLine",
                monthly."Ichimoku.BLine",
                master_data."Ichimoku.BLine"  
            ) as "Ichimoku.BLine",
		coalesce(
                daily."Rec.VWMA",
                weekly."Rec.VWMA",
                monthly."Rec.VWMA",
                master_data."Rec.VWMA"  
            ) as "Rec.VWMA",
		coalesce(
                daily."VWMA",
                weekly."VWMA",
                monthly."VWMA",
                master_data."VWMA"  
            ) as "VWMA",
		coalesce(
                daily."Rec.HullMA9",
                weekly."Rec.HullMA9",
                monthly."Rec.HullMA9",
                master_data."Rec.HullMA9"  
            ) as "Rec.HullMA9",
		coalesce(
                daily."HullMA9",
                weekly."HullMA9",
                monthly."HullMA9",
                master_data."HullMA9"  
            ) as "HullMA9",
		coalesce(
                daily."Pivot.M.Classic.S3",
                weekly."Pivot.M.Classic.S3",
                monthly."Pivot.M.Classic.S3",
                master_data."Pivot.M.Classic.S3"  
            ) as "Pivot.M.Classic.S3",
		coalesce(
                daily."Pivot.M.Classic.S2",
                weekly."Pivot.M.Classic.S2",
                monthly."Pivot.M.Classic.S2",
                master_data."Pivot.M.Classic.S2"  
            ) as "Pivot.M.Classic.S2",
		coalesce(
                daily."Pivot.M.Classic.S1",
                weekly."Pivot.M.Classic.S1",
                monthly."Pivot.M.Classic.S1",
                master_data."Pivot.M.Classic.S1"  
            ) as "Pivot.M.Classic.S1",
		coalesce(
                daily."Pivot.M.Classic.Middle",
                weekly."Pivot.M.Classic.Middle",
                monthly."Pivot.M.Classic.Middle",
                master_data."Pivot.M.Classic.Middle"  
            ) as "Pivot.M.Classic.Middle",
		coalesce(
                daily."Pivot.M.Classic.R1",
                weekly."Pivot.M.Classic.R1",
                monthly."Pivot.M.Classic.R1",
                master_data."Pivot.M.Classic.R1"  
            ) as "Pivot.M.Classic.R1",
		coalesce(
                daily."Pivot.M.Classic.R2",
                weekly."Pivot.M.Classic.R2",
                monthly."Pivot.M.Classic.R2",
                master_data."Pivot.M.Classic.R2"  
            ) as "Pivot.M.Classic.R2",
		coalesce(
                daily."Pivot.M.Classic.R3",
                weekly."Pivot.M.Classic.R3",
                monthly."Pivot.M.Classic.R3",
                master_data."Pivot.M.Classic.R3"  
            ) as "Pivot.M.Classic.R3",
		coalesce(
                daily."Pivot.M.Fibonacci.S3",
                weekly."Pivot.M.Fibonacci.S3",
                monthly."Pivot.M.Fibonacci.S3",
                master_data."Pivot.M.Fibonacci.S3"  
            ) as "Pivot.M.Fibonacci.S3",
		coalesce(
                daily."Pivot.M.Fibonacci.S2",
                weekly."Pivot.M.Fibonacci.S2",
                monthly."Pivot.M.Fibonacci.S2",
                master_data."Pivot.M.Fibonacci.S2"  
            ) as "Pivot.M.Fibonacci.S2",
		coalesce(
                daily."Pivot.M.Fibonacci.S1",
                weekly."Pivot.M.Fibonacci.S1",
                monthly."Pivot.M.Fibonacci.S1",
                master_data."Pivot.M.Fibonacci.S1"  
            ) as "Pivot.M.Fibonacci.S1",
		coalesce(
                daily."Pivot.M.Fibonacci.Middle",
                weekly."Pivot.M.Fibonacci.Middle",
                monthly."Pivot.M.Fibonacci.Middle",
                master_data."Pivot.M.Fibonacci.Middle"  
            ) as "Pivot.M.Fibonacci.Middle",
		coalesce(
                daily."Pivot.M.Fibonacci.R1",
                weekly."Pivot.M.Fibonacci.R1",
                monthly."Pivot.M.Fibonacci.R1",
                master_data."Pivot.M.Fibonacci.R1"  
            ) as "Pivot.M.Fibonacci.R1",
		coalesce(
                daily."Pivot.M.Fibonacci.R2",
                weekly."Pivot.M.Fibonacci.R2",
                monthly."Pivot.M.Fibonacci.R2",
                master_data."Pivot.M.Fibonacci.R2"  
            ) as "Pivot.M.Fibonacci.R2",
		coalesce(
                daily."Pivot.M.Fibonacci.R3",
                weekly."Pivot.M.Fibonacci.R3",
                monthly."Pivot.M.Fibonacci.R3",
                master_data."Pivot.M.Fibonacci.R3"  
            ) as "Pivot.M.Fibonacci.R3",
		coalesce(
                daily."Pivot.M.Camarilla.S3",
                weekly."Pivot.M.Camarilla.S3",
                monthly."Pivot.M.Camarilla.S3",
                master_data."Pivot.M.Camarilla.S3"  
            ) as "Pivot.M.Camarilla.S3",
		coalesce(
                daily."Pivot.M.Camarilla.S2",
                weekly."Pivot.M.Camarilla.S2",
                monthly."Pivot.M.Camarilla.S2",
                master_data."Pivot.M.Camarilla.S2"  
            ) as "Pivot.M.Camarilla.S2",
		coalesce(
                daily."Pivot.M.Camarilla.S1",
                weekly."Pivot.M.Camarilla.S1",
                monthly."Pivot.M.Camarilla.S1",
                master_data."Pivot.M.Camarilla.S1"  
            ) as "Pivot.M.Camarilla.S1",
		coalesce(
                daily."Pivot.M.Camarilla.Middle",
                weekly."Pivot.M.Camarilla.Middle",
                monthly."Pivot.M.Camarilla.Middle",
                master_data."Pivot.M.Camarilla.Middle"  
            ) as "Pivot.M.Camarilla.Middle",
		coalesce(
                daily."Pivot.M.Camarilla.R1",
                weekly."Pivot.M.Camarilla.R1",
                monthly."Pivot.M.Camarilla.R1",
                master_data."Pivot.M.Camarilla.R1"  
            ) as "Pivot.M.Camarilla.R1",
		coalesce(
                daily."Pivot.M.Camarilla.R2",
                weekly."Pivot.M.Camarilla.R2",
                monthly."Pivot.M.Camarilla.R2",
                master_data."Pivot.M.Camarilla.R2"  
            ) as "Pivot.M.Camarilla.R2",
		coalesce(
                daily."Pivot.M.Camarilla.R3",
                weekly."Pivot.M.Camarilla.R3",
                monthly."Pivot.M.Camarilla.R3",
                master_data."Pivot.M.Camarilla.R3"  
            ) as "Pivot.M.Camarilla.R3",
		coalesce(
                daily."Pivot.M.Woodie.S3",
                weekly."Pivot.M.Woodie.S3",
                monthly."Pivot.M.Woodie.S3",
                master_data."Pivot.M.Woodie.S3"  
            ) as "Pivot.M.Woodie.S3",
		coalesce(
                daily."Pivot.M.Woodie.S2",
                weekly."Pivot.M.Woodie.S2",
                monthly."Pivot.M.Woodie.S2",
                master_data."Pivot.M.Woodie.S2"  
            ) as "Pivot.M.Woodie.S2",
		coalesce(
                daily."Pivot.M.Woodie.S1",
                weekly."Pivot.M.Woodie.S1",
                monthly."Pivot.M.Woodie.S1",
                master_data."Pivot.M.Woodie.S1"  
            ) as "Pivot.M.Woodie.S1",
		coalesce(
                daily."Pivot.M.Woodie.Middle",
                weekly."Pivot.M.Woodie.Middle",
                monthly."Pivot.M.Woodie.Middle",
                master_data."Pivot.M.Woodie.Middle"  
            ) as "Pivot.M.Woodie.Middle",
		coalesce(
                daily."Pivot.M.Woodie.R1",
                weekly."Pivot.M.Woodie.R1",
                monthly."Pivot.M.Woodie.R1",
                master_data."Pivot.M.Woodie.R1"  
            ) as "Pivot.M.Woodie.R1",
		coalesce(
                daily."Pivot.M.Woodie.R2",
                weekly."Pivot.M.Woodie.R2",
                monthly."Pivot.M.Woodie.R2",
                master_data."Pivot.M.Woodie.R2"  
            ) as "Pivot.M.Woodie.R2",
		coalesce(
                daily."Pivot.M.Woodie.R3",
                weekly."Pivot.M.Woodie.R3",
                monthly."Pivot.M.Woodie.R3",
                master_data."Pivot.M.Woodie.R3"  
            ) as "Pivot.M.Woodie.R3",
		coalesce(
                daily."Pivot.M.Demark.S1",
                weekly."Pivot.M.Demark.S1",
                monthly."Pivot.M.Demark.S1",
                master_data."Pivot.M.Demark.S1"  
            ) as "Pivot.M.Demark.S1",
		coalesce(
                daily."Pivot.M.Demark.Middle",
                weekly."Pivot.M.Demark.Middle",
                monthly."Pivot.M.Demark.Middle",
                master_data."Pivot.M.Demark.Middle"  
            ) as "Pivot.M.Demark.Middle",
		coalesce(
                daily."Pivot.M.Demark.R1",
                weekly."Pivot.M.Demark.R1",
                monthly."Pivot.M.Demark.R1",
                master_data."Pivot.M.Demark.R1"  
            ) as "Pivot.M.Demark.R1",
		coalesce(
                daily."open",
                weekly."open",
                monthly."open",
                master_data."open"  
            ) as "open",
		coalesce(
                daily."P.SAR",
                weekly."P.SAR",
                monthly."P.SAR",
                master_data."P.SAR"  
            ) as "P.SAR",
		coalesce(
                daily."BB.lower",
                weekly."BB.lower",
                monthly."BB.lower",
                master_data."BB.lower"  
            ) as "BB.lower",
		coalesce(
                daily."BB.upper",
                weekly."BB.upper",
                monthly."BB.upper",
                master_data."BB.upper"  
            ) as "BB.upper",
		coalesce(
                daily."AO[2]",
                weekly."AO[2]",
                monthly."AO[2]",
                master_data."AO[2]"  
            ) as "AO[2]",
		coalesce(
                daily."volume",
                weekly."volume",
                monthly."volume",
                master_data."volume"  
            ) as "volume",
		coalesce(
                daily."change",
                weekly."change",
                monthly."change",
                master_data."change"  
            ) as "change",
		coalesce(
                daily."low",
                weekly."low",
                monthly."low",
                master_data."low"  
            ) as "low",
		coalesce(
                daily."high",
                weekly."high",
                monthly."high",
                master_data."high"  
            ) as "high",
		coalesce(
                daily."recommendation",
                weekly."recommendation",
                monthly."recommendation",
                master_data."recommendation"  
            ) as "recommendation",
		coalesce(
                daily."recommendation_buy_amount",
                weekly."recommendation_buy_amount",
                monthly."recommendation_buy_amount",
                master_data."recommendation_buy_amount"  
            ) as "recommendation_buy_amount",
		coalesce(
                daily."recommendation_neutral_amount",
                weekly."recommendation_neutral_amount",
                monthly."recommendation_neutral_amount",
                master_data."recommendation_neutral_amount"  
            ) as "recommendation_neutral_amount",
		coalesce(
                daily."recommendation_sell_amount",
                weekly."recommendation_sell_amount",
                monthly."recommendation_sell_amount",
                master_data."recommendation_sell_amount"  
            ) as "recommendation_sell_amount"
    FROM
        "DatesHistory" as dates
        CROSS JOIN "TechnicalIndicatorsMasterData" as master_data 
        LEFT JOIN "TechnicalIndicatorsHistoryDaily" as daily
        ON dates.date = daily.snapshot_date
        AND master_data."symbol" = daily."symbol"
        LEFT JOIN "TechnicalIndicatorsHistoryWeekly" as weekly 
        ON dates.year = weekly.year
        AND dates.week = weekly.week
        AND master_data."symbol" = weekly."symbol"
        LEFT JOIN "TechnicalIndicatorsHistoryMonthly" as monthly 
        ON dates.year = monthly.year
        AND dates.month = monthly.month
        AND master_data."symbol" = monthly."symbol"
    ;
    