WITH
	MEDIANDIVIDEND AS (
		SELECT
			SYMBOL,
			EXTRACT(YEAR FROM SNAPSHOT_DATE) AS DIV_YEAR,
			PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY DIVIDENDS) AS MEDIAN_DIVIDEND,
			COUNT(*) AS DIVIDENDS_PAID
		FROM
			"StockPricesYahooHistoryDaily"
		WHERE
			DIVIDENDS > 0
			AND SNAPSHOT_DATE <= '2026-06-26'::DATE
		GROUP BY
			SYMBOL,
			DIV_YEAR
	),
	MEDIANDIVIDEND2 AS (
		SELECT
			*,
			LAG(DIVIDENDS_PAID) OVER (
				PARTITION BY SYMBOL
				ORDER BY DIV_YEAR
			) DIVIDENDS_PAID_PREV,
			LEAD(DIVIDENDS_PAID) OVER (
				PARTITION BY SYMBOL
				ORDER BY DIV_YEAR
			) DIVIDENDS_PAID_NEXT
		FROM
			MEDIANDIVIDEND
	),
	CLEANEDDATA AS (
		SELECT
			A.SYMBOL,
			EXTRACT(YEAR FROM A.SNAPSHOT_DATE) AS DIV_YEAR,
			A.DIVIDENDS,
			CASE
				WHEN B.DIVIDENDS_PAID = 2 AND B.DIVIDENDS_PAID_NEXT = 4
				OR B.DIVIDENDS_PAID_PREV = 2 AND B.DIVIDENDS_PAID = 4 THEN TRUE
				ELSE FALSE
			END AS DIVIDEND_SCHEDULE_CHANGED
		FROM
			"StockPricesYahooHistoryDaily" AS A
			INNER JOIN MEDIANDIVIDEND2 AS B 
				ON A.SYMBOL = B.SYMBOL
				AND EXTRACT(YEAR FROM A.SNAPSHOT_DATE) = B.DIV_YEAR
		WHERE
			A.DIVIDENDS > 0
			AND A.SNAPSHOT_DATE <= '2026-06-26'::DATE
			AND (
				ABS(((A.DIVIDENDS - B.MEDIAN_DIVIDEND)::NUMERIC / NULLIF(B.MEDIAN_DIVIDEND, 0)) * 100) < 25
				OR (B.DIVIDENDS_PAID = 2 AND B.DIVIDENDS_PAID_NEXT = 4)
				OR (B.DIVIDENDS_PAID_PREV = 2 AND B.DIVIDENDS_PAID = 4)
			)
	),
	YEARLYSUMS AS (
		SELECT
			SYMBOL,
			DIV_YEAR,
			AVG(DIVIDENDS) AS ANNUAL_AVG_DIV,
			SUM(DIVIDENDS) AS ANNUAL_DIV,
			BOOL_OR(DIVIDEND_SCHEDULE_CHANGED) AS DIVIDEND_SCHEDULE_CHANGED
		FROM
			CLEANEDDATA
		GROUP BY
			SYMBOL,
			DIV_YEAR
	),
	-- NEU: Zwischenschritt zur Ermittlung des Wachstums (verhindert Verschachtelung)
	GROWTH_BASE AS (
		SELECT
			SYMBOL,
			DIV_YEAR,
			CASE
				WHEN ANNUAL_AVG_DIV > LAG(ANNUAL_AVG_DIV) OVER (PARTITION BY SYMBOL ORDER BY DIV_YEAR)
				OR DIVIDEND_SCHEDULE_CHANGED THEN 1
				ELSE 0
			END AS IS_INCREASE
		FROM
			YEARLYSUMS
	),
	GROWTHCHECK AS (
		SELECT
			SYMBOL,
			DIV_YEAR,
			-- Jetzt können wir die laufende Summe sicher anwenden
			SUM(CASE WHEN IS_INCREASE = 1 THEN 0 ELSE 1 END) OVER (
				PARTITION BY SYMBOL 
				ORDER BY DIV_YEAR DESC
			) AS DROPS_AHEAD
		FROM
			GROWTH_BASE
	),
	STREAKS AS (
		SELECT
			SYMBOL,
			COUNT(*) AS YEARS_OF_GROWTH
		FROM
			GROWTHCHECK
		WHERE
			DROPS_AHEAD = 0
		GROUP BY
			SYMBOL
	)
SELECT
	SYMBOL,
	YEARS_OF_GROWTH,
	CASE
		WHEN YEARS_OF_GROWTH >= 25 THEN 'Dividend Champion'
		WHEN YEARS_OF_GROWTH >= 10 THEN 'Dividend Contender'
		WHEN YEARS_OF_GROWTH >= 5 THEN 'Dividend Challenger'
		ELSE 'None'
	END AS CLASSIFICATION
FROM
	STREAKS;