DROP VIEW IF EXISTS FundamentalData;

CREATE VIEW FundamentalData AS
SELECT 
	a."Symbol", 
	a."Company", 
	a."FV", 
	a."Sector", 
	a."No-Years", 
	a."Price", 
	a."Div-Yield", 
	a."5Y-Avg-Yield", 
	a."Current-Div", 
	a."Payouts/-Year", 
	a."Annualized", 
	a."Previous-Div", 
	a."Ex-Date", 
	a."Pay-Date", 
	a."Low", 
	a."High", 
	a."DGR-1Y", 
	a."DGR-3Y", 
	a."DGR-5Y", 
	a."DGR-10Y", 
	a."TTR-1Y", 
	a."TTR-3Y", 
	a."Fair-Value", 
	a."FV-%", 
	a."Streak-Basis", 
	a."Chowder-Number", 
	a."EPS-1Y", 
	a."Revenue-1Y", 
	a."NPM", 
	a."CF/Share", 
	a."ROE", 
	a."Current-R", 
	a."Debt/Capital", 
	a."ROTC", 
	a."P/E", 
	a."P/BV", 
	a."PEG", 
	a."New-Member", 
	a."Industry", 
	a."Classification",

    b."EnterpriseValue", 
	b."ForwardPE", 
	b."TrailingEps", 
	b."PriceToBook", 
	b."TotalRevenue", 
	b."EBITDA", 
	b."FreeCashFlow", 
	b."TotalDebt", 
	b."NetIncome", 
	b."ROE", 
	b."ROA", 
	b."CurrentPrice", 
	b."MarketCap", 
	b."Volume", 
	b."AverageVolume", 
	b."Yahoo_DividendYield", 
	b."DividendRate", 
	b."TrailingAnnualDividendRate", 
	b."PayoutRatio", 
	b."ExDividendDate", 
	b."PE_Ratio_Calc", 
	b."PS_Ratio", 
	b."DebtToMarketCap", 
	b."EV_EBITDA_Approx"
FROM 
    FundamentalDataDividendRadar AS a
JOIN 
    FundamentalDataYahooProcessed as b
ON a."Symbol" = b.symbol;