
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "AnalystPriceTargetsHistoryMonthly" (
        year INT NOT NULL,
        month INT NOT NULL,
        "symbol" TEXT,
        "analyst_mean_target" DOUBLE PRECISION,
        PRIMARY KEY(year, month, "symbol")
    );
    