
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "AnalystPriceTargetsMasterData" (
        "symbol" TEXT,
        "analyst_mean_target" FLOAT,
        PRIMARY KEY("symbol")
    );
    