
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "AnalystPriceTargetsMasterData" (
        from_date DATE NOT NULL,
        to_date DATE NOT NULL,
        "symbol" TEXT,
        "analyst_mean_target" DOUBLE PRECISION,
        PRIMARY KEY("symbol")
    );
    