
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "AnalystPriceTargetsHistoryWeekly" (
        year INT NOT NULL,
        week INT NOT NULL,
        "symbol" TEXT,
        "analyst_mean_target" FLOAT,
        PRIMARY KEY(year, week, "symbol")
    );
    