
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "AnalystPriceTargetsHistoryWeekly" (
        isoyear INT NOT NULL,
        week INT NOT NULL,
        "symbol" TEXT,
        "analyst_mean_target" FLOAT,
        PRIMARY KEY(isoyear, week, "symbol")
    );
    