
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "DividendDataYahooHistoryWeekly" (
        isoyear INT NOT NULL,
        week INT NOT NULL,
        "symbol" TEXT,
        "years_of_growth" smallint,
		"classification" TEXT,
        PRIMARY KEY(isoyear, week, "symbol")
    );
    