
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "DividendDataYahooMasterData" (
        from_date DATE NOT NULL,
        to_date DATE NOT NULL,
        "symbol" TEXT,
        "years_of_growth" SMALLINT,
		"classification" TEXT,
        PRIMARY KEY("symbol")
    );
    