
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "DividendDataYahooHistoryMonthly" (
        year INT NOT NULL,
        month INT NOT NULL,
        "symbol" TEXT,
        "years_of_growth" SMALLINT,
		"classification" TEXT,
        PRIMARY KEY(year, month, "symbol")
    );
    