
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "EarningDatesHistoryMonthly" (
        year INT NOT NULL,
        month INT NOT NULL,
        "symbol" TEXT,
        "earnings_date" DATE,
        PRIMARY KEY(year, month, "symbol")
    );
    