
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "EarningDatesHistoryWeekly" (
        isoyear INT NOT NULL,
        week INT NOT NULL,
        "symbol" TEXT,
        "earnings_date" TEXT,
        PRIMARY KEY(isoyear, week, "symbol")
    );
    