
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "EarningDatesHistoryWeekly" (
        year INT NOT NULL,
        week INT NOT NULL,
        "symbol" TEXT,
        "earnings_date" TEXT,
        PRIMARY KEY(year, week, "symbol")
    );
    