
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "EarningDatesMasterData" (
        from_date DATE NOT NULL,
        to_date DATE NOT NULL,
        "symbol" TEXT,
        "earnings_date" TEXT,
        PRIMARY KEY("symbol")
    );
    