
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "EarningDatesHistoryDaily" (
        snapshot_date DATE NOT NULL,
        "symbol" TEXT,
        "earnings_date" TEXT,
        PRIMARY KEY(snapshot_date, "symbol")
    );
    