
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "OptionDataMassiveMasterData" (
        from_date DATE NOT NULL,
        to_date DATE NOT NULL,
        "option_osi" TEXT,
        "symbol" TEXT,
		"contract_type" TEXT,
		"expiration_date" TEXT,
		"strike_price" DOUBLE PRECISION,
		"open_interest" BIGINT,
		"implied_volatility" DOUBLE PRECISION,
		"exercise_style" TEXT,
		"shares_per_contract" BIGINT,
		"greeks_delta" DOUBLE PRECISION,
		"greeks_gamma" DOUBLE PRECISION,
		"greeks_theta" DOUBLE PRECISION,
		"greeks_vega" DOUBLE PRECISION,
		"day_change" DOUBLE PRECISION,
		"day_change_percent" DOUBLE PRECISION,
		"day_close" DOUBLE PRECISION,
		"day_high" DOUBLE PRECISION,
		"day_low" DOUBLE PRECISION,
		"day_open" DOUBLE PRECISION,
		"day_previous_close" DOUBLE PRECISION,
		"day_volume" DOUBLE PRECISION,
		"day_vwap" DOUBLE PRECISION,
		"day_last_updated" TIMESTAMP WITHOUT TIME ZONE,
        PRIMARY KEY("option_osi")
    );
    