
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "OptionDataTradingViewHistoryMonthly" (
        year INT NOT NULL,
        month INT NOT NULL,
        "option_osi" TEXT,
        "symbol" TEXT,
			"option-type" TEXT,
			"expiration_date" BIGINT,
			"strike" FLOAT,
			"ask" FLOAT,
			"bid" FLOAT,
			"delta" FLOAT,
			"gamma" FLOAT,
			"iv" FLOAT,
			"rho" FLOAT,
			"theoPrice" FLOAT,
			"theta" FLOAT,
			"vega" FLOAT,
			"option" TEXT,
			"time" TEXT,
			"exchange" TEXT,
        PRIMARY KEY(year, month, "option_osi")
    );
    