
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "OptionDataYahooHistoryWeekly" (
        year INT NOT NULL,
        week INT NOT NULL,
        "contractSymbol" TEXT,
        "symbol" TEXT,
			"option-type" TEXT,
			"expiration_date" DATETIME,
			"strike" FLOAT,
			"currency" TEXT,
			"lastPrice" FLOAT,
			"change" FLOAT,
			"percentChange" FLOAT,
			"option_open_interest" BIGINT,
			"bid" FLOAT,
			"ask" FLOAT,
			"contractSize" TEXT,
			"lastTradeDate" DATETIME,
			"impliedVolatility" FLOAT,
			"inTheMoney" BOOLEAN,
			"option_volume" FLOAT,
        PRIMARY KEY(year, week, "contractSymbol")
    );
    