
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "StockPricesYahooMasterData" (
        from_date DATE NOT NULL,
        to_date DATE NOT NULL,
        "symbol" TEXT,
        "open" DOUBLE PRECISION,
		"high" DOUBLE PRECISION,
		"low" DOUBLE PRECISION,
		"close" DOUBLE PRECISION,
		"volume" BIGINT,
		"adjclose" DOUBLE PRECISION,
		"dividends" REAL,
		"splits" DOUBLE PRECISION,
        PRIMARY KEY("symbol")
    );
    