
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "StockImpliedVolatilityMassiveHistoryMonthly" (
        year INT NOT NULL,
        month INT NOT NULL,
        "symbol" TEXT,
        "iv" double precision,
		"iv_low" double precision,
		"iv_high" double precision,
		"iv_rank" double precision,
		"iv_percentile" double precision,
        PRIMARY KEY(year, month, "symbol")
    );
    