
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "StockDataBarchartMasterData" (
        "symbol" TEXT,
        "implied_volatility" FLOAT,
			"historical_volatility" FLOAT,
			"iv_percentile" FLOAT,
			"iv_rank" FLOAT,
			"iv_high" FLOAT,
			"iv_low" FLOAT,
			"put_call_vol_ratio" FLOAT,
			"put_call_oi_ratio" FLOAT,
			"todays_volume" BIGINT,
			"volume_avg_30d" BIGINT,
			"todays_open_interest" BIGINT,
			"open_int_30d" BIGINT,
        PRIMARY KEY("symbol")
    );
    