
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "StockHistoricalVolatilityYahooMasterData" (
        from_date DATE NOT NULL,
        to_date DATE NOT NULL,
        "symbol" TEXT,
        "historical_volatility_30d" DOUBLE PRECISION,
        PRIMARY KEY("symbol")
    );
    