
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "StockAssetProfilesYahooHistoryDaily" (
        snapshot_date DATE NOT NULL,
        "symbol" TEXT,
        "name" TEXT,
		"industry" TEXT,
		"sector" TEXT,
		"country" TEXT,
		"long_business_summary" TEXT,
        PRIMARY KEY(snapshot_date, "symbol")
    );
    