
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "StockHistoricalVolatilityYahooHistoryDaily" (
        snapshot_date DATE NOT NULL,
        "symbol" TEXT,
        "historical_volatility_30d" DOUBLE PRECISION,
        PRIMARY KEY(snapshot_date, "symbol")
    );
    