
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "StockAssetProfilesYahooHistoryWeekly" (
        isoyear INT NOT NULL,
        week INT NOT NULL,
        "symbol" TEXT,
        "name" TEXT,
		"industry" TEXT,
		"sector" TEXT,
		"country" TEXT,
		"long_business_summary" TEXT,
        PRIMARY KEY(isoyear, week, "symbol")
    );
    