
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "StockPriceHistoryMonthly" (
        year INT NOT NULL,
        month INT NOT NULL,
        "symbol" TEXT,
        "live_stock_price" FLOAT,
		"price_source" TEXT,
		"live_price_timestamp" DATETIME,
        PRIMARY KEY(year, month, "symbol")
    );
    