
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "StockPriceMasterData" (
        "symbol" TEXT,
        "live_stock_price" FLOAT,
		"price_source" TEXT,
		"live_price_timestamp" DATETIME,
        PRIMARY KEY("symbol")
    );
    