
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "StockImpliedVolatilityMassiveHistoryWeekly" (
        isoyear INT NOT NULL,
        week INT NOT NULL,
        "symbol" TEXT,
        "iv" double precision,
		"iv_low" double precision,
		"iv_high" double precision,
		"iv_rank" double precision,
		"iv_percentile" double precision,
        PRIMARY KEY(isoyear, week, "symbol")
    );
    