
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "StockPricesYahooHistoryWeekly" (
        isoyear INT NOT NULL,
        week INT NOT NULL,
        "symbol" TEXT,
        "open" DOUBLE PRECISION,
		"high" DOUBLE PRECISION,
		"low" DOUBLE PRECISION,
		"close" DOUBLE PRECISION,
		"volume" BIGINT,
		"adjclose" DOUBLE PRECISION,
		"dividends" DOUBLE PRECISION,
		"splits" DOUBLE PRECISION,
        PRIMARY KEY(isoyear, week, "symbol")
    );
    