
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "StockImpliedVolatilityMassiveHistoryWeekly" (
        isoyear INT NOT NULL,
        week INT NOT NULL,
        "symbol" TEXT,
        "iv" DOUBLE PRECISION,
		"iv_low" DOUBLE PRECISION,
		"iv_high" DOUBLE PRECISION,
		"iv_rank" DOUBLE PRECISION,
		"iv_percentile" DOUBLE PRECISION,
        PRIMARY KEY(isoyear, week, "symbol")
    );
    