
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "StockImpliedVolatilityMassiveMasterData" (
        from_date DATE NOT NULL,
        to_date DATE NOT NULL,
        "symbol" TEXT,
        "iv" double precision,
		"iv_low" double precision,
		"iv_high" double precision,
		"iv_rank" double precision,
		"iv_percentile" double precision,
        PRIMARY KEY("symbol")
    );
    