
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "StockImpliedVolatilityMassiveMasterData" (
        from_date DATE NOT NULL,
        to_date DATE NOT NULL,
        "symbol" TEXT,
        "iv" DOUBLE PRECISION,
		"iv_low" DOUBLE PRECISION,
		"iv_high" DOUBLE PRECISION,
		"iv_rank" DOUBLE PRECISION,
		"iv_percentile" DOUBLE PRECISION,
        PRIMARY KEY("symbol")
    );
    