
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "StockPriceHistoryWeekly" (
        year INT NOT NULL,
        week INT NOT NULL,
        "symbol" TEXT,
        "live_stock_price" FLOAT,
		"price_source" TEXT,
		"live_price_timestamp" DATETIME,
        PRIMARY KEY(year, week, "symbol")
    );
    