
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "StockHistoricalVolatilityYahooHistoryWeekly" (
        isoyear INT NOT NULL,
        week INT NOT NULL,
        "symbol" TEXT,
        "historical_volatility_30d" DOUBLE PRECISION,
        PRIMARY KEY(isoyear, week, "symbol")
    );
    