
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "StockHistoricalVolatilityYahooHistoryMonthly" (
        year INT NOT NULL,
        month INT NOT NULL,
        "symbol" TEXT,
        "historical_volatility_30d" DOUBLE PRECISION,
        PRIMARY KEY(year, month, "symbol")
    );
    