
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "StockImpliedVolatilityMassiveHistoryDaily" (
        snapshot_date DATE NOT NULL,
        "symbol" TEXT,
        "iv" DOUBLE PRECISION,
		"iv_low" DOUBLE PRECISION,
		"iv_high" DOUBLE PRECISION,
		"iv_rank" DOUBLE PRECISION,
		"iv_percentile" DOUBLE PRECISION,
        PRIMARY KEY(snapshot_date, "symbol")
    );
    