
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "StockPriceHistoryDaily" (
        snapshot_date DATE NOT NULL,
        "symbol" TEXT,
        "live_stock_price" FLOAT,
		"price_source" TEXT,
		"live_price_timestamp" DATETIME,
        PRIMARY KEY(snapshot_date, "symbol")
    );
    