
    -- generated by HistorizationService
    CREATE TABLE IF NOT EXISTS "StockAssetProfilesYahooHistoryMonthly" (
        year INT NOT NULL,
        month INT NOT NULL,
        "symbol" TEXT,
        "name" TEXT,
		"industry" TEXT,
		"sector" TEXT,
		"country" TEXT,
		"long_business_summary" TEXT,
        PRIMARY KEY(year, month, "symbol")
    );
    