DROP VIEW IF EXISTS "DividendData" CASCADE;

CREATE VIEW "DividendData" AS
SELECT
	A.SYMBOL,
	A.YEARS_OF_GROWTH AS DIVIDEND_GROWTH_YEARS,
	A.CLASSIFICATION AS DIVIDEND_CLASSIFICATION,
	B.LAST_DIVIDEND,
    B.LAST_DIVIDEND_DATE,
	C.NO_DIVIDEND_PAYOUTS_LAST_YEAR
FROM
	"DividendDataYahoo" AS A
	LEFT OUTER JOIN (
		SELECT DISTINCT
			ON (SYMBOL) SYMBOL,
			DIVIDENDS AS LAST_DIVIDEND,
            SNAPSHOT_DATE AS LAST_DIVIDEND_DATE
		FROM
			"StockPricesYahooHistoryDaily"
		WHERE
			DIVIDENDS > 0
		ORDER BY
			SYMBOL,
			SNAPSHOT_DATE DESC
	) AS B ON A.SYMBOL = B.SYMBOL
	LEFT OUTER JOIN (
		SELECT
			SYMBOL,
			COUNT(*) AS NO_DIVIDEND_PAYOUTS_LAST_YEAR
		FROM
			"StockPricesYahooHistoryDaily"
		WHERE
			DIVIDENDS > 0
			AND SNAPSHOT_DATE > CURRENT_DATE - INTERVAL '1 year'
		GROUP BY
			SYMBOL
	) AS C ON A.SYMBOL = C.SYMBOL