DROP VIEW IF EXISTS  "IvMetrics";
CREATE OR REPLACE VIEW "IvMetrics" AS
WITH
	IV_STATS AS (
		SELECT
			SYMBOL,
			SNAPSHOT_DATE AS TRADE_DATE,
			IMPLIED_VOLATILITY,
			-- Avg, Min und Max der letzten 252 Zeilen (1 Jahr)
			AVG(IMPLIED_VOLATILITY) OVER (
				PARTITION BY
					SYMBOL
				ORDER BY
					SNAPSHOT_DATE ROWS BETWEEN 251 PRECEDING
					AND CURRENT ROW
			) AS AVG_IV_YEAR,
			MIN(IMPLIED_VOLATILITY) OVER (
				PARTITION BY
					SYMBOL
				ORDER BY
					SNAPSHOT_DATE ROWS BETWEEN 251 PRECEDING
					AND CURRENT ROW
			) AS MIN_IV_YEAR,
			MAX(IMPLIED_VOLATILITY) OVER (
				PARTITION BY
					SYMBOL
				ORDER BY
					SNAPSHOT_DATE ROWS BETWEEN 251 PRECEDING
					AND CURRENT ROW
			) AS MAX_IV_YEAR,
			-- Abstand zum Durchschnitt in Prozent
			ROUND(
				CAST(
					(
						IMPLIED_VOLATILITY / NULLIF(
							AVG(IMPLIED_VOLATILITY) OVER (
								PARTITION BY
									SYMBOL
								ORDER BY
									SNAPSHOT_DATE ROWS BETWEEN 251 PRECEDING
									AND CURRENT ROW
							),
							0
						) - 1
					) * 100 AS NUMERIC
				),
				2
			) AS PCT_ABOVE_AVG,
			-- Für Percentile: Alle Werte des letzten Jahres in ein Array/Fenster laden
			-- In Standard-SQL nutzen wir eine Unterabfrage oder CUME_DIST
			CUME_DIST() OVER (
				PARTITION BY
					SYMBOL
				ORDER BY
					IMPLIED_VOLATILITY
			) AS PERCENTILE_VAL
		FROM
			"OptionDataMassiveHistoryDaily"
	)
SELECT
	SYMBOL,
	TRADE_DATE,
	IMPLIED_VOLATILITY AS CURRENT_IV,
	AVG_IV_YEAR AS HISTORY_IV,
	PCT_ABOVE_AVG,
	MIN_IV_YEAR,
	MAX_IV_YEAR,
	-- Berechnung IV Rank: (Aktuell - Min) / (Max - Min) * 100
	ROUND(
		CAST(
			(IMPLIED_VOLATILITY - MIN_IV_YEAR) / NULLIF(MAX_IV_YEAR - MIN_IV_YEAR, 0) * 100 AS NUMERIC
		),
		2
	) AS IV_RANK,
	-- IV Percentile: Wie viel % der Tage waren niedriger als heute
	ROUND(CAST(PERCENTILE_VAL * 100 AS NUMERIC), 2) AS IV_PERCENTILE
FROM
	IV_STATS;