DROP VIEW IF EXISTS "OptionPricingMetrics" CASCADE;
CREATE VIEW
    "OptionPricingMetrics" AS
SELECT
	SYMBOL,
	OPTION_OSI,
	DAYS_TO_EXPIRATION,
	ROUND(PREMIUM_OPTION_PRICE::NUMERIC, 2) AS PREMIUM_OPTION_PRICE,
	SPREAD,
	SPREAD_PTC,
	ROUND(INTRINSIC_VALUE::NUMERIC, 2) AS INTRINSIC_VALUE,
	ROUND(
		(PREMIUM_OPTION_PRICE - INTRINSIC_VALUE)::NUMERIC,
		2
	) AS EXTRINSIC_VALUE,
	STRIKE_STOCK_PRICE_DIFFERENCE,
	STRIKE_STOCK_PRICE_DIFFERENCE_PTC
FROM
	(
		SELECT
			A.SYMBOL,
			A.OPTION_OSI,
			(A.EXPIRATION_DATE::DATE - CURRENT_DATE) AS DAYS_TO_EXPIRATION,
			C.LIVE_STOCK_PRICE,
			ROUND(
				(A."strike_price" - C.LIVE_STOCK_PRICE)::NUMERIC,
				2
			) AS STRIKE_STOCK_PRICE_DIFFERENCE,
			ROUND(
				(
					(A."strike_price" - C.LIVE_STOCK_PRICE) / NULLIF(C.LIVE_STOCK_PRICE, 0) * 100
				)::NUMERIC,
				2
			) AS STRIKE_STOCK_PRICE_DIFFERENCE_PTC,
			CASE
				WHEN A."contract_type" = 'call' THEN GREATEST(C.LIVE_STOCK_PRICE - A."strike_price", 0)
				WHEN A."contract_type" = 'put' THEN GREATEST(A."strike_price" - C.LIVE_STOCK_PRICE, 0)
				ELSE NULL
			END AS INTRINSIC_VALUE,
			(B.ASK + B.BID) / 2 AS PREMIUM_OPTION_PRICE,
			B.ASK - B.BID AS SPREAD,
			ROUND(
				((B.ASK - B.BID) / NULLIF(B.BID, 0) * 100)::NUMERIC,
				2
			) AS SPREAD_PTC
		FROM
			"OptionDataMassive" AS A
			JOIN "OptionDataYahoo" AS B ON A.OPTION_OSI = B."contractSymbol"
			JOIN "StockPrice" AS C ON A.SYMBOL = C.SYMBOL
	);