DROP VIEW IF EXISTS "OptionPricingMetrics" CASCADE;
CREATE VIEW
    "OptionPricingMetrics" AS
SELECT
	SYMBOL,
	OPTION_OSI,
	DAYS_TO_EXPIRATION,
	ROUND(PREMIUM_OPTION_PRICE::NUMERIC, 2) AS PREMIUM_OPTION_PRICE,
	NULL AS SPREAD,
	NULL AS SPREAD_PTC,
	ROUND(INTRINSIC_VALUE::NUMERIC, 2) AS INTRINSIC_VALUE,
	ROUND(
		(PREMIUM_OPTION_PRICE - INTRINSIC_VALUE)::NUMERIC,
		2
	) AS EXTRINSIC_VALUE,
	STRIKE_STOCK_PRICE_DIFFERENCE,
	STRIKE_STOCK_PRICE_DIFFERENCE_PTC
FROM
	(
		SELECT
			A.SYMBOL,
			A.OPTION_OSI,
			CASE WHEN (A.EXPIRATION_DATE::DATE - CURRENT_DATE) >= 0 THEN (A.EXPIRATION_DATE::DATE - CURRENT_DATE) ELSE NULL END AS DAYS_TO_EXPIRATION,
			ROUND(
				(A."strike_price" - C.close)::NUMERIC,
				2
			) AS STRIKE_STOCK_PRICE_DIFFERENCE,
			ROUND(
				(
					(A."strike_price" - C.close) / NULLIF(C.close, 0) * 100
				)::NUMERIC,
				2
			) AS STRIKE_STOCK_PRICE_DIFFERENCE_PTC,
			CASE
				WHEN A."contract_type" = 'call' THEN GREATEST(C.close - A."strike_price", 0)
				WHEN A."contract_type" = 'put' THEN GREATEST(A."strike_price" - C.close, 0)
				ELSE NULL
			END AS INTRINSIC_VALUE,
			a.day_close AS PREMIUM_OPTION_PRICE
			-- B.ASK - B.BID AS SPREAD,
			-- ROUND(
			-- 	((B.ASK - B.BID) / NULLIF(B.BID, 0) * 100)::NUMERIC,
			-- 	2
			-- ) AS SPREAD_PTC
		FROM
			"OptionDataMassive" AS A
			LEFT OUTER JOIN "StockPricesYahoo" AS C ON A.SYMBOL = C.SYMBOL
	) AS OPTION_PRICING_DATA;