DROP VIEW IF EXISTS "StockData" CASCADE;

CREATE VIEW
    "StockData" AS
SELECT
	A.SYMBOL,
	A.LIVE_STOCK_PRICE,
	A.PRICE_SOURCE,
	A.LIVE_PRICE_TIMESTAMP,
	CASE
		WHEN B.SYMBOL IS NOT NULL THEN TRUE
		ELSE FALSE
	END AS HAS_EARNINGS_DATE,
	B.EARNINGS_DATE,
	CAST(B.EARNINGS_DATE::DATE - CURRENT_DATE AS INTEGER) AS DAYS_TO_ERNINGS,
	CASE
		WHEN C.SYMBOL IS NOT NULL THEN TRUE
		ELSE FALSE
	END AS HAS_ANALYST_PRICE_TARGET,
	C.ANALYST_MEAN_TARGET,
	-- Barchart Data
	D.IMPLIED_VOLATILITY,
	D.HISTORICAL_VOLATILITY,
	D.IV_PERCENTILE,
	D.IV_RANK,
	D.IV_HIGH,
	D.IV_LOW,
	D.PUT_CALL_VOL_RATIO,
	D.PUT_CALL_OI_RATIO,
	D.TODAYS_VOLUME,
	D.VOLUME_AVG_30D,
	D.TODAYS_OPEN_INTEREST,
	D.OPEN_INT_30D
FROM
	"StockPrice" AS A
	LEFT OUTER JOIN (
		SELECT
			SYMBOL,
			CASE
				WHEN EARNINGS_DATE LIKE '%.%.%' THEN SUBSTR(EARNINGS_DATE, 7, 4) || '-' || SUBSTR(EARNINGS_DATE, 4, 2) || '-' || SUBSTR(EARNINGS_DATE, 1, 2)
				ELSE NULL
			END AS EARNINGS_DATE
		FROM
			"EarningDates"
	) AS B ON A.SYMBOL = B.SYMBOL
	LEFT OUTER JOIN "AnalystPriceTargets" AS C ON A.SYMBOL = C.SYMBOL
	LEFT OUTER JOIN "StockDataBarchart" AS D ON A.SYMBOL = D.SYMBOL;