name: Run Pipeline

on:
  push:
    branches: [ "dividend_feather" ]
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1-5"   # Every weekday (Mon-Fri) at 10:00 CET (09:00 UTC)
    - cron: "0 15 * * 1-5"  # Every weekday (Mon-Fri) at 16:00 CET (15:00 UTC)

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create service account file
        run: echo "$SERVICE_ACCOUNT_JSON" > service_account.json
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}

      - name: Run main script 
        run: |
          python main.py 
