
        -- generated by HistorizationService
        CREATE OR REPLACE FUNCTION
            "getDividendDataHistory"(p_target_date date)
        RETURNS TABLE ("symbol" TEXT,
		"dividend_growth_years" SMALLINT,
		"dividend_classification" TEXT,
		"last_dividend" DOUBLE PRECISION,
		"last_dividend_date" DATE,
		"no_dividend_payouts_last_year" BIGINT)
        AS
        $$
             SELECT a.symbol,
    a.years_of_growth AS dividend_growth_years,
    a.classification AS dividend_classification,
    b.last_dividend,
    b.last_dividend_date,
    c.no_dividend_payouts_last_year
   FROM (("getDividendDataYahooHistory"(p_target_date) a
     LEFT JOIN ( SELECT DISTINCT ON (sp.symbol) sp.symbol,
            sp.dividends AS last_dividend,
            sp.snapshot_date AS last_dividend_date
           FROM "StockPricesYahooHistoryDaily" sp
          WHERE ((sp.dividends > (0)::double precision) AND (sp.snapshot_date > (p_target_date - '1 year'::interval)) AND (sp.snapshot_date <= p_target_date))
          ORDER BY sp.symbol, sp.snapshot_date DESC) b ON ((a.symbol = b.symbol)))
     LEFT JOIN ( SELECT sp.symbol,
            count(*) AS no_dividend_payouts_last_year
           FROM "StockPricesYahooHistoryDaily" sp
          WHERE ((sp.dividends > (0)::double precision) AND (sp.snapshot_date > (p_target_date - '1 year'::interval)) AND (sp.snapshot_date <= p_target_date))
          GROUP BY sp.symbol) c ON ((a.symbol = c.symbol)));
        $$
        LANGUAGE sql STABLE;
                