
        -- generated by HistorizationService
        CREATE OR REPLACE FUNCTION
            "getOptionDataHistory"(p_target_date date)
        RETURNS TABLE ("option_osi" TEXT,
		"symbol" TEXT,
		"contract_type" TEXT,
		"expiration_date" DATE,
		"strike_price" DOUBLE PRECISION,
		"open_interest" BIGINT,
		"implied_volatility" DOUBLE PRECISION,
		"exercise_style" TEXT,
		"shares_per_contract" BIGINT,
		"greeks_delta" DOUBLE PRECISION,
		"greeks_gamma" DOUBLE PRECISION,
		"greeks_theta" DOUBLE PRECISION,
		"greeks_vega" DOUBLE PRECISION,
		"day_change" DOUBLE PRECISION,
		"day_change_percent" DOUBLE PRECISION,
		"day_close" DOUBLE PRECISION,
		"day_high" DOUBLE PRECISION,
		"day_low" DOUBLE PRECISION,
		"day_open" DOUBLE PRECISION,
		"day_previous_close" DOUBLE PRECISION,
		"day_volume" DOUBLE PRECISION,
		"day_vwap" DOUBLE PRECISION,
		"day_last_updated" TIMESTAMP WITHOUT TIME ZONE,
		"days_to_expiration" INTEGER,
		"premium_option_price" NUMERIC,
		"intrinsic_value" NUMERIC,
		"extrinsic_value" NUMERIC,
		"strike_stock_price_difference" NUMERIC,
		"strike_stock_price_difference_ptc" NUMERIC,
		"last_updated_option_data" TEXT)
        AS
        $$
             SELECT a.option_osi,
    a.symbol,
    a.contract_type,
    a.expiration_date,
    a.strike_price,
    a.open_interest,
    a.implied_volatility,
    a.exercise_style,
    a.shares_per_contract,
    a.greeks_delta,
    a.greeks_gamma,
    a.greeks_theta,
    a.greeks_vega,
    a.day_change,
    a.day_change_percent,
    a.day_close,
    a.day_high,
    a.day_low,
    a.day_open,
    a.day_previous_close,
    a.day_volume,
    a.day_vwap,
    a.day_last_updated,
        CASE
            WHEN ((a.expiration_date - p_target_date) >= 0) THEN (a.expiration_date - p_target_date)
            ELSE 0
        END AS days_to_expiration,
    d.premium_option_price,
    d.intrinsic_value,
    d.extrinsic_value,
    d.strike_stock_price_difference,
    d.strike_stock_price_difference_ptc,
    ''::text AS last_updated_option_data
   FROM ("getOptionDataMassiveHistory"(p_target_date) a
     LEFT JOIN "getOptionPricingMetricsHistory"(p_target_date) d ON (((a.option_osi = d.option_osi) AND (a.symbol = d.symbol))));
        $$
        LANGUAGE sql STABLE;
                