
        -- generated by HistorizationService
        CREATE OR REPLACE FUNCTION
            "getOptionPricingMetricsHistory"(p_target_date date)
        RETURNS TABLE ("symbol" TEXT,
		"option_osi" TEXT,
		"days_to_expiration" INTEGER,
		"premium_option_price" NUMERIC,
		"intrinsic_value" NUMERIC,
		"extrinsic_value" NUMERIC,
		"strike_stock_price_difference" NUMERIC,
		"strike_stock_price_difference_ptc" NUMERIC)
        AS
        $$
             SELECT option_pricing_data.symbol,
    option_pricing_data.option_osi,
    option_pricing_data.days_to_expiration,
    round((option_pricing_data.premium_option_price)::numeric, 2) AS premium_option_price,
    round((option_pricing_data.intrinsic_value)::numeric, 2) AS intrinsic_value,
    round(((option_pricing_data.premium_option_price - option_pricing_data.intrinsic_value))::numeric, 2) AS extrinsic_value,
    option_pricing_data.strike_stock_price_difference,
    option_pricing_data.strike_stock_price_difference_ptc
   FROM ( SELECT a.symbol,
            a.option_osi,
                CASE
                    WHEN ((a.expiration_date - p_target_date) >= 0) THEN (a.expiration_date - p_target_date)
                    ELSE 0
                END AS days_to_expiration,
            round(((a.strike_price - c.close))::numeric, 2) AS strike_stock_price_difference,
            round(((((a.strike_price - c.close) / NULLIF(c.close, (0)::double precision)) * (100)::double precision))::numeric, 2) AS strike_stock_price_difference_ptc,
                CASE
                    WHEN (a.contract_type = 'call'::text) THEN GREATEST((c.close - a.strike_price), (0)::double precision)
                    WHEN (a.contract_type = 'put'::text) THEN GREATEST((a.strike_price - c.close), (0)::double precision)
                    ELSE NULL::double precision
                END AS intrinsic_value,
            a.day_close AS premium_option_price
           FROM ("getOptionDataMassiveHistory"(p_target_date) a
             LEFT JOIN "getStockPricesYahooHistory"(p_target_date) c ON ((a.symbol = c.symbol)))) option_pricing_data;
        $$
        LANGUAGE sql STABLE;
                