
        -- generated by HistorizationService
        CREATE OR REPLACE FUNCTION
            "getStockVolatilityHistory"(p_target_date date)
        RETURNS TABLE ("symbol" TEXT,
		"historical_volatility_30d" DOUBLE PRECISION)
        AS
        $$
             SELECT a.symbol,
    a.historical_volatility_30d
   FROM "getStockHistoricalVolatilityYahooHistory"(p_target_date) a;
        $$
        LANGUAGE sql STABLE;
                