
        -- generated by HistorizationService
        CREATE OR REPLACE FUNCTION
            "getTableLastUpdatedHistory"(p_target_date date)
        RETURNS TABLE ("table_name" TEXT,
		"last_updated" TIMESTAMP WITHOUT TIME ZONE)
        AS
        $$
             SELECT logs.table_name,
    max(logs."timestamp") AS last_updated
   FROM "DataChangeLogs" logs
  WHERE ((logs.operation_type = ANY (ARRAY['UPSERT'::text, 'UPDATE'::text, 'INSERT'::text])) AND (logs."timestamp" >= (p_target_date - '4 days'::interval)) AND (logs."timestamp" <= p_target_date))
  GROUP BY logs.table_name;
        $$
        LANGUAGE sql STABLE;
                