CREATE TABLE "FundamentalDataYahooProcessed" (
	symbol TEXT, 
	"EnterpriseValue" BIGINT, 
	"ForwardPE" FLOAT, 
	"TrailingEps" FLOAT, 
	"PriceToBook" FLOAT, 
	"TotalRevenue" BIGINT, 
	"EBITDA" BIGINT, 
	"FreeCashFlow" BIGINT, 
	"TotalDebt" BIGINT, 
	"NetIncome" TEXT, 
	"ROE" FLOAT, 
	"ROA" FLOAT, 
	"CurrentPrice" FLOAT, 
	"MarketCap" BIGINT, 
	"Volume" BIGINT, 
	"AverageVolume" BIGINT, 
	"Yahoo_DividendYield" FLOAT, 
	"DividendRate" FLOAT, 
	"TrailingAnnualDividendRate" FLOAT, 
	"PayoutRatio" FLOAT, 
	"ExDividendDate" TEXT, 
	"PE_Ratio_Calc" TEXT, 
	"PS_Ratio" FLOAT, 
	"DebtToMarketCap" FLOAT, 
	"EV_EBITDA_Approx" FLOAT
)