
    -- generated by HistorizationService
    CREATE VIEW
        "AnalystPriceTargetsHistoryTimeTravel" AS
    
            
        SELECT
            (current_setting('app.time_travel_date', true))::date AS date,
            master_data."symbol",
        coalesce(
                daily."analyst_mean_target",
                master_data."analyst_mean_target"
            ) as "analyst_mean_target"
        FROM
            "AnalystPriceTargetsMasterData" as master_data
            LEFT OUTER JOIN "AnalystPriceTargetsHistoryDaily" as daily
        ON daily.snapshot_date = (current_setting('app.time_travel_date', true))::date
        AND master_data."symbol" = daily."symbol"
        
        
    