
    -- generated by HistorizationService
    CREATE VIEW
        "AnalystPriceTargetsHistoryTimeTravel" AS
    
            
            SELECT
                daily.snapshot_date AS date,
                daily."symbol",
            daily."analyst_mean_target" as "analyst_mean_target"
            FROM
                "AnalystPriceTargetsHistoryDaily" as daily
               
            WHERE daily.snapshot_date = (current_setting('app.time_travel_date', true))::date
        
    