
    -- generated by HistorizationService
    CREATE VIEW
        "DividendDataYahooHistoryTimeTravel" AS
    
            
            SELECT
                daily.snapshot_date AS date,
                daily."symbol",
            daily."years_of_growth" as "years_of_growth",
			daily."classification" as "classification"
            FROM
                "DividendDataYahooHistoryDaily" as daily
               
            WHERE daily.snapshot_date = (current_setting('app.time_travel_date', true))::date
        
    