
    -- generated by HistorizationService
    CREATE VIEW
        "DividendDataYahooHistoryTimeTravel" AS
    
            
        SELECT
            (current_setting('app.time_travel_date', true))::date AS date,
            master_data."symbol",
        coalesce(
                daily."years_of_growth",
                master_data."years_of_growth"
            ) as "years_of_growth",
		coalesce(
                daily."classification",
                master_data."classification"
            ) as "classification"
        FROM
            "DividendDataYahooMasterData" as master_data
            LEFT OUTER JOIN "DividendDataYahooHistoryDaily" as daily
        ON daily.snapshot_date = (current_setting('app.time_travel_date', true))::date
        AND master_data."symbol" = daily."symbol"
        
            WHERE (current_setting('app.time_travel_date', true))::date BETWEEN master_data.from_date AND master_data.to_date
        
    