
    -- generated by HistorizationService
    CREATE VIEW
        "EarningDatesHistoryTimeTravel" AS
    
            
            SELECT
                daily.snapshot_date AS date,
                daily."symbol",
            daily."earnings_date" as "earnings_date"
            FROM
                "EarningDatesHistoryDaily" as daily
               
            WHERE daily.snapshot_date = (current_setting('app.time_travel_date', true))::date
        
    