
    -- generated by HistorizationService
    CREATE VIEW
        "EarningDatesHistoryTimeTravel" AS
    
            
        SELECT
            (current_setting('app.time_travel_date', true))::date AS date,
            master_data."symbol",
        coalesce(
                daily."earnings_date",
                master_data."earnings_date"
            ) as "earnings_date"
        FROM
            "EarningDatesMasterData" as master_data
            LEFT OUTER JOIN "EarningDatesHistoryDaily" as daily
        ON daily.snapshot_date = (current_setting('app.time_travel_date', true))::date
        AND master_data."symbol" = daily."symbol"
        
        
    