
    -- generated by HistorizationService
    CREATE VIEW
        "StockImpliedVolatilityMassiveHistoryTimeTravel" AS
    
            
            SELECT
                daily.snapshot_date AS date,
                daily."symbol",
            daily."iv" as "iv",
			daily."iv_low" as "iv_low",
			daily."iv_high" as "iv_high",
			daily."iv_rank" as "iv_rank",
			daily."iv_percentile" as "iv_percentile"
            FROM
                "StockImpliedVolatilityMassiveHistoryDaily" as daily
               
            WHERE daily.snapshot_date = (current_setting('app.time_travel_date', true))::date
        
    