
    -- generated by HistorizationService
    CREATE VIEW
        "StockPricesYahooHistoryTimeTravel" AS
    
            
            SELECT
                daily.snapshot_date AS date,
                daily."symbol",
            daily."open" as "open",
			daily."high" as "high",
			daily."low" as "low",
			daily."close" as "close",
			daily."volume" as "volume",
			daily."adjclose" as "adjclose",
			daily."dividends" as "dividends",
			daily."splits" as "splits"
            FROM
                "StockPricesYahooHistoryDaily" as daily
               
            WHERE daily.snapshot_date = (current_setting('app.time_travel_date', true))::date
        
    