
    -- generated by HistorizationService
    CREATE VIEW
        "StockHistoricalVolatilityYahooHistoryTimeTravel" AS
    
            
            SELECT
                daily.snapshot_date AS date,
                daily."symbol",
            daily."historical_volatility_30d" as "historical_volatility_30d"
            FROM
                "StockHistoricalVolatilityYahooHistoryDaily" as daily
               
            WHERE daily.snapshot_date = (current_setting('app.time_travel_date', true))::date
        
    