
    -- generated by HistorizationService
    CREATE VIEW
        "StockAssetProfilesYahooHistoryTimeTravel" AS
    
            
        SELECT
            dates.date,
            dates.year,
            dates.month,
            dates.isoyear,
            dates.week,
            master_data."symbol",
            master_data."name" as "name",
			master_data."industry" as "industry",
			master_data."sector" as "sector",
			master_data."country" as "country",
			master_data."long_business_summary" as "long_business_summary"
        FROM
            "DatesHistory" as dates
            INNER JOIN "StockAssetProfilesYahooMasterData" as master_data
            ON dates.date BETWEEN master_data.from_date AND master_data.to_date 
            
        
            WHERE dates.date = (current_setting('app.time_travel_date', true))::date 
        
    