
    -- generated by HistorizationService
    CREATE VIEW
        "StockHistoricalVolatilityYahooHistoryTimeTravel" AS
    
            
        SELECT
            (current_setting('app.time_travel_date', true))::date AS date,
            master_data."symbol",
        coalesce(
                daily."historical_volatility_30d",
                master_data."historical_volatility_30d"
            ) as "historical_volatility_30d"
        FROM
            "StockHistoricalVolatilityYahooMasterData" as master_data
            LEFT OUTER JOIN "StockHistoricalVolatilityYahooHistoryDaily" as daily
        ON daily.snapshot_date = (current_setting('app.time_travel_date', true))::date
        AND master_data."symbol" = daily."symbol"
        
            WHERE (current_setting('app.time_travel_date', true))::date BETWEEN master_data.from_date AND master_data.to_date
        
    