
    -- generated by HistorizationService
    CREATE VIEW
        "StockPricesYahooHistoryTimeTravel" AS
    
            
        SELECT
            (current_setting('app.time_travel_date', true))::date AS date,
            master_data."symbol",
        daily."open" as "open",
		daily."high" as "high",
		daily."low" as "low",
		daily."close" as "close",
		daily."volume" as "volume",
		daily."adjclose" as "adjclose",
		coalesce(
                daily."dividends",
                master_data."dividends"
            ) as "dividends",
		coalesce(
                daily."splits",
                master_data."splits"
            ) as "splits"
        FROM
            "StockPricesYahooMasterData" as master_data
            LEFT OUTER JOIN "StockPricesYahooHistoryDaily" as daily
        ON daily.snapshot_date = (current_setting('app.time_travel_date', true))::date
        AND master_data."symbol" = daily."symbol"
        
            WHERE (current_setting('app.time_travel_date', true))::date BETWEEN master_data.from_date AND master_data.to_date
        
    