
    -- generated by HistorizationService
    CREATE VIEW
        "StockAssetProfilesYahooHistoryTimeTravel" AS
    
            
        SELECT
            (current_setting('app.time_travel_date', true))::date AS date,
            master_data."symbol",
        coalesce(
                daily."name",
                master_data."name"
            ) as "name",
		coalesce(
                daily."industry",
                master_data."industry"
            ) as "industry",
		coalesce(
                daily."sector",
                master_data."sector"
            ) as "sector",
		coalesce(
                daily."country",
                master_data."country"
            ) as "country",
		coalesce(
                daily."long_business_summary",
                master_data."long_business_summary"
            ) as "long_business_summary"
        FROM
            "StockAssetProfilesYahooMasterData" as master_data
            LEFT OUTER JOIN "StockAssetProfilesYahooHistoryDaily" as daily
        ON daily.snapshot_date = (current_setting('app.time_travel_date', true))::date
        AND master_data."symbol" = daily."symbol"
        
        
    