
    -- generated by HistorizationService
    CREATE VIEW
        "TechnicalIndicatorsCalculatedHistoryTimeTravel" AS
    
        SELECT
            dates.date,
            dates.year,
            dates.month,
            dates.isoyear,
            dates.week,
            master_data."symbol",
        daily."EMA_5" as "EMA_5",
		daily."EMA_10" as "EMA_10",
		daily."EMA_20" as "EMA_20",
		daily."EMA_30" as "EMA_30",
		daily."EMA_50" as "EMA_50",
		daily."EMA_100" as "EMA_100",
		daily."EMA_200" as "EMA_200",
		daily."SMA_5" as "SMA_5",
		daily."SMA_10" as "SMA_10",
		daily."SMA_20" as "SMA_20",
		daily."SMA_30" as "SMA_30",
		daily."SMA_50" as "SMA_50",
		daily."SMA_100" as "SMA_100",
		daily."SMA_200" as "SMA_200",
		daily."MACD_12_26_9" as "MACD_12_26_9",
		daily."MACDh_12_26_9" as "MACDh_12_26_9",
		daily."MACDs_12_26_9" as "MACDs_12_26_9",
		daily."BBL_20_2.0_2.0" as "BBL_20_2.0_2.0",
		coalesce(
                daily."BBM_20_2.0_2.0",
                master_data."BBM_20_2.0_2.0"
            ) as "BBM_20_2.0_2.0",
		daily."BBU_20_2.0_2.0" as "BBU_20_2.0_2.0",
		daily."BBB_20_2.0_2.0" as "BBB_20_2.0_2.0",
		daily."BBP_20_2.0_2.0" as "BBP_20_2.0_2.0",
		daily."ATRr_14" as "ATRr_14",
		daily."ADX_10" as "ADX_10",
		daily."ADXR_10_2" as "ADXR_10_2",
		daily."DMP_10" as "DMP_10",
		daily."DMN_10" as "DMN_10",
		daily."STOCHk_14_3_1" as "STOCHk_14_3_1",
		daily."STOCHd_14_3_1" as "STOCHd_14_3_1",
		daily."STOCHh_14_3_1" as "STOCHh_14_3_1",
		daily."RSI_14" as "RSI_14",
		daily."RSL" as "RSL"
        FROM
            "DatesHistory" as dates
            INNER JOIN "TechnicalIndicatorsCalculatedMasterData" as master_data
            ON dates.date BETWEEN master_data.from_date AND master_data.to_date 
            LEFT OUTER JOIN "TechnicalIndicatorsCalculatedHistoryDaily" as daily
        ON dates.date = daily.snapshot_date
        AND master_data."symbol" = daily."symbol"
        
    