
    -- generated by HistorizationService
    CREATE OR REPLACE FUNCTION
        "getAnalystPriceTargetsHistory"(p_target_date date)
    RETURNS TABLE ("symbol" TEXT,
        "analyst_mean_target" DOUBLE PRECISION)
    AS $$
        SELECT 
        "symbol", 
        "analyst_mean_target" 
        FROM (
        SELECT
            daily.snapshot_date AS date,
            master_data.from_date AS from_date,
            master_data.to_date AS to_date,
            master_data."symbol",
        coalesce(
                daily."analyst_mean_target",
                master_data."analyst_mean_target"
            ) as "analyst_mean_target"
        FROM
            "AnalystPriceTargetsMasterData" as master_data
            LEFT OUTER JOIN "AnalystPriceTargetsHistoryDaily" as daily
        ON master_data."symbol" = daily."symbol"
        ) AS sub
        WHERE date = p_target_date
    $$ LANGUAGE SQL STABLE;
    