
    -- generated by HistorizationService
    CREATE OR REPLACE FUNCTION
        "getAnalystPriceTargetsHistory"(p_target_date date)
    RETURNS TABLE ("symbol" TEXT,
        "analyst_mean_target" DOUBLE PRECISION)
    AS $$
        SELECT 
        "symbol", 
        "analyst_mean_target" 
        FROM (
        SELECT
                daily.snapshot_date AS date,
                daily."symbol",
            daily."analyst_mean_target" as "analyst_mean_target"
            FROM
                "AnalystPriceTargetsHistoryDaily" as daily
        ) AS sub
        WHERE date = p_target_date
    $$ LANGUAGE SQL STABLE;
    