
    -- generated by HistorizationService
    CREATE OR REPLACE FUNCTION
        "getAnalystPriceTargetsHistory"(p_target_date date)
    RETURNS TABLE ("symbol" TEXT,
        "analyst_mean_target" DOUBLE PRECISION)
    AS $$
        SELECT 
        "symbol", 
        "analyst_mean_target" 
        FROM (
        SELECT
        dates.date,
        dates.year,
        dates.month,
        dates.isoyear,
        dates.week,
        master_data."symbol",
        coalesce(
                daily."analyst_mean_target",
                master_data."analyst_mean_target"
            ) as "analyst_mean_target"
    FROM
        "DatesHistory" as dates
        INNER JOIN "AnalystPriceTargetsMasterData" as master_data
        ON dates.date BETWEEN master_data.from_date AND master_data.to_date 
        LEFT JOIN "AnalystPriceTargetsHistoryDaily" as daily
        ON dates.date = daily.snapshot_date
        AND master_data."symbol" = daily."symbol"
        ) AS sub
        WHERE date = p_target_date
    $$ LANGUAGE SQL STABLE;
    