
    -- generated by HistorizationService
    CREATE OR REPLACE FUNCTION
        "getDividendDataYahooHistory"(p_target_date date)
    RETURNS TABLE ("symbol" TEXT,
        "years_of_growth" SMALLINT,
		"classification" TEXT)
    AS $$
        SELECT 
        "symbol", 
        "years_of_growth", "classification" 
        FROM (
        SELECT
                daily.snapshot_date AS date,
                daily."symbol",
            daily."years_of_growth" as "years_of_growth",
			daily."classification" as "classification"
            FROM
                "DividendDataYahooHistoryDaily" as daily
        ) AS sub
        WHERE date = p_target_date
    $$ LANGUAGE SQL STABLE;
    