
    -- generated by HistorizationService
    CREATE OR REPLACE FUNCTION
        "getDividendDataYahooHistory"(p_target_date date)
    RETURNS TABLE ("symbol" TEXT,
        "years_of_growth" SMALLINT,
		"classification" TEXT)
    AS $$
        SELECT 
        "symbol", 
        "years_of_growth", "classification" 
        FROM (
        SELECT
            daily.snapshot_date AS date,
            master_data.from_date AS from_date,
            master_data.to_date AS to_date,
            master_data."symbol",
        coalesce(
                daily."years_of_growth",
                master_data."years_of_growth"
            ) as "years_of_growth",
		coalesce(
                daily."classification",
                master_data."classification"
            ) as "classification"
        FROM
            "DividendDataYahooMasterData" as master_data
            LEFT OUTER JOIN "DividendDataYahooHistoryDaily" as daily
        ON master_data."symbol" = daily."symbol"
        ) AS sub
        WHERE date = p_target_date
    $$ LANGUAGE SQL STABLE;
    