
    -- generated by HistorizationService
    CREATE OR REPLACE FUNCTION
        "getEarningDatesHistory"(p_target_date date)
    RETURNS TABLE ("symbol" TEXT,
        "earnings_date" TEXT)
    AS $$
        SELECT 
        "symbol", 
        "earnings_date" 
        FROM (
        SELECT
                daily.snapshot_date AS date,
                daily."symbol",
            daily."earnings_date" as "earnings_date"
            FROM
                "EarningDatesHistoryDaily" as daily
        ) AS sub
        WHERE date = p_target_date
    $$ LANGUAGE SQL STABLE;
    