
    -- generated by HistorizationService
    CREATE OR REPLACE FUNCTION
        "getEarningDatesHistory"(p_target_date date)
    RETURNS TABLE ("symbol" TEXT,
        "earnings_date" TEXT)
    AS $$
        SELECT 
        "symbol", 
        "earnings_date" 
        FROM (
        SELECT
        dates.date,
        dates.year,
        dates.month,
        dates.isoyear,
        dates.week,
        master_data."symbol",
        coalesce(
                daily."earnings_date",
                master_data."earnings_date"
            ) as "earnings_date"
    FROM
        "DatesHistory" as dates
        INNER JOIN "EarningDatesMasterData" as master_data
        ON dates.date BETWEEN master_data.from_date AND master_data.to_date 
        LEFT JOIN "EarningDatesHistoryDaily" as daily
        ON dates.date = daily.snapshot_date
        AND master_data."symbol" = daily."symbol"
        ) AS sub
        WHERE date = p_target_date
    $$ LANGUAGE SQL STABLE;
    