
    -- generated by HistorizationService
    CREATE OR REPLACE FUNCTION
        "getEarningDatesHistory"(p_target_date date)
    RETURNS TABLE ("symbol" TEXT,
        "earnings_date" TEXT)
    AS $$
        SELECT 
        "symbol", 
        "earnings_date" 
        FROM (
        SELECT
            daily.snapshot_date AS date,
            master_data."symbol",
        coalesce(
                daily."earnings_date",
                master_data."earnings_date"
            ) as "earnings_date"
        FROM
            "EarningDatesMasterData" as master_data
            INNER JOIN "EarningDatesHistoryDaily" as daily
        ON master_data."symbol" = daily."symbol"
        ) AS sub
        WHERE date = p_target_date
    $$ LANGUAGE SQL STABLE;
    