
    -- generated by HistorizationService
    CREATE OR REPLACE FUNCTION
        "getOptionDataMassiveHistory"(p_target_date date)
    RETURNS TABLE ("option_osi" TEXT,
			"symbol" TEXT,
        "contract_type" TEXT,
		"expiration_date" DATE,
		"strike_price" DOUBLE PRECISION,
		"open_interest" BIGINT,
		"implied_volatility" DOUBLE PRECISION,
		"exercise_style" TEXT,
		"shares_per_contract" BIGINT,
		"greeks_delta" DOUBLE PRECISION,
		"greeks_gamma" DOUBLE PRECISION,
		"greeks_theta" DOUBLE PRECISION,
		"greeks_vega" DOUBLE PRECISION,
		"day_change" DOUBLE PRECISION,
		"day_change_percent" DOUBLE PRECISION,
		"day_close" DOUBLE PRECISION,
		"day_high" DOUBLE PRECISION,
		"day_low" DOUBLE PRECISION,
		"day_open" DOUBLE PRECISION,
		"day_previous_close" DOUBLE PRECISION,
		"day_volume" DOUBLE PRECISION,
		"day_vwap" DOUBLE PRECISION,
		"day_last_updated" TIMESTAMP WITHOUT TIME ZONE)
    AS $$
        SELECT 
        "option_osi", "symbol", 
        "contract_type", "expiration_date", "strike_price", "open_interest", "implied_volatility", "exercise_style", "shares_per_contract", "greeks_delta", "greeks_gamma", "greeks_theta", "greeks_vega", "day_change", "day_change_percent", "day_close", "day_high", "day_low", "day_open", "day_previous_close", "day_volume", "day_vwap", "day_last_updated" 
        FROM (
        SELECT
        dates.date,
        dates.year,
        dates.month,
        dates.isoyear,
        dates.week,
        master_data."option_osi",
		master_data."symbol",
        master_data."contract_type" as "contract_type",
		master_data."expiration_date" as "expiration_date",
		master_data."strike_price" as "strike_price",
		daily."open_interest" as "open_interest",
		daily."implied_volatility" as "implied_volatility",
		master_data."exercise_style" as "exercise_style",
		master_data."shares_per_contract" as "shares_per_contract",
		daily."greeks_delta" as "greeks_delta",
		daily."greeks_gamma" as "greeks_gamma",
		daily."greeks_theta" as "greeks_theta",
		daily."greeks_vega" as "greeks_vega",
		daily."day_change" as "day_change",
		daily."day_change_percent" as "day_change_percent",
		daily."day_close" as "day_close",
		daily."day_high" as "day_high",
		daily."day_low" as "day_low",
		daily."day_open" as "day_open",
		daily."day_previous_close" as "day_previous_close",
		daily."day_volume" as "day_volume",
		daily."day_vwap" as "day_vwap",
		daily."day_last_updated" as "day_last_updated"
    FROM
        "DatesHistory" as dates
        INNER JOIN "OptionDataMassiveMasterData" as master_data
        ON dates.date BETWEEN master_data.from_date AND master_data.to_date 
        LEFT JOIN "OptionDataMassiveHistoryDaily" as daily
        ON dates.date = daily.snapshot_date
        AND master_data."option_osi" = daily."option_osi" AND master_data."symbol" = daily."symbol"
        ) AS sub
        WHERE date = p_target_date
    $$ LANGUAGE SQL STABLE;
    