
    -- generated by HistorizationService
    CREATE OR REPLACE FUNCTION
        "getStockHistoricalVolatilityYahooHistory"(p_target_date date)
    RETURNS TABLE ("symbol" TEXT,
        "historical_volatility_30d" DOUBLE PRECISION)
    AS $$
        SELECT 
        "symbol", 
        "historical_volatility_30d" 
        FROM (
        SELECT
                daily.snapshot_date AS date,
                daily."symbol",
            daily."historical_volatility_30d" as "historical_volatility_30d"
            FROM
                "StockHistoricalVolatilityYahooHistoryDaily" as daily
        ) AS sub
        WHERE date = p_target_date
    $$ LANGUAGE SQL STABLE;
    