
    -- generated by HistorizationService
    CREATE OR REPLACE FUNCTION
        "getStockImpliedVolatilityMassiveHistory"(p_target_date date)
    RETURNS TABLE ("symbol" TEXT,
        "iv" DOUBLE PRECISION,
		"iv_low" DOUBLE PRECISION,
		"iv_high" DOUBLE PRECISION,
		"iv_rank" DOUBLE PRECISION,
		"iv_percentile" DOUBLE PRECISION)
    AS $$
        SELECT 
        "symbol", 
        "iv", "iv_low", "iv_high", "iv_rank", "iv_percentile" 
        FROM (
        SELECT
                daily.snapshot_date AS date,
                daily."symbol",
            daily."iv" as "iv",
			daily."iv_low" as "iv_low",
			daily."iv_high" as "iv_high",
			daily."iv_rank" as "iv_rank",
			daily."iv_percentile" as "iv_percentile"
            FROM
                "StockImpliedVolatilityMassiveHistoryDaily" as daily
        ) AS sub
        WHERE date = p_target_date
    $$ LANGUAGE SQL STABLE;
    