
    -- generated by HistorizationService
    CREATE OR REPLACE FUNCTION
        "getStockPricesYahooHistory"(p_target_date date)
    RETURNS TABLE ("symbol" TEXT,
        "open" DOUBLE PRECISION,
		"high" DOUBLE PRECISION,
		"low" DOUBLE PRECISION,
		"close" DOUBLE PRECISION,
		"volume" BIGINT,
		"adjclose" DOUBLE PRECISION,
		"dividends" DOUBLE PRECISION,
		"splits" DOUBLE PRECISION)
    AS $$
        SELECT 
        "symbol", 
        "open", "high", "low", "close", "volume", "adjclose", "dividends", "splits" 
        FROM (
        SELECT
                daily.snapshot_date AS date,
                daily."symbol",
            daily."open" as "open",
			daily."high" as "high",
			daily."low" as "low",
			daily."close" as "close",
			daily."volume" as "volume",
			daily."adjclose" as "adjclose",
			daily."dividends" as "dividends",
			daily."splits" as "splits"
            FROM
                "StockPricesYahooHistoryDaily" as daily
        ) AS sub
        WHERE date = p_target_date
    $$ LANGUAGE SQL STABLE;
    