
    -- generated by HistorizationService
    CREATE OR REPLACE FUNCTION
        "getStockImpliedVolatilityMassiveHistory"(p_target_date date)
    RETURNS TABLE ("symbol" TEXT,
        "iv" DOUBLE PRECISION,
		"iv_low" DOUBLE PRECISION,
		"iv_high" DOUBLE PRECISION,
		"iv_rank" DOUBLE PRECISION,
		"iv_percentile" DOUBLE PRECISION)
    AS $$
        SELECT 
        "symbol", 
        "iv", "iv_low", "iv_high", "iv_rank", "iv_percentile" 
        FROM (
        SELECT
        dates.date,
        dates.year,
        dates.month,
        dates.isoyear,
        dates.week,
        master_data."symbol",
        daily."iv" as "iv",
		daily."iv_low" as "iv_low",
		daily."iv_high" as "iv_high",
		daily."iv_rank" as "iv_rank",
		daily."iv_percentile" as "iv_percentile"
    FROM
        "DatesHistory" as dates
        INNER JOIN "StockImpliedVolatilityMassiveMasterData" as master_data
        ON dates.date BETWEEN master_data.from_date AND master_data.to_date 
        LEFT JOIN "StockImpliedVolatilityMassiveHistoryDaily" as daily
        ON dates.date = daily.snapshot_date
        AND master_data."symbol" = daily."symbol"
        ) AS sub
        WHERE date = p_target_date
    $$ LANGUAGE SQL STABLE;
    