
    -- generated by HistorizationService
    CREATE OR REPLACE FUNCTION
        "getStockPricesYahooHistory"(p_target_date date)
    RETURNS TABLE ("symbol" TEXT,
        "open" DOUBLE PRECISION,
		"high" DOUBLE PRECISION,
		"low" DOUBLE PRECISION,
		"close" DOUBLE PRECISION,
		"volume" BIGINT,
		"adjclose" DOUBLE PRECISION,
		"dividends" DOUBLE PRECISION,
		"splits" DOUBLE PRECISION)
    AS $$
        SELECT 
        "symbol", 
        "open", "high", "low", "close", "volume", "adjclose", "dividends", "splits" 
        FROM (
        SELECT
                daily.snapshot_date AS date,
                master_data."symbol",
            daily."open" as "open",
			daily."high" as "high",
			daily."low" as "low",
			daily."close" as "close",
			daily."volume" as "volume",
			daily."adjclose" as "adjclose",
			coalesce(
                daily."dividends",
                master_data."dividends"
            ) as "dividends",
			coalesce(
                daily."splits",
                master_data."splits"
            ) as "splits"
            FROM
                "StockPricesYahooHistoryDaily" as daily
                LEFT OUTER JOIN "StockPricesYahooMasterData" as master_data
                ON master_data."symbol" = daily."symbol"
        ) AS sub
        WHERE date = p_target_date
    $$ LANGUAGE SQL STABLE;
    