
    -- generated by HistorizationService
    CREATE OR REPLACE FUNCTION
        "getStockPricesYahooHistory"(p_target_date date)
    RETURNS TABLE ("symbol" TEXT,
        "open" DOUBLE PRECISION,
		"high" DOUBLE PRECISION,
		"low" DOUBLE PRECISION,
		"close" DOUBLE PRECISION,
		"volume" BIGINT,
		"adjclose" DOUBLE PRECISION,
		"dividends" DOUBLE PRECISION,
		"splits" DOUBLE PRECISION)
    AS $$
        SELECT 
        "symbol", 
        "open", "high", "low", "close", "volume", "adjclose", "dividends", "splits" 
        FROM (
        SELECT
        dates.date,
        dates.year,
        dates.month,
        dates.isoyear,
        dates.week,
        master_data."symbol",
        daily."open" as "open",
		daily."high" as "high",
		daily."low" as "low",
		daily."close" as "close",
		daily."volume" as "volume",
		daily."adjclose" as "adjclose",
		coalesce(
                daily."dividends",
                master_data."dividends"
            ) as "dividends",
		coalesce(
                daily."splits",
                master_data."splits"
            ) as "splits"
    FROM
        "DatesHistory" as dates
        INNER JOIN "StockPricesYahooMasterData" as master_data
        ON dates.date BETWEEN master_data.from_date AND master_data.to_date 
        LEFT JOIN "StockPricesYahooHistoryDaily" as daily
        ON dates.date = daily.snapshot_date
        AND master_data."symbol" = daily."symbol"
        ) AS sub
        WHERE date = p_target_date
    $$ LANGUAGE SQL STABLE;
    