
    -- generated by HistorizationService
    CREATE OR REPLACE FUNCTION
        "getStockHistoricalVolatilityYahooHistory"(p_target_date date)
    RETURNS TABLE ("symbol" TEXT,
        "historical_volatility_30d" DOUBLE PRECISION)
    AS $$
        SELECT 
        "symbol", 
        "historical_volatility_30d" 
        FROM (
        SELECT
            daily.snapshot_date AS date,
            master_data.from_date AS from_date,
            master_data.to_date AS to_date,
            master_data."symbol",
        coalesce(
                daily."historical_volatility_30d",
                master_data."historical_volatility_30d"
            ) as "historical_volatility_30d"
        FROM
            "StockHistoricalVolatilityYahooMasterData" as master_data
            LEFT OUTER JOIN "StockHistoricalVolatilityYahooHistoryDaily" as daily
        ON master_data."symbol" = daily."symbol"
        ) AS sub
        WHERE date = p_target_date
    $$ LANGUAGE SQL STABLE;
    