
    -- generated by HistorizationService
    CREATE OR REPLACE FUNCTION
        "getStockAssetProfilesYahooHistory"(p_target_date date)
    RETURNS TABLE ("symbol" TEXT,
        "name" TEXT,
		"industry" TEXT,
		"sector" TEXT,
		"country" TEXT,
		"long_business_summary" TEXT)
    AS $$
        SELECT 
        "symbol", 
        "name", "industry", "sector", "country", "long_business_summary" 
        FROM (
        SELECT
            daily.snapshot_date AS date,
            master_data."symbol",
        coalesce(
                daily."name",
                master_data."name"
            ) as "name",
		coalesce(
                daily."industry",
                master_data."industry"
            ) as "industry",
		coalesce(
                daily."sector",
                master_data."sector"
            ) as "sector",
		coalesce(
                daily."country",
                master_data."country"
            ) as "country",
		coalesce(
                daily."long_business_summary",
                master_data."long_business_summary"
            ) as "long_business_summary"
        FROM
            "StockAssetProfilesYahooMasterData" as master_data
            INNER JOIN "StockAssetProfilesYahooHistoryDaily" as daily
        ON master_data."symbol" = daily."symbol"
        ) AS sub
        WHERE date = p_target_date
    $$ LANGUAGE SQL STABLE;
    