
        -- generated by HistorizationService
        CREATE OR REPLACE VIEW
             "DividendDataHistoryTimeTravel" AS
         SELECT a.symbol,
    a.years_of_growth AS dividend_growth_years,
    a.classification AS dividend_classification,
    b.last_dividend,
    b.last_dividend_date,
    c.no_dividend_payouts_last_year
   FROM (("DividendDataYahooHistoryTimeTravel" a
     LEFT JOIN ( SELECT DISTINCT ON (sp.symbol) sp.symbol,
            sp.dividends AS last_dividend,
            sp.snapshot_date AS last_dividend_date
           FROM "StockPricesYahooHistoryDaily" sp
          WHERE ((sp.dividends > (0)::double precision) AND (sp.snapshot_date > (current_setting('app.time_travel_date', true)::date - '1 year'::interval)) AND (sp.snapshot_date <= current_setting('app.time_travel_date', true)::date))
          ORDER BY sp.symbol, sp.snapshot_date DESC) b ON ((a.symbol = b.symbol)))
     LEFT JOIN ( SELECT sp.symbol,
            count(*) AS no_dividend_payouts_last_year
           FROM "StockPricesYahooHistoryDaily" sp
          WHERE ((sp.dividends > (0)::double precision) AND (sp.snapshot_date > (current_setting('app.time_travel_date', true)::date - '1 year'::interval)) AND (sp.snapshot_date <= current_setting('app.time_travel_date', true)::date))
          GROUP BY sp.symbol) c ON ((a.symbol = c.symbol)));;
                