
        -- generated by HistorizationService
        CREATE OR REPLACE VIEW
             "OptionDataHistoryTimeTravel" AS
         SELECT a.option_osi,
    a.symbol,
    a.contract_type,
    a.expiration_date,
    a.strike_price,
    a.open_interest,
    a.implied_volatility,
    a.exercise_style,
    a.shares_per_contract,
    a.greeks_delta,
    a.greeks_gamma,
    a.greeks_theta,
    a.greeks_vega,
    a.day_change,
    a.day_change_percent,
    a.day_close,
    a.day_high,
    a.day_low,
    a.day_open,
    a.day_previous_close,
    a.day_volume,
    a.day_vwap,
    a.day_last_updated,
        CASE
            WHEN ((a.expiration_date - current_setting('app.time_travel_date', true)::date) >= 0) THEN (a.expiration_date - current_setting('app.time_travel_date', true)::date)
            ELSE 0
        END AS days_to_expiration,
    round((a.day_close)::numeric, 2) AS premium_option_price,
    ''::text AS last_updated_option_data
   FROM "OptionDataMassiveHistoryTimeTravel" a;;
                