
        -- generated by HistorizationService
        CREATE OR REPLACE VIEW
             "StockVolatilityHistoryTimeTravel" AS
         SELECT a.symbol,
    a.historical_volatility_30d
   FROM "StockHistoricalVolatilityYahooHistoryTimeTravel" a;;
                