
        -- generated by HistorizationService
        CREATE OR REPLACE VIEW
             "TableLastUpdatedHistoryTimeTravel" AS
         SELECT logs.table_name,
    max(logs."timestamp") AS last_updated
   FROM "DataChangeLogs" logs
  WHERE ((logs.operation_type = ANY (ARRAY['UPSERT'::text, 'UPDATE'::text, 'INSERT'::text])) AND (logs."timestamp" >= (current_setting('app.time_travel_date', true)::date - '4 days'::interval)) AND (logs."timestamp" <= current_setting('app.time_travel_date', true)::date))
  GROUP BY logs.table_name;;
                