"""
Executor — orchestrates pricing + slippage + commission + margin per action.

Multi-leg orders are atomic (Kap. 7.5): if any leg is unpriceable or would
violate margin, the whole order is rejected and logged.
"""

from __future__ import annotations

import logging
from datetime import date
from typing import Optional
from uuid import uuid4

from src.backtesting.data.snapshot import MarketSnapshot, Option
from src.backtesting.engine.actions import (
    Action, AdjustPosition, ClosePosition, ClosePartial,
    LegSpec, OpenPosition, SetStopLoss, SetTakeProfit, SetTrailingStop,
)
from src.backtesting.engine.portfolio import (
    OptionLeg, Portfolio, Position, StockLeg,
)
from src.backtesting.engine.stop_orders import (
    StopLossOrder, TakeProfitOrder, TrailingStopOrder,
)
from src.backtesting.execution.commission import (
    CommissionCalculator, CommissionConfig,
)
from src.backtesting.execution.margin import RegTMarginCalculator
from src.backtesting.execution.slippage import SlippageModel

logger = logging.getLogger(__name__)


class Executor:
    def __init__(self, run_config):
        self.slippage = SlippageModel(
            mode=run_config.slippage_mode,
            fixed_pct=run_config.slippage_fixed_pct,
            reject_illiquid=run_config.reject_illiquid,
        )
        commission_cfg = CommissionConfig(**(run_config.commission_config or {}))
        self.commission = CommissionCalculator(commission_cfg)
        self.margin = RegTMarginCalculator()

    # ── Dispatch ─────────────────────────────────────────────────────────

    def execute(
        self, action: Action, portfolio: Portfolio, snapshot: MarketSnapshot
    ) -> list[dict]:
        """Return a list of trade-log entries generated by this action."""
        if isinstance(action, OpenPosition):
            return self._execute_open(action, portfolio, snapshot)
        if isinstance(action, ClosePosition):
            return self._execute_close(action.position_id, portfolio, snapshot,
                                       fraction=1.0, reason=action.reason)
        if isinstance(action, ClosePartial):
            return self._execute_close(action.position_id, portfolio, snapshot,
                                       fraction=action.fraction, reason=action.reason)
        if isinstance(action, AdjustPosition):
            return self._execute_adjust(action, portfolio, snapshot)
        if isinstance(action, (SetStopLoss, SetTrailingStop, SetTakeProfit)):
            return self._execute_set_stop(action, portfolio)
        logger.warning("Unknown action: %s", type(action).__name__)
        return []

    # ── Open ─────────────────────────────────────────────────────────────

    def _execute_open(
        self, action: OpenPosition, portfolio: Portfolio, snapshot: MarketSnapshot
    ) -> list[dict]:
        resolved: list[tuple[LegSpec, Optional[Option], float]] = []
        for spec in action.legs:
            opt_or_none, price = self._resolve_leg(spec, snapshot)
            if price is None:
                logger.info("Order rejected: leg unpriceable (%s)", spec)
                return [{
                    "type": "reject", "reason": "unpriceable",
                    "symbol": spec.symbol,
                }]
            resolved.append((spec, opt_or_none, price))

        # Build tentative position to check margin
        position = Position(opened_at=snapshot.date, tags=dict(action.tags))
        cashflow = 0.0
        commissions = 0.0
        trade_logs: list[dict] = []

        for spec, opt, price in resolved:
            slip = self._slippage_pct_for(spec, opt)
            if slip is None:
                logger.info("Order rejected: illiquid leg %s", spec.symbol)
                return [{
                    "type": "reject", "reason": "illiquid",
                    "symbol": spec.symbol,
                }]
            fill = price * (1 + slip * _sign_for_buy(spec.quantity))

            if spec.kind == "stock":
                leg = StockLeg(
                    symbol=spec.symbol,
                    quantity=spec.quantity,
                    entry_price=fill,
                    current_price=fill,
                )
                position.legs.append(leg)
                cashflow -= fill * spec.quantity
                commissions += self.commission.stock_commission(spec.quantity, fill)
                trade_logs.append({
                    "type": "open_stock", "date": snapshot.date,
                    "symbol": spec.symbol, "quantity": spec.quantity,
                    "price": fill, "slippage_pct": slip,
                })
            else:
                assert opt is not None
                leg = OptionLeg(
                    symbol=spec.symbol,
                    option_osi=opt.option_osi,
                    contract_type=opt.contract_type,
                    strike=opt.strike,
                    expiration_date=opt.expiration_date,
                    quantity=spec.quantity,
                    entry_premium=fill,
                    current_premium=fill,
                    shares_per_contract=opt.shares_per_contract,
                    days_to_expiration=opt.days_to_expiration,
                    delta=opt.delta, gamma=opt.gamma,
                    theta=opt.theta, vega=opt.vega,
                    implied_volatility=opt.implied_volatility,
                )
                position.legs.append(leg)
                # short options: +premium; long options: -premium
                cashflow += -fill * spec.quantity * opt.shares_per_contract
                commissions += self.commission.option_commission(spec.quantity)
                trade_logs.append({
                    "type": "open_option", "date": snapshot.date,
                    "symbol": spec.symbol, "option_osi": opt.option_osi,
                    "quantity": spec.quantity, "premium": fill,
                    "slippage_pct": slip,
                })

        # Margin check
        underlying_prices = {
            l.symbol: (snapshot.get_stock(l.symbol).live_stock_price
                       if snapshot.get_stock(l.symbol) else 0.0)
            for l in position.legs
        }
        margin_required = self.margin.position_margin(position, underlying_prices)
        if margin_required > portfolio.buying_power + cashflow:
            logger.info("Order rejected: insufficient margin (%.2f needed, %.2f free)",
                        margin_required, portfolio.buying_power + cashflow)
            return [{
                "type": "reject", "reason": "margin",
                "margin_required": margin_required,
            }]

        # Apply stops declared alongside the open action
        if action.stop_loss is not None:
            position.stop_orders.append(StopLossOrder(level=action.stop_loss))
        if action.trailing_stop_pct is not None:
            position.stop_orders.append(TrailingStopOrder(trail_pct=action.trailing_stop_pct))
        if action.take_profit is not None:
            position.stop_orders.append(TakeProfitOrder(level=action.take_profit))

        # Commit to portfolio
        position.entry_cashflow = cashflow - commissions
        portfolio.cash += cashflow - commissions
        portfolio.margin_used += margin_required
        portfolio.positions.append(position)

        for entry in trade_logs:
            entry["position_id"] = str(position.id)
            entry["commission"] = commissions / max(len(trade_logs), 1)
            entry["reason"] = action.reason
        return trade_logs

    # ── Close (full or partial) ──────────────────────────────────────────

    def _execute_close(
        self,
        position_id,
        portfolio: Portfolio,
        snapshot: MarketSnapshot,
        fraction: float,
        reason: str,
    ) -> list[dict]:
        position = portfolio.get_position(position_id)
        if position is None:
            return []
        fraction = max(0.0, min(1.0, fraction))
        cashflow = 0.0
        commissions = 0.0
        entries: list[dict] = []

        for leg in list(position.legs):
            trade_qty = -int(leg.quantity * fraction)
            if trade_qty == 0:
                continue

            if isinstance(leg, StockLeg):
                price = leg.current_price
                slip = self.slippage.stock_slippage_pct()
                fill = price * (1 + slip * _sign_for_buy(trade_qty))
                leg_cashflow = -fill * trade_qty
                cashflow += leg_cashflow
                comm = self.commission.stock_commission(abs(trade_qty), fill)
                commissions += comm
                leg.quantity += trade_qty
                entries.append({
                    "type": "close_stock", "date": snapshot.date,
                    "symbol": leg.symbol, "quantity": trade_qty,
                    "price": fill, "reason": reason, "slippage_pct": slip,
                })
            else:  # OptionLeg
                price = leg.current_premium
                # Use today's actual open_interest from the snapshot so a
                # liquid option gets liquid-tier slippage on close, not the
                # OI=0 illiquid tier.
                oi = self._leg_open_interest(leg, snapshot)
                slip = self.slippage.option_slippage_pct(open_interest=oi) or 0.01
                fill = price * (1 + slip * _sign_for_buy(trade_qty))
                leg_cashflow = -fill * trade_qty * leg.shares_per_contract
                cashflow += leg_cashflow
                comm = self.commission.option_commission(abs(trade_qty))
                commissions += comm
                leg.quantity += trade_qty
                entries.append({
                    "type": "close_option", "date": snapshot.date,
                    "symbol": leg.symbol, "option_osi": leg.option_osi,
                    "quantity": trade_qty, "premium": fill,
                    "reason": reason, "slippage_pct": slip,
                })

        # Remove zeroed legs
        position.legs = [l for l in position.legs if l.quantity != 0]

        portfolio.cash += cashflow - commissions
        if not position.legs or fraction >= 1.0:
            underlying_prices = {}
            portfolio.margin_used = max(
                0.0,
                portfolio.margin_used - self.margin.position_margin(
                    position, underlying_prices
                ),
            )
            position.realized_pnl = position.entry_cashflow + cashflow - commissions
            position.closed_at = snapshot.date
            position.tags.setdefault("close_reason", reason)
            portfolio._move_to_closed(position)

        for entry in entries:
            entry["position_id"] = str(position_id)
            entry["commission"] = commissions / max(len(entries), 1)
        return entries

    # ── Adjust (roll / hedge) ────────────────────────────────────────────

    def _execute_adjust(
        self, action: AdjustPosition, portfolio: Portfolio, snapshot: MarketSnapshot
    ) -> list[dict]:
        position = portfolio.get_position(action.position_id)
        if position is None:
            return []

        entries: list[dict] = []
        # 1) close specified legs at market
        legs_to_close = [l for l in position.legs if l.id in action.close_leg_ids]
        for leg in legs_to_close:
            trade_qty = -leg.quantity
            if isinstance(leg, StockLeg):
                price = leg.current_price
                slip = self.slippage.stock_slippage_pct()
                fill = price * (1 + slip * _sign_for_buy(trade_qty))
                leg_cashflow = -fill * trade_qty
                comm = self.commission.stock_commission(abs(trade_qty), fill)
                portfolio.cash += leg_cashflow - comm
                entries.append({
                    "type": "close_stock", "date": snapshot.date,
                    "symbol": leg.symbol, "quantity": trade_qty,
                    "price": fill, "reason": action.reason,
                    "position_id": str(position.id), "commission": comm,
                })
                position.legs.remove(leg)
            else:  # OptionLeg
                price = leg.current_premium
                # Same fix as _execute_close: use today's real OI from the
                # snapshot rather than defaulting to 0 (illiquid tier).
                oi = self._leg_open_interest(leg, snapshot)
                slip = self.slippage.option_slippage_pct(open_interest=oi) or 0.01
                fill = price * (1 + slip * _sign_for_buy(trade_qty))
                leg_cashflow = -fill * trade_qty * leg.shares_per_contract
                comm = self.commission.option_commission(abs(trade_qty))
                portfolio.cash += leg_cashflow - comm
                entries.append({
                    "type": "close_option", "date": snapshot.date,
                    "symbol": leg.symbol, "option_osi": leg.option_osi,
                    "quantity": trade_qty, "premium": fill,
                    "reason": action.reason,
                    "position_id": str(position.id), "commission": comm,
                })
                position.legs.remove(leg)

        # 2) open new legs on the same position
        for spec in action.open_legs:
            opt, price = self._resolve_leg(spec, snapshot)
            if price is None:
                logger.info("Roll rejected: new leg unpriceable (%s)", spec)
                continue
            slip = self._slippage_pct_for(spec, opt)
            if slip is None:
                logger.info("Roll rejected: new leg illiquid (%s)", spec.symbol)
                continue
            fill = price * (1 + slip * _sign_for_buy(spec.quantity))
            if spec.kind == "stock":
                leg = StockLeg(
                    symbol=spec.symbol, quantity=spec.quantity,
                    entry_price=fill, current_price=fill,
                )
                position.legs.append(leg)
                portfolio.cash -= fill * spec.quantity
                comm = self.commission.stock_commission(spec.quantity, fill)
                portfolio.cash -= comm
                entries.append({
                    "type": "open_stock", "date": snapshot.date,
                    "symbol": spec.symbol, "quantity": spec.quantity,
                    "price": fill, "reason": action.reason,
                    "position_id": str(position.id), "commission": comm,
                })
            else:
                assert opt is not None
                leg = OptionLeg(
                    symbol=spec.symbol,
                    option_osi=opt.option_osi,
                    contract_type=opt.contract_type,
                    strike=opt.strike,
                    expiration_date=opt.expiration_date,
                    quantity=spec.quantity,
                    entry_premium=fill, current_premium=fill,
                    shares_per_contract=opt.shares_per_contract,
                    days_to_expiration=opt.days_to_expiration,
                    delta=opt.delta, gamma=opt.gamma,
                    theta=opt.theta, vega=opt.vega,
                    implied_volatility=opt.implied_volatility,
                )
                position.legs.append(leg)
                portfolio.cash += -fill * spec.quantity * opt.shares_per_contract
                comm = self.commission.option_commission(spec.quantity)
                portfolio.cash -= comm
                entries.append({
                    "type": "open_option", "date": snapshot.date,
                    "symbol": spec.symbol, "option_osi": opt.option_osi,
                    "quantity": spec.quantity, "premium": fill,
                    "reason": action.reason,
                    "position_id": str(position.id), "commission": comm,
                })
        position.tags["roll_count"] = str(position.roll_count + 1)
        return entries

    # ── Stops ────────────────────────────────────────────────────────────

    def _execute_set_stop(self, action, portfolio: Portfolio) -> list[dict]:
        position = portfolio.get_position(action.position_id)
        if position is None:
            return []
        if isinstance(action, SetStopLoss):
            position.stop_orders.append(StopLossOrder(level=action.level))
        elif isinstance(action, SetTrailingStop):
            position.stop_orders.append(TrailingStopOrder(trail_pct=action.trail_pct))
        elif isinstance(action, SetTakeProfit):
            position.stop_orders.append(TakeProfitOrder(level=action.level))
        return []

    # ── Helpers ──────────────────────────────────────────────────────────

    def _resolve_leg(
        self, spec: LegSpec, snapshot: MarketSnapshot
    ) -> tuple[Optional[Option], Optional[float]]:
        """Return (option-or-None, price) for a leg. price=None means reject."""
        if spec.kind == "stock":
            stock = snapshot.get_stock(spec.symbol)
            if stock is None:
                return None, None
            return None, stock.live_stock_price

        # option leg
        chain = snapshot.get_chain(spec.symbol)
        if chain is None:
            return None, None
        if spec.option_osi:
            for opt in chain.all():
                if opt.option_osi == spec.option_osi:
                    return opt, opt.day_close
            return None, None
        # descriptive resolution
        assert spec.contract_type is not None
        opt = chain.find(
            contract_type=spec.contract_type,
            delta_target=spec.delta_target,
            dte_range=spec.dte_range,
            strike_target=spec.strike_target,
            min_open_interest=100 if not self.slippage.reject_illiquid else 100,
        )
        if opt is None:
            return None, None
        return opt, opt.day_close

    def _slippage_pct_for(self, spec: LegSpec, opt: Optional[Option]) -> Optional[float]:
        if spec.kind == "stock":
            return self.slippage.stock_slippage_pct()
        oi = opt.open_interest if opt else 0
        return self.slippage.option_slippage_pct(open_interest=oi)

    def _leg_open_interest(
        self, leg: "OptionLeg", snapshot: MarketSnapshot
    ) -> int:
        """Look up today's open_interest for an option leg from the snapshot.

        Returns 0 if the contract can't be found (e.g. on/after expiry or
        after a delisting). Used to compute realistic close/adjust slippage —
        without this the executor would treat every close as an OI=0 order
        and pay the 3% illiquid-tier slippage regardless of actual liquidity.
        """
        chain = snapshot.get_chain(leg.symbol)
        if chain is None:
            return 0
        for opt in chain.all():
            if opt.option_osi == leg.option_osi:
                return int(opt.open_interest or 0)
        return 0


def _sign_for_buy(quantity: int) -> int:
    """Slippage direction: buying (+qty) pays more, selling (-qty) receives less."""
    return 1 if quantity > 0 else -1
