# exchange must match the trading view ones.
# yahoo uses different exchange names which must be mapped first



SYMBOLS_EXCHANGE = {
    'A': 'NYQ',
    'AAPL': 'NMS',
    'AAT': 'NYQ',
    'ABBV': 'NYQ',
    'ABM': 'NYQ',
    'ABR': 'NYQ',
    'ABT': 'NYQ',
    'ACN': 'NYQ',
    'ACNB': 'NCM',
    'ADC': 'NYQ',
    'ADI': 'NMS',
    'ADM': 'NYQ',
    'ADP': 'NMS',
    'AEE': 'NYQ',
    'AEP': 'NMS',
    'AES': 'NYQ',
    'AFG': 'NYQ',
    'AFL': 'NYQ',
    'AGCO': 'NYQ',
    'AGM': 'NYQ', 'AGO': 'NYQ', 'AIN': 'NYQ', 'AIT': 'NYQ', 'AIZ': 'NYQ',
    'AJG': 'NYQ', 'AL': 'NYQ', 'ALB': 'NYQ', 'ALE': 'NYQ', 'ALEX': 'NYQ', 'ALG': 'NYQ', 'ALL': 'NYQ', 'ALLE': 'NYQ',
    'ALRS': 'NCM', 'ALSN': 'NYQ', 'ALV': 'NYQ', 'AMAT': 'NMS', 'AMCR': 'NYQ', 'AMD': 'NMS', 'AME': 'NYQ', 'AMGN': 'NMS',
    'AMH': 'NYQ', 'AMKR': 'NMS', 'AMP': 'NYQ', 'AMSF': 'NMS', 'AMT': 'NYQ', 'AMZN': 'NMS', 'ANDE': 'NMS', 'AON': 'NYQ',
    'AOS': 'NYQ', 'APD': 'NYQ', 'APH': 'NYQ', 'APOG': 'NMS', 'ARE': 'NYQ', 'ARES': 'NYQ', 'AROW': 'NMS', 'ASB': 'NYQ',
    'ASH': 'NYQ', 'ATO': 'NYQ', 'ATR': 'NYQ', 'AUB': 'NYQ', 'AVA': 'NYQ', 'AVGO': 'NMS', 'AVNT': 'NYQ', 'AVT': 'NMS',
    'AVY': 'NYQ', 'AWI': 'NYQ', 'AWK': 'NYQ', 'AWR': 'NYQ', 'BA': 'NYQ', 'BABA': 'NYQ', 'BAC': 'NYQ', 'BAH': 'NYQ',
    'BANF': 'NMS', 'BBY': 'NYQ', 'BC': 'NYQ', 'BCC': 'NYQ', 'BCO': 'NYQ', 'BCPC': 'NMS', 'BCS': 'NYQ', 'BDX': 'NYQ',
    'BEN': 'NYQ', 'BF.A': None, 'BF.B': 'YHD', 'BFC': 'NCM', 'BFST': 'NMS', 'BHB': 'ASE', 'BIDU': 'NMS', 'BIP': 'NYQ',
    'BK': 'NYQ', 'BKH': 'NYQ', 'BKU': 'NYQ', 'BMI': 'NYQ', 'BMY': 'NYQ', 'BOKF': 'NMS', 'BOTJ': 'NCM', 'BR': 'NYQ',
    'BRC': 'NYQ', 'BRO': 'NYQ', 'BRX': 'NYQ', 'BSET': 'NMS', 'BSVN': 'NMS', 'BWXT': 'NYQ', 'BXS': None, 'C': 'NYQ',
    'CABO': 'NYQ', 'CAG': 'NYQ', 'CAH': 'NYQ', 'CARR': 'NYQ', 'CASS': 'NMS', 'CASY': 'NMS', 'CAT': 'NYQ', 'CB': 'NYQ',
    'CBAN': 'NYQ', 'CBOE': 'BTS', 'CBSH': 'NMS', 'CBT': 'NYQ', 'CBU': 'NYQ', 'CCBG': 'NMS', 'CCOI': 'NMS', 'CDW': 'NMS',
    'CFBK': 'NCM', 'CFFI': 'NMS', 'CFR': 'NYQ', 'CGNX': 'NMS', 'CHCO': 'NMS', 'CHCT': 'NYQ', 'CHD': 'NYQ',
    'CHDN': 'NMS', 'CHE': 'NYQ', 'CHRW': 'NMS', 'CI': 'NYQ', 'CINF': 'NMS', 'CIVB': 'NCM', 'CL': 'NYQ', 'CLX': 'NYQ',
    'CMC': 'NYQ', 'CMCSA': 'NMS', 'CMI': 'NYQ', 'CMS': 'NYQ', 'CNA': 'NYQ', 'CNI': 'NYQ', 'CNO': 'NYQ', 'CNOB': 'NMS',
    'CNQ': 'NYQ', 'CNS': 'NYQ', 'COF': 'NYQ', 'COFS': 'NCM', 'COP': 'NYQ', 'COR': 'NYQ', 'COST': 'NMS', 'CPK': 'NYQ',
    'CPT': 'NYQ', 'CQP': 'NYQ', 'CRAI': 'NMS', 'CRM': 'NYQ', 'CRWD': 'NMS', 'CSCO': 'NMS', 'CSGS': 'NMS', 'CSL': 'NYQ',
    'CSR': 'NYQ', 'CSWC': 'NMS', 'CSWI': 'NMS', 'CSX': 'NMS', 'CTAS': 'NMS', 'CTBI': 'NMS', 'CTRA': 'NYQ',
    'CTRE': 'NYQ', 'CTSH': 'NMS', 'CTVA': 'NYQ', 'CUBE': 'NYQ', 'CVX': 'NYQ', 'CW': 'NYQ', 'CWEN': 'NYQ', 'CWT': 'NYQ',
    'CZWI': 'NGM', 'DCI': 'NYQ', 'DDS': 'NYQ', 'DE': 'NYQ', 'DFS': 'NYQ', 'DG': 'NYQ', 'DGX': 'NYQ', 'DHI': 'NYQ',
    'DHR': 'NYQ', 'DIA': 'PCX', 'DIS': 'NYQ', 'DKL': 'NYQ', 'DKS': 'NYQ', 'DLB': 'NYQ', 'DOV': 'NYQ', 'DPZ': 'NMS',
    'DRI': 'NYQ', 'DUK': 'NYQ', 'DVN': 'NYQ', 'EBAY': 'NMS', 'EBMT': 'NGM', 'EBTC': 'NMS', 'ECL': 'NYQ', 'ED': 'NYQ',
    'EEM': 'PCX', 'EFSC': 'NMS', 'EGP': 'NYQ', 'EIX': 'NYQ', 'ELS': 'NYQ', 'ELV': 'NYQ', 'EME': 'NYQ', 'EMN': 'NYQ',
    'EMR': 'NYQ', 'ENB': 'NYQ', 'ENSG': 'NMS', 'EOG': 'NYQ', 'EPD': 'NYQ', 'EPRT': 'NYQ', 'EQH': 'NYQ', 'EQIX': 'NMS',
    'EQR': 'NYQ', 'ERIC': 'NMS', 'ERIE': 'NMS', 'ES': 'NYQ', 'ESNT': 'NYQ', 'ESS': 'NYQ', 'ETD': 'NYQ', 'ETN': 'NYQ',
    'ETR': 'NYQ', 'EVR': 'NYQ', 'EVRG': 'NMS', 'EWBC': 'NMS', 'EXPD': 'NYQ', 'EXPO': 'NMS', 'FAF': 'NYQ', 'FANG': 'NMS',
    'FAST': 'NMS', 'FBIZ': 'NMS', 'FBK': 'NYQ', 'FBMS': 'NYQ', 'FBP': 'NYQ', 'FCBC': 'NMS', 'FCF': 'NYQ', 'FCPT': 'NYQ',
    'FDBC': 'NGM', 'FDP': 'NYQ', 'FDS': 'NYQ', 'FDX': 'NYQ', 'FELE': 'NMS', 'FFIN': 'NMS', 'FISI': 'NMS', 'FITB': 'NMS',
    'FIX': 'NYQ', 'FLNG': 'NYQ', 'FLO': 'NYQ', 'FMAO': 'NCM', 'FMBH': 'NGM', 'FNF': 'NYQ', 'FNLC': 'NMS', 'FNV': 'NYQ',
    'FOX': 'NMS', 'FOXA': 'NMS', 'FR': 'NYQ', 'FRME': 'NMS', 'FRT': 'NYQ', 'FSBW': 'NCM', 'FSFG': 'NCM', 'FSV': 'NMS',
    'FUL': 'NYQ', 'FULT': 'NMS', 'FUNC': 'NMS', 'FXNC': 'NCM', 'G': 'NYQ', 'GABC': 'NMS', 'GATX': 'NYQ', 'GCBC': 'NCM',
    'GD': 'NYQ', 'GE': 'NYQ', 'GEF': 'NYQ', 'GEF.B': 'YHD', 'GFF': 'NYQ', 'GGG': 'NYQ', 'GHC': 'NYQ', 'GIC': 'NYQ',
    'GIL': 'NYQ', 'GILD': 'NMS', 'GIS': 'NYQ', 'GL': 'NYQ', 'GLD': 'PCX', 'GLPI': 'NMS', 'GM': 'NYQ', 'GNTY': 'NYQ',
    'GOLF': 'NYQ', 'GOOG': 'NMS', 'GPC': 'NYQ', 'GPI': 'NYQ', 'GPRK': 'NYQ', 'GRC': 'NYQ', 'GRMN': 'NYQ', 'GS': 'NYQ',
    'GTY': 'NYQ', 'GWRS': 'NGM', 'GWW': 'NYQ', 'HBB': 'NYQ', 'HBCP': 'NMS', 'HCA': 'NYQ', 'HD': 'NYQ', 'HEI': 'NYQ',
    'HESM': 'NYQ', 'HFBL': 'NCM', 'HFWA': 'NMS', 'HI': 'NYQ', 'HIG': 'NYQ', 'HII': 'NYQ', 'HLI': 'NYQ', 'HLNE': 'NMS',
    'HMN': 'NYQ', 'HNI': 'NYQ', 'HOFT': 'NMS', 'HOG': 'NYQ', 'HOMB': 'NYQ', 'HON': 'NMS', 'HPQ': 'NYQ', 'HRB': 'NYQ',
    'HRL': 'NYQ', 'HSBC': 'NYQ', 'HSY': 'NYQ', 'HTB': 'NYQ', 'HTGC': 'NYQ', 'HTH': 'NYQ', 'HUBB': 'NYQ', 'HUM': 'NYQ',
    'HVT': 'NYQ', 'HWBK': 'NMS', 'HWKN': 'NMS', 'HWM': 'NYQ', 'HY': 'NYQ', 'IBCP': 'NMS', 'IBM': 'NYQ', 'IBOC': 'NMS',
    'IBP': 'NYQ', 'ICE': 'NYQ', 'IDA': 'NYQ', 'IEX': 'NYQ', 'IIPR': 'NYQ', 'IMO': 'ASE', 'INDB': 'NMS', 'INFY': 'NYQ',
    'INGR': 'NYQ', 'INTU': 'NMS', 'INVH': 'NYQ', 'IOSP': 'NMS', 'IPAR': 'NMS', 'IPG': 'NYQ', 'ISTR': 'NGM',
    'ITT': 'NYQ', 'ITW': 'NYQ', 'IWM': 'PCX', 'J': 'NYQ', 'JBHT': 'NMS', 'JBSS': 'NMS', 'JJSF': 'NMS', 'JKHY': 'NMS',
    'JNJ': 'NYQ', 'JOE': 'NYQ', 'JOUT': 'NMS', 'JPM': 'NYQ', 'KAI': 'NYQ', 'KBR': 'NYQ', 'KDP': 'NMS', 'KFRC': 'NYQ',
    'KFY': 'NYQ', 'KIM': 'NYQ', 'KKR': 'NYQ', 'KLAC': 'NMS', 'KLIC': 'NMS', 'KMB': 'NYQ', 'KMI': 'NYQ', 'KNSL': 'NYQ',
    'KNX': 'NYQ', 'KO': 'NYQ', 'KOF': 'NYQ', 'KR': 'NYQ', 'KRG': 'NYQ', 'KTB': 'NYQ', 'KWR': 'NYQ', 'LAD': 'NYQ',
    'LAMR': 'NMS', 'LANC': 'NMS', 'LAND': 'NGM', 'LARK': 'NGM', 'LCII': 'NYQ', 'LCNB': 'NCM', 'LDOS': 'NYQ',
    'LECO': 'NMS', 'LEVI': 'NYQ', 'LFUS': 'NMS', 'LHX': 'NYQ', 'LII': 'NYQ', 'LIN': 'NMS', 'LKFN': 'NMS', 'LLY': 'NYQ',
    'LMAT': 'NGM', 'LMT': 'NYQ', 'LNN': 'NYQ', 'LNT': 'NMS', 'LOGI': 'NMS', 'LOW': 'NYQ', 'LPX': 'NYQ', 'LRCX': 'NMS',
    'LSTR': 'NMS', 'LW': 'NYQ', 'LXP': 'NYQ', 'LYB': 'NYQ', 'LZB': 'NYQ', 'MA': 'NYQ', 'MAA': 'NYQ', 'MAIN': 'NYQ',
    'MAN': 'NYQ', 'MAS': 'NYQ', 'MATW': 'NMS', 'MATX': 'NYQ', 'MBIN': 'NCM', 'MBWM': 'NMS', 'MCBS': 'NMS', 'MCD': 'NYQ',
    'MCHP': 'NMS', 'MCK': 'NYQ', 'MCO': 'NYQ', 'MDLZ': 'NMS', 'MDT': 'NYQ', 'MET': 'NYQ', 'META': 'NMS', 'MFC': 'NYQ',
    'MGA': 'NYQ', 'MGEE': 'NMS', 'MGRC': 'NMS', 'MKC': 'NYQ', 'MKTX': 'NMS', 'MLI': 'NYQ', 'MLM': 'NYQ', 'MMC': 'NYQ',
    'MMM': 'NYQ', 'MO': 'NYQ', 'MOG.A': None, 'MORN': 'NMS', 'MOS': 'NYQ', 'MPLX': 'NYQ', 'MPWR': 'NMS', 'MRK': 'NYQ',
    'MRVL': 'NMS', 'MS': 'NYQ', 'MSA': 'NYQ', 'MSBI': 'NMS', 'MSCI': 'NYQ', 'MSEX': 'NMS', 'MSFT': 'NMS', 'MSI': 'NYQ',
    'MTB': 'NYQ', 'MTG': 'NYQ', 'MTRN': 'NYQ', 'MU': 'NMS', 'MUSA': 'NYQ', 'MWA': 'NYQ', 'NBHC': 'NYQ', 'NBTB': 'NMS',
    'NC': 'NYQ', 'NDAQ': 'NMS', 'NDSN': 'NMS', 'NEE': 'NYQ', 'NEU': 'NYQ', 'NFG': 'NYQ', 'NFLX': 'NMS', 'NHC': 'ASE',
    'NI': 'NYQ', 'NJR': 'NYQ', 'NKE': 'NYQ', 'NNI': 'NYQ', 'NNN': 'NYQ', 'NOC': 'NYQ', 'NPO': 'NYQ', 'NRG': 'NYQ',
    'NRIM': 'NMS', 'NSA': 'NYQ', 'NSP': 'NYQ', 'NTR': 'NYQ', 'NUE': 'NYQ', 'NVDA': 'NMS', 'NVS': 'NYQ', 'NWE': 'NMS',
    'NWFL': 'NGM', 'NWN': 'NYQ', 'NXPI': 'NMS', 'NXRT': 'NYQ', 'NXST': 'NMS', 'NYT': 'NYQ', 'O': 'NYQ', 'OC': 'NYQ',
    'ODC': 'NYQ', 'ODFL': 'NMS', 'OFG': 'NYQ', 'OFLX': 'NGM', 'OGE': 'NYQ', 'OGS': 'NYQ', 'OLED': 'NMS', 'OMF': 'NYQ',
    'ORCL': 'NYQ', 'ORI': 'NYQ', 'ORRF': 'NCM', 'OSK': 'NYQ', 'OTEX': 'NMS', 'OTIS': 'NYQ', 'OTTR': 'NMS',
    'OVLY': 'NCM', 'OVV': 'NYQ', 'OXM': 'NYQ', 'OZK': 'NMS', 'PAG': 'NYQ', 'PATK': 'NMS', 'PAYX': 'NMS', 'PB': 'NYQ',
    'PBHC': 'NCM', 'PCB': 'NMS', 'PEBK': 'NGM', 'PEBO': 'NMS', 'PEG': 'NYQ', 'PEP': 'NMS', 'PFBC': 'NMS', 'PFE': 'NYQ',
    'PFG': 'NMS', 'PFIS': 'NMS', 'PG': 'NYQ', 'PH': 'NYQ', 'PHM': 'NYQ', 'PII': 'NYQ', 'PINE': 'NYQ', 'PLBC': 'NCM',
    'PLD': 'NYQ', 'PM': 'NYQ', 'PNC': 'NYQ', 'PNR': 'NYQ', 'PNW': 'NYQ', 'POOL': 'NMS', 'POR': 'NYQ', 'POWI': 'NMS',
    'PPG': 'NYQ', 'PRGO': 'NYQ', 'PRI': 'NYQ', 'PRK': 'ASE', 'PRU': 'NYQ', 'PSTL': 'NYQ', 'PSX': 'NYQ', 'PWR': 'NYQ',
    'QCOM': 'NMS', 'QQQ': 'NGM', 'QSR': 'NYQ', 'R': 'NYQ', 'RBA': 'NYQ', 'RDN': 'NYQ', 'REG': 'NMS', 'REXR': 'NYQ',
    'RF': 'NYQ', 'RGA': 'NYQ', 'RGCO': 'NGM', 'RGLD': 'NMS', 'RHI': 'NYQ', 'RICK': 'NGM', 'RJF': 'NYQ', 'RL': 'NYQ',
    'RLI': 'NYQ', 'RMD': 'NYQ', 'RNR': 'NYQ', 'ROK': 'NYQ', 'ROL': 'NYQ', 'ROP': 'NMS', 'ROST': 'NMS', 'RPM': 'NYQ',
    'RPRX': 'NMS', 'RS': 'NYQ', 'RSG': 'NYQ', 'RTX': 'NYQ', 'RY': 'NYQ', 'SAH': 'NYQ', 'SAMG': 'NGM', 'SAN': 'NYQ',
    'SBAC': 'NMS', 'SBFG': 'NCM', 'SBSI': 'NYQ', 'SBUX': 'NMS', 'SCCO': 'NYQ', 'SCI': 'NYQ', 'SCL': 'NYQ',
    'SCVL': 'NMS', 'SEIC': 'NMS', 'SF': 'NYQ', 'SFBS': 'NYQ', 'SFNC': 'NMS', 'SGI': 'NYQ', 'SGU': 'NYQ', 'SHOP': 'NYQ',
    'SHW': 'NYQ', 'SIGI': 'NMS', 'SJM': 'NYQ', 'SJW': 'NMS', 'SKT': 'NYQ', 'SLGN': 'NYQ', 'SMBC': 'NGM', 'SMH': 'NGM',
    'SNA': 'NYQ', 'SNDR': 'NYQ', 'SNV': 'NYQ', 'SNX': 'NYQ', 'SO': 'NYQ', 'SON': 'NYQ', 'SONY': 'NYQ', 'SPFI': 'NMS',
    'SPGI': 'NYQ', 'SPTN': 'NMS', 'SPY': 'PCX', 'SR': 'NYQ', 'SRCE': 'NMS', 'SRE': 'NYQ', 'SSB': 'NYQ', 'SSD': 'NYQ',
    'SSNC': 'NMS', 'SSTK': 'NYQ', 'STAG': 'NYQ', 'STBA': 'NMS', 'STC': 'NYQ', 'STE': 'NYQ', 'STLD': 'NMS', 'STN': 'NYQ',
    'STT': 'NYQ', 'STZ': 'NYQ', 'SUI': 'NYQ', 'SWBI': 'NMS', 'SWK': 'NYQ', 'SWKS': 'NMS', 'SXI': 'NYQ', 'SYBT': 'NMS',
    'SYK': 'NYQ', 'SYY': 'NYQ', 'TCBK': 'NMS', 'TFII': 'NYQ', 'TGLS': 'NYQ', 'TGNA': 'NYQ', 'TGT': 'NYQ', 'THFF': 'NMS',
    'THG': 'NYQ', 'THO': 'NYQ', 'TJX': 'NYQ', 'TKR': 'NYQ', 'TLK': 'NYQ', 'TLT': 'NGM', 'TMO': 'NYQ', 'TMP': 'ASE',
    'TNC': 'NYQ', 'TOL': 'NYQ', 'TOWN': 'NMS', 'TPB': 'NYQ', 'TR': 'NYQ', 'TRN': 'NYQ', 'TRNO': 'NYQ', 'TROW': 'NMS',
    'TRV': 'NYQ', 'TS': 'NYQ', 'TSBK': 'NGM', 'TSCO': 'NMS', 'TSLA': 'NMS', 'TSN': 'NYQ', 'TT': 'NYQ', 'TTC': 'NYQ',
    'TTEK': 'NMS', 'TXN': 'NMS', 'TXNM': 'NYQ', 'TXRH': 'NMS', 'UBCP': 'NCM', 'UBER': 'NYQ', 'UBSI': 'NMS',
    'UCB': 'NYQ', 'UDR': 'NYQ', 'UFPI': 'NMS', 'UGI': 'NYQ', 'UHT': 'NYQ', 'UMBF': 'NMS', 'UMH': 'NYQ', 'UNF': 'NYQ',
    'UNH': 'NYQ', 'UNM': 'NYQ', 'UNP': 'NYQ', 'UNTY': 'NGM', 'UPS': 'NYQ', 'USB': 'NYQ', 'USO': 'PCX', 'USPH': 'NYQ',
    'UTL': 'NYQ', 'UVV': 'NYQ', 'V': 'NYQ', 'VAC': 'NYQ', 'VALU': 'NCM', 'VCTR': 'NMS', 'VICI': 'NYQ', 'VMC': 'NYQ',
    'VMI': 'NYQ', 'VOYA': 'NYQ', 'VRSK': 'NMS', 'VRTS': 'NYQ', 'VST': 'NYQ', 'VZ': 'NYQ', 'WABC': 'NMS', 'WAFD': 'NMS',
    'WAL': 'NYQ', 'WCN': 'NYQ', 'WD': 'NYQ', 'WDFC': 'NMS', 'WEC': 'NYQ', 'WFC': 'NYQ', 'WGO': 'NYQ', 'WH': 'NYQ',
    'WHD': 'NYQ', 'WINA': 'NGM', 'WING': 'NMS', 'WKC': 'NYQ', 'WLK': 'NYQ', 'WLY': 'NYQ', 'WLYB': 'NYQ', 'WM': 'NYQ',
    'WMB': 'NYQ', 'WMS': 'NYQ', 'WMT': 'NYQ', 'WOR': 'NYQ', 'WRB': 'NYQ', 'WSBC': 'NMS', 'WSM': 'NYQ', 'WSO': 'NYQ',
    'WST': 'NYQ', 'WTFC': 'NMS', 'WTRG': 'NYQ', 'WTS': 'NYQ', 'WTW': 'NMS', 'WWD': 'NMS', 'X': 'NYQ', 'XBI': 'PCX',
    'XEL': 'NMS', 'XIFR': 'NYQ', 'XLU': 'PCX', 'XOM': 'NYQ', 'XOP': 'PCX', 'XRAY': 'NMS', 'XYL': 'NYQ', 'YORW': 'NMS',
    'YUM': 'NYQ', 'ZION': 'NMS', 'ZTS': 'NYQ'
}


if __name__ == '__main__':
    for _ in set(SYMBOLS_EXCHANGE.values()):
        print(_)